### ISSUE TITLE
Shortcut to Open URLs

### ISSUE THREAD

**Issue by atomi** [termux/termux-api#1]
Is it possible to map a keyboard shortcut to bring up the list of urls available to open? Alternatively, can we make termux work with this https://github.com/tmux-plugins/tmux-open ?

**Comment by atomi** [comment]
found the relevant cmd ```termux-open-url``` :+1:

**Comment by fornwall** [comment]
The `termux-open-url` command will only work with public URL:s such as http ones. To open files under $HOME, there is a command `termux-share` available in the Termux:API add-on - see http://termux.com/api/.

With the above command it should hopefully be possible to use e.g. tmux-open if one creates a symlink from xdg-open to termux-share.

A shortcut to bring up list of URL:s is a nice suggestion - perhaps VolumeUp+U for the soft keyboard and Ctrl+Shift+U for hardware ones?

**Comment by atomi** [comment]
Thanks for the reply. Anyway I couldn't get tmux-open to work with this version of bash.
Bu yeah <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> sounds fine.

**Comment by fornwall** [comment]
Termux version 0.12 will be available through Google Play in a couple of hours. It adds <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> as a shortcut to open the list of URLs - let me know if you find any issues!

Also, let me know if I can help with the `tmux-open` problems - doing the replacement you mention seems to be the right thing!

**Comment by atomi** [comment]
Thanks!

When using the  <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd> sequence to select a url can we have enter open the browser and  <kbd>y</kbd> to copy it. Or  <kbd>Ctrl</kbd>+<kbd>Enter</kbd> open the url if you'd rather.
