### ISSUE TITLE
Feature request : termux-sms-all

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-api#102]
Ik we have termux-sms-inbox, but it only cats out messages in inbox section, I was wondering if we can have outbox messages also to be cat out. Or at least create a file out of it, also itd nice if we could get feature to choose sim while using `termux-sms-send`

**Comment by bit-garden** [comment]
I would like too, maybe along with api to manage sms itself. I would like to have a terminal sms application opposed to the blinding white one.

**Comment by cgarz** [comment]
Absolutely +1!
I found it very weird not seeing what the people in my inbox were replying to.
I'm also trying to write a terminal sms tool that I connect to over ssh. Outbox support would be very helpful. Currently I can messily read both in and out texts with:
echo "select strftime(\"%Y-%m-%d %H:%M:%S\", date / 1000, \"unixepoch\"),address,type,body from sms order by date asc;" | ../sudo sqlite3 /data/data/com.android.providers.telephony/databases/mmssms.db
If anyone wants to know a way to do it now. It requires the sudo script and sqlite3 installed.
API support would be much cleaner though.

**Comment by xeffyr** [comment]
Closing as SMS feature was removed in https://github.com/termux/termux-api/commit/de44896a01111506590a258f0267400af067b778.
