### ISSUE TITLE
Setting and getting of volume for various streams

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#104]
It would be cool if we coul set the volume with the termux-api.
Something like this:
`termux-volume-set -s MEDIA 6`
`termux-volume-get -s MEDIA`

I think with that I could create a really neat graphical volume mixer (like alsamixer).

**Comment by fornwall** [comment]
This will be available in v0.23 of this app, to be released shortly!

- https://github.com/termux/termux-api/pull/181
- https://github.com/termux/termux-api-package/pull/25
