### ISSUE TITLE
termux-camera-photo: back facing camera does not work

### ISSUE THREAD

**Issue by ilkkajylha** [termux/termux-api#11]
Backwards facing camera, id 0,  produces empty file:

`$ termux-camera-photo -c 0 camera0.jpg`
`$ ls -l`
`total 0`
`-rw-------    1 u0_a260  u0_a260          0 Mar 21 15:32 camera0.jpg`

Frontfacing camera, id 1, works just fine:

`$ termux-camera-photo -c 1 camera1.jpg`
`$ ls -l`
`total 244`
`-rw-------    1 u0_a260  u0_a260          0 Mar 21 15:32 camera0.jpg`
`-rw-------    1 u0_a260  u0_a260     247734 Mar 21 15:33 camera1.jpg`

Device: Samsung Galaxy S4 Active
Model number: GT-I9295
Android version: 5.0.1

$ termux-camera-info 
[
  {
    "id": "0",
    "facing": "back",
    "jpeg_output_sizes": [
      {
        "width": 3264,
        "height": 2448
      },
      {
        "width": 3264,
        "height": 1836
      },
      {
        "width": 2048,
        "height": 1536
      },
      {
        "width": 2048,
        "height": 1152
      },
      {
        "width": 1920,
        "height": 1080
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 640,
        "height": 480
      }
    ],
    "focal_lengths": [
      3.700000047683716
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_ON",
      "CONTROL_AE_MODE_ON_AUTO_FLASH",
      "CONTROL_AE_MODE_ON_ALWAYS_FLASH"
    ],
    "physical_size": {
      "width": 3.8357956409454346,
      "height": 2.8777027130126953
    },
    "capabilities": [
      "backward_compatible"
    ]
  },
  {
    "id": "1",
    "facing": "front",
    "jpeg_output_sizes": [
      {
        "width": 1920,
        "height": 1080
      },
      {
        "width": 1440,
        "height": 1080
      },
      {
        "width": 1392,
        "height": 1392
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 960,
        "height": 720
      },
      {
        "width": 640,
        "height": 480
      }
    ],
    "focal_lengths": [
      1.850000023841858
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_ON"
    ],
    "physical_size": {
      "width": 0.03228941187262535,
      "height": 0.03228941187262535
    },
    "capabilities": [
      "backward_compatible"
    ]
  }
]

**Comment by hjknm1993** [comment]
Sadly, I have a similar result. The 'termux-camera-info' utility have a similar to @ilkkajylha output. Both of resulting files with a different camera ID's have a zero size. Also, tried to store resulting file in a different locations, but the resulting files haven't no one byte.

Asus Z170CG.

**Comment by fornwall** [comment]
This should be fixed in the coming 0.9 update of the Termux:API app which will be released shortly - re-open the issue if the problem remains in that version!

**Comment by Grimler91** [comment]
@taomcj it doesn't sound like the same issue if neither of your cameras work. See #52 and #124 instead. v0.9 is old, version numbering is 0.9, 0.10, 0.11, ..., 0.33.

**Comment by taomcj** [comment]
@Grimler91 Thanks for the info.
