### ISSUE TITLE
termux-notification: Get current notifications

### ISSUE THREAD

**Issue by Tajnymag** [termux/termux-api#110]
Would it be possible to query for currently displayed notifications?

It could work as follows:

```
termux-notification-get --json
```

Result:

```
{
{"appid":"com.facebook.mlite","title":"John Doe","content":"Some content of the notification"},
{"appid":"com.maxmpz.audioplayer","title":"After the Storm","content":"Name of a song fex."}
}
```

**Comment by vovcacik** [comment]
Meanwhile one can grab some data from `dumpsys notification` (root shell required).

**Comment by Tajnymag** [comment]
Interesting, but that doesn't contain whole content of the notifications. Try grepping the output of "dumpsys notification" with content from Termux's permanent or Messenger's multi-line notification.

However, it's better than nothing. Thank you.

**Comment by T-vK** [comment]
Any news on this? I see there has been a related PR?

**Comment by SwapnilSoni1999** [comment]
It says command not found for termux-notification-get

**Comment by Kilo-411** [comment]
Termux file

**Comment by xalexalex** [comment]
@T-vK @SwapnilSoni1999 
The functionality is available in termux/termux-api, but someone must implement it in termux/termux-api-package. Meanwhile from within termux you can use `/data/data/com.termux/files/usr/libexec/termux-api NotificationList`.

**Comment by SwapnilSoni1999** [comment]
@xalexalex thanks alot ❤️

**Comment by fornwall** [comment]
Fixed in version 0.44 of the termux-api package!

**Comment by Benjamin-Loison** [comment]
Just to let the issue readers know: the command is `termux-notification-list`.

**Comment by nozwock** [comment]
Is there a way to retrieve information about the notification's actions?
