### ISSUE TITLE
termux-camera-photo: empty file

### ISSUE THREAD

**Issue by sinus-x** [termux/termux-api#124]
Hi.
Straight to the problem: I have a script, that takes photo using both main and selfie camera. Selfie camera gives me output every time, but the main one almost never. When I execute `termux-camera-photo x.jpg` manually, I get desired JPEG - this does not happen when I run it via script. That way it only creates 0-byte file.

Android 7.0 aarch64, DOOGEE MIX, bash 4.4.12, termux 0.59

As you can see, there can be nothing wrong with the script:
```
cd $HOME/storage/dcim
termux-camera-photo 0.jpg
termux-camera-photo -c 1 1.jpg
```

**Comment by Grimler91** [comment]
Does it work if you reverse the order? I.e. take a photo with the selfie cam first?

**Comment by IAmNotImportant** [comment]
No, still got same result. Zero byte file from main camera.

**Comment by Grimler91** [comment]
I was thinking that the second command interupts the first, but that isn't the case then. 

Try adding a proper shebang to the script, `/data/data/com.termux/files/usr/bin/sh` or `/data/data/com.termux/files/usr/bin/bash` and see if that changes anything.

**Comment by IAmNotImportant** [comment]
I added the `.../bin/bash` and it works now. Wow, thanks a lot.

**Comment by kypi** [comment]
Im having this issue as well, but it doesn't capture from any camera. It doesnt work in commandline nor using a script. Adding the shebang didnt do anything for me.

**Comment by taomcj** [comment]
Hi,

I have the same issue.
termux-info --> https://pastebin.com/qnc2R6zM
termux-camera-info --> https://pastebin.com/U2MB4r9V
termux-api version --> https://pastebin.com/MFriAEeX
out file --> https://pastebin.com/jd45ZhG6

**Comment by qusielle** [comment]
`pkill com.termux.api` can be used as a temporary workaround.
Since the first shot is proceed okay usually, it seems that some resource is not released correctly. So I do pkilling every time for sure and it works fine:
```
pkill com.termux.api
termux-camera-photo -c 0 ${photo_name_main}
pkill com.termux.api
termux-camera-photo -c 1 ${photo_name_front}
pkill com.termux.api
```

**Comment by Ravishan11** [comment]
When i follow the steps.. direct link is not generated what to do? Can someone help?

**Comment by alejandromangione** [comment]
Hi there, I am facing the same issue, when I try to get a picture from `termux-camera-photo -c 0 ./test.jpg` it results in an empty file. I am using a rooted android, (moto x play) with Lineage Android 10. 

Also, I tried from the front camera and it gets the same result. 

If someone has any thoughts on that, I would appreciate the help. 
Thanks.

**Comment by sparrowyang** [comment]
I have same problem:
 ```
~  termux-info 
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://mirrors.bfsu.edu.cn/termux/game-packages-24/ games stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# science-repo (sources.list.d/science.list)
deb https://mirrors.bfsu.edu.cn/termux/science-packages-24/ science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.192-perf-g5952833 #1 SMP PREEMPT Thu Jul 23 21:11:42 CST 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
MI 8 Lite

```

**Comment by andrey-pavlenko** [comment]
There is same problem: empty files

```sh
[u0_a77@localhost ~]$ termux-info 
Application version:
0.113
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.10.108-lineageos-g038e5f6 #1 SMP PREEMPT Tue Feb 12 14:46:53 UTC 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi 3
```

**Comment by lgommans** [comment]
Can confirm on a Fairphone 3+, the `pkill com.termux.api` trick posted above does not work for me. I also needed to `pm grant com.termux android.permission.CAMERA` or it would give an error (did this as root, not sure if needed); I also added the permission for `com.termux.api` but no change. Applies to both cameras (0 and 1). `logcat` shows the following:

```
08-23 23:35:05.818 20883 20883 D AndroidRuntime: Calling main entry com.termux.termuxam.Am
08-23 23:35:05.862 11329 12874 I CameraService: CameraService::connect call (PID -1 "com.termux.api", camera ID 0) for HAL version default and Camera API version 2
08-23 23:35:06.171 11329 12874 E CameraService: Access Denial: can't use the camera from an idle UID pid=20445, uid=10159
08-23 23:35:06.174 20445 20897 E termux-api: Error getting camera
08-23 23:35:06.174 20445 20897 E termux-api: android.hardware.camera2.CameraAccessException: CAMERA_DISABLED (1): validateClientPermissionsLocked:1195: Caller "com.termux.api" (PID 10159, UID 20445) cannot open camera "0" from background (calling UID 10159 proc state 11)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1010)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:545)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.hardware.camera2.CameraManager.openCameraForUid(CameraManager.java:726)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.hardware.camera2.CameraManager.openCamera(CameraManager.java:654)
08-23 23:35:06.174 20445 20897 E termux-api: 	at com.termux.api.PhotoAPI.takePicture(PhotoAPI.java:62)
08-23 23:35:06.174 20445 20897 E termux-api: 	at com.termux.api.PhotoAPI.lambda$onReceive$0(PhotoAPI.java:49)
08-23 23:35:06.174 20445 20897 E termux-api: 	at com.termux.api.-$$Lambda$PhotoAPI$TVeyrywhoGcxn5rY6HAcKkOPTo0.writeResult(Unknown Source:8)
08-23 23:35:06.174 20445 20897 E termux-api: 	at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:133)
08-23 23:35:06.174 20445 20897 E termux-api: 	at com.termux.api.util.-$$Lambda$ResultReturner$oCU8JqHW5HLMrNZa40ThjAWcwzo.run(Unknown Source:8)
08-23 23:35:06.174 20445 20897 E termux-api: 	at java.lang.Thread.run(Thread.java:923)
08-23 23:35:06.174 20445 20897 E termux-api: Caused by: android.os.ServiceSpecificException: validateClientPermissionsLocked:1195: Caller "com.termux.api" (PID 10159, UID 20445) cannot open camera "0" from background (calling UID 10159 proc state 11) (code 6)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.os.Parcel.createException(Parcel.java:2357)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.os.Parcel.readException(Parcel.java:2340)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.os.Parcel.readException(Parcel.java:2282)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.hardware.ICameraService$Stub$Proxy.connectDevice(ICameraService.java:634)
08-23 23:35:06.174 20445 20897 E termux-api: 	at android.hardware.camera2.CameraManager.openCameraDeviceUserAsync(CameraManager.java:512)
08-23 23:35:06.174 20445 20897 E termux-api: 	... 8 more
```

**"can't use the camera from an idle UID" sounds like the key issue.** Looking that up, I don't really get any good results explaining what is going on with an "idle UID" or how to resolve it. Anyone have ideas?

**Comment by SDRausty** [comment]
>`cd $HOME/storage/dcim`

I have noticed a larger quantity of zero size files on cheaper and slower external micro sd cards;  Moreso when there is more than one read/write cycle attempting to read/write via buses to cards.  Do you still have the zero size file issue when files are saved to device internal memory; i.e. $HOME/pics and similar.

**Comment by SDRausty** [comment]
>`cd $HOME/storage/dcim`

I have noticed a larger quantity of zero size files on cheaper and slower external micro sd cards;  Moreover when there is more than one read/write cycle attempting to read/write via buses to cards.  Do you still have the zero size file issue @sinus-x when files are saved to device internal memory; i.e. $HOME/pics and similar?

I am using these shell loops to test this amazing command; `termux-camera-photo`:

`while true ; do for i in {0..7} ; do sleep 2 && termux-camera-photo -c $i $i.$(date +%s).jpg && sleep 2 ; done ; done &`

Has anyone found more than eight functioning cameras per device that save files correctly?

**Comment by GitHubQueenn** [comment]
Hi. My photos are also showing as 0 bytes. Using Secure Task in Tasker to trigger the Termux termux-camera-photo command when failed login attempt is made. Help?
