### ISSUE TITLE
termux-tts-speak volume cannot be adjusted

### ISSUE THREAD

**Issue by davidsands** [termux/termux-api#13]
The stream, AudioManager.STREAM_SYSTEM is not adjustable on my Android 5.0 Asus Fonepad through the volume control app. I tried adjusting the STREAM_SYSTEM volume manually through a Rhino JS tool (Scriptit), but although I can adjust the STREAM_MUSIC that way, STREAM_SYSTEM stays at full volume. 

Other tts systems seem to use either STREAM_DEFAULT or STREAM_MUSIC. Are there constraints which cause termux to use STREAM_SYSTEM?

**Comment by fornwall** [comment]
I'm thinking about going for `STREAM_ALARM` here, so that e.g. a background script can be used to speak an alarm when it detects something and stand out from e.g. music playing (which may be muted).

This will be in version 0.9 of the Termux:API app which will be released shortly - re-open this issue if `STREAM_ALARM` does not work well for you!

**Comment by fornwall** [comment]
Scratch the above - after playing around with it STREAM_NOTIFICATION feels more appropriate.

**Comment by davidsands** [comment]
Thank you for your reply. 

Since which stream is used may depend on what the tts is used for (I'm using it for language study), is there any chance that an alternate stream could be chosen via an additional command line switch? 'termux-tts-speak -l es -s music', perhaps; so that, in my case, the standard hardware volume controls could be used for tts apps running in the background? 


-------- Original Message --------

**Comment by fornwall** [comment]
> Since which stream is used may depend on what the tts is used for (I'm using it for language study), is there any chance that an alternate stream could be chosen via an additional command line switch? 'termux-tts-speak -l es -s music', perhaps; so that, in my case, the standard hardware volume controls could be used for tts apps running in the background?

@davidsands This has now been implemented in version 0.18 of the termux-api package (you also need the Termux:API app at version 0.9 or greater). It's now possible to specify the stream with the `-s` option - see https://termux.com/add-on-api.html#termux-tts-speak for full documentation.

**Comment by davidsands** [comment]
That's great! Thank you.
