### ISSUE TITLE
termux-notification - missing executable error

### ISSUE THREAD

**Issue by 4oo4** [termux/termux-api#130]
I noticed with the latest update that I don't seem to be able to send notifications anymore, it gives the below error:

```
execv("/data/data/com.termux/files/usr/bin/am"): No such file or directory

```

I have a bash script I run that calls both `termux-notification` and `termux-toast`, and both are giving me that error message. Running LineageOS 14.1-20180205-NIGHTLY for Nexus 5x.

Cheers

**Comment by 4oo4** [comment]
Ahh, looks like it got moved to `/data/data/com.termux/files/usr/bin/applets/am`? For now I'll just use a symlink as a workaround.

**Comment by Grimler91** [comment]
Install termux-am with `pkg in termux-am`, there is a missing dependency here that we should fix.

**Comment by 4oo4** [comment]
@Grimler91 Will do, thanks!

**Comment by fornwall** [comment]
Thanks for reporting!

This is now fixed as `termux-tools` (which everyone has installed) depends on `termux-am`, so every existing user will have it pulled in as a dependency on the next update (and new ones will have `termux-am` preinstalled)!
