### ISSUE TITLE
API command request: launch-activity

### ISSUE THREAD

**Issue by ClockGen** [termux/termux-api#132]
Launching external activities would be a huge boost to device-automation capatibilities of termux-api.

**Comment by Auxilus** [comment]
You can use `am start` to start activities

**Comment by ClockGen** [comment]
This still requires INTERACT_ACROSS_USERS_FULL permission.

**Comment by Auxilus** [comment]
Does `--user 0` help?

**Comment by ClockGen** [comment]
Yes indeed, big thanks.
