### ISSUE TITLE
Airplane mode 

### ISSUE THREAD

**Issue by sicaboy** [termux/termux-api#138]
Is there any chance Termux api is able to control phone’s airplane mode turn on/off.

**Comment by rgh36167** [comment]
On Mon, Feb 19, 2018 at 05:29:39AM -0800, David Shen wrote:
> Is there any chance Termux api is able to control phone’s airplane mode turn on/off.

no, apparently not accessible programmatically in any way since Android 2.3

Wondering if data on/off would be doable?

**Comment by sicaboy** [comment]
Thanks @rgh36167 
I'm going to run some automation tasks (generally speaking, data crawler), which requires changing IP address, turning on/off data won't change the external IP address, but toggle Airplane Mode does.

I searched the web, says if the device is rooted, apps can still control airplane mode even above android 4.2.


```java
private final static String COMMAND_AIRPLANE_ON = "settings put global airplane_mode_on 1 \n " +
            "am broadcast -a android.intent.action.AIRPLANE_MODE --ez state true\n ";

private final static String COMMAND_AIRPLANE_OFF = "settings put global airplane_mode_on 0 \n" +
            " am broadcast -a android.intent.action.AIRPLANE_MODE --ez state false\n ";
```

**Comment by sicaboy** [comment]
I will try to implement it myself. I cloned the code but Android Studio has an error when I tried to run termux-api.
Error running app: Default Activity not found
Could you tell me how to install this on my device?

**Comment by sicaboy** [comment]
I've forked and implemented this feature with rooted devices. If anyone needs it, just let me know, I will open pull request. Closing this ticket.

**Comment by danieldjewell** [comment]
Interestingly, it appears possible to grant "WRITE_SECURE_SETTINGS" to an app via adb. 

It does not appear to require root. If so, that would open the Termux API to many new and wondrous possibilities. 

https://tasker.joaoapps.com/userguide/en/help/ah_secure_setting_grant.html

**Comment by xeffyr** [comment]
> It does not appear to require root.

Yes, it is not require root.
But don't forget that **ADB has special permissions**, unlike regular Android applications.
