### ISSUE TITLE
termux-sms-send has no command-line option to feed a string to send as sms.

### ISSUE THREAD

**Issue by cpb83** [termux/termux-api#14]
Any possibility of adding a command line argument to take a string an send it to the recipient? Without this, the interface is unusable from any other program.

**Comment by cathalgarvey** [comment]
Hey @cpb83, what language/program are you using? Most frameworks allow you to specify stdin, one way or another, so although it's a little more awkward than a terminal flag it should still be possible?

For example, in Python you can use `subprocess` to create a piped-command, then feed stdin through a StringIO, if memory serves. And in Go, you can attach stdin readers to an `exec.Cmd` and have it read from those (as [I've done](/cathalgarvey/go-termux)).

Happy to help if I'm able!

**Comment by cpb83** [comment]
@cathalgarvey Yeah, I could try python, was using bash where it's not as obvious. Thanks for the ideas!
@fornwall Seems like you totally fixed my issue! Thanks!

**Comment by fornwall** [comment]
Yes, it's fixed now in the latest version of the `termux-api` package. I think it's a good idea generally to allow input both from arguments (for easier calling from other programs) and from stdin (for easier piping of e.g. files).

**Comment by fornwall** [comment]
@cpb83 A heads up: In the newly updated `termux-api` package at version 0.18 the `termux-sms-send` command has been tweaked slightly:

```
Usage: termux-sms-send -n number[,number2,number3,...] [text]
Send a SMS message to the specified recipient number(s).
The text to send is either supplied as arguments or read from stdin
if no arguments are given.

  -n number(s)  recipient number(s) - separate multiple numbers by commas
```

Also, be sure to update to version 0.10 of the Termux:API app.
