### ISSUE TITLE
termux-sms-send doesn't work with third party app

### ISSUE THREAD

**Issue by mayureshw** [termux/termux-api#141]
A peculiar setup forces me to use an app provider by cellular provider (app Jio4gVoice by provider Jio, India). The SIM card is placed in a mifi router via which only the provider's app can send SMSes. I have to use this arrangement as my phone is not VoLTE compatible.

I think, in theory termux-sms-send should be able to talk with any default SMS app. But that's not happening with above app. Are there any things / work arounds that I can try?

E.g I tried switching the SMS app to stock default app - though it can't actually send SMS, it might at least save it as a draft and then I can switch the app again to above one to send the draft. But termux-sms-send does not seem to work that way (i.e. save a draft if it could not send).

**Comment by xeffyr** [comment]
Closing as SMS feature was removed in https://github.com/termux/termux-api/commit/de44896a01111506590a258f0267400af067b778.
