### ISSUE TITLE
termux-camera-photo produces empty file

### ISSUE THREAD

**Issue by fornwall** [termux/termux-api#15]
_From @destiny07 on March 27, 2016 8:31_

`termux-camera-photo -c 0 pic1.jpg` produces a file of size 0B. When opened with gallery, it say's thumbnail cannot be retrieved. 

_Copied from original issue: termux/termux-packages#185_

**Comment by fornwall** [comment]
_From @vaites on April 7, 2016 6:51_

Same problem here with Android 6.0 and a Nexus 5, with both cameras...

**Comment by vaites** [comment]
The camera interface is no opened: command just finishes without error or dialog...

**Comment by cathalgarvey** [comment]
@vaites I think that is normal behaviour; this API snaps a photo and saves it to a filename (optionally, a user-selected filename). It also has an undocumented option for photo dimensions I haven't toyed with. But it doesn't open the camera "app" if that's what you mean.

**Comment by vaites** [comment]
Don't know if camera interface must open (I think is necessary to focus or
use flash and zoom) but with or without this, filesize can't be zero.

**Comment by cathalgarvey** [comment]
Indeed, I wasn't commenting on the original problem, just @vaites' concern that the termux-camera-photo tool returns silently.

On 19 April 2016 12:31:33 IST, "David Martínez" <notifications@github.com> wrote:
>Don't know if camera interface must open (I think is necessary to focus
>or
>use flash and zoom) but with or without this, filesize can't be zero.
>
>El mar., 19 abr. 2016 13:27, Cathal Garvey <notifications@github.com>
>escribió:
>
>> @vaites <https://github.com/vaites> I think that is normal behaviour;
>> this API snaps a photo and saves it to a filename (optionally, a
>> user-selected filename). It also has an undocumented option for photo
>> dimensions I haven't toyed with. But it doesn't open the camera "app"
>if
>> that's what you mean.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/termux/termux-api/issues/15#issuecomment-211867196>
>>
>
>
>---
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/termux/termux-api/issues/15#issuecomment-211868071

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by fornwall** [comment]
This should be fixed in the coming 0.9 update of the Termux:API app which will be released shortly - re-open the issue if the problem remains in that version!

**Comment by SereznoKot** [comment]
Version 0.10, OnePlus X, Android 5.1.1 Oxygen OS 2.2.1. Same issue, trying both cameras, saving to ~ folder. After a long pause I get a 0 byte file.

**Comment by tarjeiba** [comment]
@fornwall Is 0.9 still not released, or am I missing something?

**Comment by vishalbiswas** [comment]
@tarjeiba Termux:API is at 0.15, now.

**Comment by tarjeiba** [comment]
@vishalbiswas I must be completely turned off today, I thought about it as "point one five", not " point fifteen".

Okay, so this issue is still going strong on my S7.
