### ISSUE TITLE
turmyx: a python-based launcher for termux-url-opener and termux-file-editor 

### ISSUE THREAD

**Issue by isman7** [termux/termux-api#151]
FYI. I'v been working on that idea for a couple of days: https://github.com/isman7/turmyx

I plan to introduce termux-api some how trying to automate the parser.

Ismael

**Comment by isman7** [comment]
I want to implement wrapping / parsing the 
Termux API as subpackage of turmux because I haven't find another one written in python.

**Comment by Grimler91** [comment]
It's probably easier to spread information like this through the various termux communities: https://wiki.termux.com/wiki/Community
