### ISSUE TITLE
MediaPlayerAPI: calling it without any argument could crash the API app

### ISSUE THREAD

**Issue by tomty89** [termux/termux-api#154]
i.e. `$PREFIX/libexec/termux-api MediaPlayer`

The API would crash because:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toUpperCase()' on a null object reference
```

Note that it would probably crash even if `command` is `switch`ed without `toUpperCase`.

Btw, what's the point of the `toUpperCase` anyway?

@dkramer95

**Comment by dkramer95** [comment]
Good catch... I did that as to ensure that regardless of case the command would work which I guess isn't really needed... But you're right, if command is null and we call toUpperCase it would in fact crash.
