### ISSUE TITLE
FYI: termux-api in Go!

### ISSUE THREAD

**Issue by cathalgarvey** [termux/termux-api#16]
Hey folks,

Thought you'd find this interesting; I rewrote in Go the C tool and scripts from the `termux-api` tools normally installed through apt to use this App. In theory, this means you can compile Go apps that make calls to `termux-api` to use the APIs from Go.

Lots of it is completely untested, including things like "sending Stdin down a Unix pipe". Only some tools have been tested at all.

Also, the struct values for SMS messages from SmsInbox and from TTS engines are currently unknown because I get no results for these on my phone (SMSsecure protects sms, and no TTS engines).

Thanks for a great app, I'm looking forward to playing with pure-Go pseudo-apps thanks to Termux. :)

**Comment by cathalgarvey** [comment]
Derp, the Repo: https://github.com/cathalgarvey/go-termux

**Comment by fornwall** [comment]
This is awesome!

Let me know if you have any ideas for further api calls exposing Android functionality, or if things can be changed for easier wrapping!

**Comment by cathalgarvey** [comment]
@fornwall Glad you like it! In recent pushes I've gotten it working a lot better, and have started working on refining the spaghetti-ish parts of the code.

One thing I'd *love* is if I could access the APIs from the standard adb shell, but for some reason it fails at the part where I expect the API to connect to my unix sockets. The same program runs in termux but not in adb shell.

Is this something the Termux:API app can be modified to permit, or is it an unavoidable security layer? If it could be fixed, then I could look into code that could make this a general-purpose phone-automation layer, which would be pretty awesome. :)

In terms of blue-sky API feature requests, it'd be kinda neat to have:

* Access to radio data, like nearby towers, for potential metrics-gathering uses
* IR blaster API! Would be neat to have some way to send arbitrary signals. I'm not sure if they IR blaster API also lets you receive IR data, that'd be excellent also.

Will think of others. :)

**Comment by fornwall** [comment]
NOTE: You need version 0.10 (just released) of the Termux:API app and 0.18 of the termux-api package for the below!

> IR blaster API! Would be neat to have some way to send arbitrary signals. I'm not sure if they IR blaster API also lets you receive IR data, that'd be excellent also.

This has now been added - see the `termux-infrared-frequencies` and `termux-infrared-transmit` commands at https://termux.com/add-on-api.html. It's still untested as I had no IR-capable device available when writing it, let me know if there are any trouble!

> Access to radio data, like nearby towers, for potential metrics-gathering uses

I added `termux-telephony-cellinfo` and `termux-telephony-deviceinfo` - though I'm not sure if that was the kind of information you wanted :).

**Comment by fornwall** [comment]
Another heads up: The SMS sending API can now take several recipients in one API call by using a `recipients` string array extra, instead of the previous single `recipient` string extra.

**Comment by fornwall** [comment]
> One thing I'd love is if I could access the APIs from the standard adb shell, but for some reason it fails at the part where I expect the API to connect to my unix sockets. The same program runs in termux but not in adb shell.
> 
> Is this something the Termux:API app can be modified to permit, or is it an unavoidable security layer? If it could be fixed, then I could look into code that could make this a general-purpose phone-automation layer, which would be pretty awesome. :)

I'll look into it, if we can add the possibility for adb to access it!

Note that you can also connect to Termux over ssh or telnet - but it doesn't solve exactly the same use case as adb I guess.

**Comment by cathalgarvey** [comment]
Thanks so much!

I'm still trying to fix #20 in my own implementation, it's boggling me. Stdin args work fine but flag args were getting mangled. I'm not sure how stuff is actually getting passed by the shell scripts to `am` in the default scripts, whether they're shell-escaped and quoted or passed as actual flags, and can't replicate actual behaviour yet in the Go.

However, as soon as that's fixed (should be a top-level fix that makes all the underlying functions work or break simultaneously..), I'll look into perhaps baking in some reverse-shell functions for ADB, too (optional of course, not default).

Thanks for the features! Looking forward to playing with the IR blaster in particular, so far I've only been using it as a TV-be-gone. :)

**Comment by rion24976-a11y** [comment]
Command setup termux games
