### ISSUE TITLE
newly added apis not working 

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-api#161]
termux-media-player and termux-torch are not working.

aarch64

**Comment by Auxilus** [comment]
sry my bad, Termux:API wasn't updated

@fornwall something wrong with the app name in fdroid (should be Termux:API) 
![screenshot_20180409-181048](https://user-images.githubusercontent.com/23075789/38498272-776a87ea-3c21-11e8-9265-08632230bb59.png)

**Comment by fornwall** [comment]
The version on F-Droid lags a bit, but should be updated now!

Can you file an issue at https://gitlab.com/fdroid/fdroidclient/issues for the "Unknown" name?
