### ISSUE TITLE
Wrong version of Termux API on F-Droid

### ISSUE THREAD

**Issue by yvan-sraka** [termux/termux-api#165]
Hello,

The version of [Termux API on F-Droid](https://f-droid.org/packages/com.termux.api/) does not match the version on the Google Play Store, and it is displayed under the name `Unknown` ...

Do you know who manages the publication of the app?

Thank you in advance,

**Comment by fornwall** [comment]
The version on F-Droid seems to be updated now, right?

F-Droid scans repos for releases (tags) automatically. It has some delay, but normally updates should reach F-Droid within a day or two.

As for the unknown name - can you report that at: https://gitlab.com/fdroid/fdroidclient/issues ?
