### ISSUE TITLE
F-Driod website and mobile app ~missing~ package name

### ISSUE THREAD

**Issue by ChiefMikeK** [termux/termux-api#166]
## I would suggest you rename _ALL_ of the modules by adding a plus sign to them

>  **Termux+: <_module?_>**
so that they will group properly see 2nd image below

see **\~missing\~** on webpage
https://f-droid.org/en/packages/com.termux.api/

![screenshot](https://user-images.githubusercontent.com/20070053/38801940-bde75000-419d-11e8-9192-c3b048176a31.png)

![termux01](https://user-images.githubusercontent.com/20070053/38802766-f07b1856-419f-11e8-9b74-d7f348fd9968.png)

**Comment by Grimler91** [comment]
Thanks for the screenshots. 
Why would adding a "+" help?

@yvan-sraka reported the same error last week in https://github.com/termux/termux-api/issues/165 and there is an open issue about this at [fdroid's repo](https://gitlab.com/fdroid/fdroidserver/issues/475).
