### ISSUE TITLE
Where can i get sign key?

### ISSUE THREAD

**Issue by meshr-net** [termux/termux-api#167]
Hi,

Readme says: "note that this app needs to be signed with the same key as the main Termux app for permissions to work".
Where can i get this sign key? I successfully build the app on ubuntu but i don't know how to sign unsigned apk...
Please help

**Comment by xeffyr** [comment]
You can use an application ZipSigner for this: https://play.google.com/store/apps/details?id=kellinwood.zipsigner2

Just sign Termux application and addons (such as Termux:API) with the same key. Then you need to reinstall all apks.
