### ISSUE TITLE
How can this be built on device?

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-api#174]
How can this be built on device?

**Comment by sdrausty** [comment]
Failed building monthly; assistance requested.

**Comment by sdrausty** [comment]
https://github.com/termux/proot ditto; doesn't build; what good is it if it does not build as requested?

**Comment by Grimler91** [comment]
It not possible to build termux-api on device. It requires gradle, which we don't have. It might not even be supported on arm based devices.

**Comment by sdrausty** [comment]
my ? (question) wasn't arm; was x86 (beyond x86^86)

**Comment by sdrausty** [comment]
my ? (question) wasn't arm; was x86 (beyond x86^86)

**Comment by sdrausty** [comment]
can u plz answr x86? @grimler91

**Comment by sdrausty** [comment]
can u plz answr x86? @grimler91

**Comment by sdrausty** [comment]
IN Android studio(root it?;walk on dex);some such:(should i venter into da attic,wadz dat?;surplus)

**Comment by sdrausty** [comment]
#174

**Comment by sdrausty** [comment]
>> Failed building monthly; assistance requested.

**Comment by sdrausty** [comment]
174 :starz: vs :starz:

**Comment by sdrausty** [comment]
doez talkz in te!ch lounge;enlightenung;`Setting up play-audio (0.5) ...
$ while true;do play-audio storage/downloads/floyd/pink/gig/*Gig*;done
/`

**Comment by sdrausty** [comment]
`:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
:: Starting full system upgrade...
resolving dependencies...
:: There are 3 providers available for java-environment:
:: Repository extra
   1) jdk7-openjdk  2) jdk8-openjdk  3) jdk9-openjdk

Enter a number (default=1):
looking for conflicting packages...

Packages (29) avahi-0.7+4+gd8d8c67-1  hicolor-icon-theme-0.17-1
              java-environment-common-3-1  java-runtime-common-3-1
              jdk7-openjdk-7.u171_2.6.13-1  jre7-openjdk-7.u171_2.6.13-1
              jre7-openjdk-headless-7.u171_2.6.13-1  lcms2-2.9-1
              libcups-2.2.7-2  libdaemon-0.14-4  libice-1.0.9-2
              libjpeg-turbo-1.5.3-1  libpng-1.6.34-2  libsm-1.2.2-2
              libtiff-4.0.9-1  libx11-1.6.5-1  libxau-1.0.8-3  libxcb-1.13-1
              libxdmcp-1.1.2-1  libxext-1.3.3-1  libxmu-1.1.2-2  libxt-1.1.5-2
              nspr-4.19-1  nss-3.37.1-1  xcb-proto-1.13-1  xdg-utils-1.1.3-1
              xorg-xset-1.2.4-1  xorgproto-2018.4-1  gradle-4.7-1

Total Download Size:   127.03 MiB
Total Installed Size:  179.16 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 nspr-4.19-1-armv7h       168.7 KiB   260K/s 00:01 [######################] 100%
 nss-3.37.1-1-armv7h     1261.8 KiB   356K/s 00:04 [######################] 100%
 java-environment-co...  1792.0   B  0.00B/s 00:00 [######################] 100%
 java-runtime-common...     4.2 KiB   417K/s 00:00 [######################] 100%
 libjpeg-turbo-1.5.3...   256.2 KiB   294K/s 00:01 [######################] 100%
 libtiff-4.0.9-1-armv7h   765.7 KiB   773K/s 00:01 [######################

**Comment by sdrausty** [comment]
gradle is NOT issue @grimler91

**Comment by sdrausty** [comment]
Did u miss`[17:32 home ]$ pc gradle
:: Synchronizing package databases...` ? i think nit

**Comment by sdrausty** [comment]
Did u miss`[17:32 home ]$ pc gradle
:: Synchronizing package databases...` ? i think u did not

**Comment by sdrausty** [comment]
teacher's pet?

**Comment by sdrausty** [comment]
r u?

**Comment by xeffyr** [comment]
> does NOT compile, nor build in Android Studio;why?

Why ? Reasons why it doesn't build:
1. You have a broken Android Studio/Android SDK installation.
2. You are running Android Studio in your TermuxArch under proot (isn't it ?).

For me everything builds...
![2018-06-02 00-35-00](https://user-images.githubusercontent.com/25881154/40864747-c8d439f4-65fd-11e8-999f-e17fa4240698.png)

**Comment by sdrausty** [comment]
[17:32 home ]$ pc gradle
:: Synchronizing package databases...

**Comment by sdrausty** [comment]
@xeffer And studio is;on lap(top)

**Comment by sdrausty** [comment]
s

**Comment by xeffyr** [comment]
Yes this is on laptop.

**Comment by sdrausty** [comment]
@Xeffer Android studio(w** iz it?) is;on lap(tops)... [more dan 1]

**Comment by sdrausty** [comment]
i wanna perms 4my apps;simple?

**Comment by sdrausty** [comment]
i wanna perms 4my apps;simple?

**Comment by sdrausty** [comment]
>You have a broken Android Studio/Android SDK installation.
You are running Android Studio in your TermuxArch under proot (isn't it ?).

Termux and addons built correctly, but api would not((.
