### ISSUE TITLE
Sound Fix..Help

### ISSUE THREAD

**Issue by foodmaher** [termux/termux-api#178]
I am a novice in Linux system and do not know how to launch a sound system I've installed the following commands only 

#@#@#@#@#@#@#@#@#@#@#@#@
............................Termux ...................................................................................................
termux-setup-storage
apt update
apt upgrade -y
apt install git wget proot -y
git clone https://github.com/Bhai4You/Termux-Os
cd Termux-Os
chmod +x Termux-Os.sh requirement.sh
./requirement.sh
./Termux-Os.sh

............................Fedora.....................................................................................................

startfedora
dnf update -y
dnf upgrade
dnf install tigervnc-server -y
dnf install xterm -y
dnf group install lxde-desktop -y
dnf install java-1.8.0-openjdk-headless -y && dnf install java-1.8.0-openjdk -y && dnf install java-1.8.0-openjdk-devel -y

................................End................................
الكاتب ماهر
اوامر تثبيت Fedora و lxde و java-jdk
netbeans IDE 8.0
......................................................................
&$&$&$&$&$&$&$&$&$&$&$&$&$&$&$&

My problem is I do not know how to launch system sounds and I do not have a Wine application on fedora arm64 and do not work lxqt or cinnamon on fedora after downloading them in termux only lxde works and i also have problem in netbeans in javafx libraries and audio also i mean the problem of configuring a new file at Using vncserver where I am making a new server and not using the same previous name has solved my problems
I miss the pulseaudio

**Comment by foodmaher** [comment]
I apologize I do not speak English only Arabic
But use the google translator, which is bad for translating sentences

**Comment by Epictek** [comment]
Not a termux-api issue but install pulseaudio and run `pulseaudio --daemon`?
