### ISSUE TITLE
termux-dialog hangs if dialog loses focus.

### ISSUE THREAD

**Issue by PluMGMK** [termux/termux-api#193]
Since the update of the DialogAPI, it is now possible for termux-dialog to hang if the dialog box loses focus.
For example: I use the Password Store app, which can prompt to autofill passwords. If my GPG passphrase is not in memory, it needs to prompt me for that in turn. So, if I have a termux-dialog asking for a password, and I ask Password Store to autofill it, and it asks me for my GPG passphrase, then the original termux-dialog loses focus and disappears. With the old DialogAPI this caused termux-dialog to exit, but now it just hangs, and I need to terminate it manually.

**Comment by fornwall** [comment]
Thanks for reporting! This has been fixed in v0.26 by @cvirostek in https://github.com/termux/termux-api/pull/200.

Version 0.26 of the app has been released and should be available as an update shortly.
