### ISSUE TITLE
SMS in JSON

### ISSUE THREAD

**Issue by vdakalov** [termux/termux-api#197]
The project main page says "Grep through your SMS inbox". Really? How you suggest me grep by prettified json? :DD
This is bash, not JavaScript! What about output sms in plain format like a this:
```
2018-07-25 12:43:01 1 "sender name" "phone number" "message body"
```
or in csv
```
2018-07-25 12:43:01; 1; sender name; phone number; message body
```
then it really grepable!))

**Comment by Neo-Oli** [comment]
Well, since you have the command line json parser `jq` available, you can easily convert the json to any format.
``` 
termux-sms-inbox -nl 100 |
jq -r '.[] | .received + "; " + (.read|tostring)  + "; " + .sender + "; " + .number + "; "  + .body'
```
Then it is very easily also greppable
```
$ termux-sms-inbox -nl 100 | jq -r '.[] | .received + "; " + (.read|tostring)  + "; " + .sender + "; " + .number + "; "  + .body' | grep "Some Dude"
2018-07-21 15:18; true; Some Dude; +4179000000; Aber heissliim, faus de grad gsesch
```

**Comment by vdakalov** [comment]
Yes it's true! I know too much methods for works with `JSON` in bash. For example

```bash
termux-sms-inbox -nl 100 | node parser.js
```
But `bash` can't work with `JSON` by default and you can't just grep by sms inbox. You need think about how you want do it. You need know about `jq` or other method for work with `JSON` in `bash`. It is not reasonable by my opinion.

**Comment by empjustine** [comment]
By definition, `grep` isn't included in `bash` as built-in either.

And to find something you need to think about what you're attempting to get at the very least.

On the other hand, if you really want a single line with everything, what prevents you from using (also not a bash built in, by the way)

`termux-sms-inbox | sed ':a; /,$/ { N; s/\n//; ba };'`

I hate JSON as well, but I can't deny that when the underlying structure is simple, it's easy to convert it into other formats.
