### ISSUE TITLE
ctrl+shit++ key not increasing text size

### ISSUE THREAD

**Issue by atomi** [termux/termux-api#2]
Not sure where else to post this. I don't have a G+ account (and never will).

The sequence <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>+</kbd> is not working on my k810 bluetooth keyboard (tenkey less). I think since the <kbd>+</kbd> requires <kbd>shift</kbd> to register and <kbd>shift</kbd> is already being used for the sequence the text size increment is not registering.

**Comment by fornwall** [comment]
@atomi This has now been fixed in the 0.14 update of Termux, which should be available in the Play Store as an update in a couple of hours.

Thanks for describing the issue, let me know if there is any remaining problem!
