### ISSUE TITLE
Various commands cut off after the first word. (termux-notification, termux-dialog)

### ISSUE THREAD

**Issue by JKathmann** [termux/termux-api#20]
After update && upgrade, I found this behaviour:

`termux-dialog -t "Foo Bar"`
->empty mask

`termux-notification -c "hello world" -t "foo bar"`
->
->hello world

**Comment by JKathmann** [comment]
this works:

`termux-dialog -t "foo bar" -i "hello world"`
->foo bar
->hello world

`termux-notification -c "hello world" -t "foo bar" -i 123`
->foo bar
->hello world

**Comment by fornwall** [comment]
Thanks, this has been fixed in version 0.17 of the termux-api package to which you can update now.

There has been some flux in the scripts to handle whitespace and argument parsing correctly, hopefully the solution used now is correct and they will stabil
