### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by Craeckie** [termux/termux-api#21]
I have installed the App and the package, but when I run any command of the API it just blocks until I cancel it with CTRL-C.
Displaying the help (-h) works though.

**Comment by fornwall** [comment]
You have installed the Termux:API app?

Which device and Android version is this? Does running `logcat` show anything?

**Comment by Craeckie** [comment]
Yes, Termux:API is installed.

Android: 5.0.2
Device: ZE500KL (ASUS Zenfone 2 Laser)

Logcat didn't show anything relevant, I don't have root though, not sure if that's necessary.

**Comment by fyrthis** [comment]
Hi, I have the same issue.
I installed termux app, then run apt update/upgrade then apt install termux-api.
I tried termux-battery-status and termux-camera-photo file , but nothing happened, like if the process was running endless loop.. Did I miss something ?

Samsung S7 / Android 6.0.1

**Comment by fornwall** [comment]
@fyrthis Have you installed [the Termux:API](https://play.google.com/store/apps/details?id=com.termux.api&hl=en) app?

**Comment by fyrthis** [comment]
Oh no I did not ! Thank you !
But I don't understand, why should I need to install both app and package termux-API ?

**Comment by fornwall** [comment]
@fyrthis The termux-api package installed by apt contains the client scripts calling the API.

The Termux:API contains the background service implementation of the API which the client scripts connect to. It's not possible to install outside of an app, and it's not bundled in the main Termux app to avoid requiring a lot of permission for everyone.

**Comment by Craeckie** [comment]
Seems to be an Asus specific issue.
Solved it by going to settings -> Power management -> Auto-start Manager -> allow Termux:API.
Adding a hint in the app description would be useful.

**Comment by fornwall** [comment]
@Craeckie Thanks for finding the issue and resolving it! I'll add the information to the app description!
