### ISSUE TITLE
Add permission WRITE_SECURE_SETTINGS and READ_LOGS

### ISSUE THREAD

**Issue by oza6ut0ne** [termux/termux-api#211]
They are needed to use `settings` command and `logcat` command in Termux, respectively.
With `settings` command, we can change many settings without root.

For example, turn on location service by
```settings put secure location_providers_allowed +network,gps```
and turn it off by
```settings put secure location_providers_allowed -network,gps```

And it would be nice if we can read logcat in Termux.

Note that these permissions doesn't work by just adding to AndroidManifest.xml.
We also need to grant them using adb only once.
```
adb shell pm grant com.termux.api android.permission.WRITE_SECURE_SETTINGS
adb shell pm grant com.termux.api android.permission.READ_LOGS
```
Then we will be able to use `settings` and `logcat` in Termux.

**Comment by Grimler91** [comment]
Closing since adding additional permissions that requires running adb won't really benefit the average user. 

The users that want the extra permissions can build the app themselves :+1:

**Comment by jidanni** [comment]
Yes but it wouldn't hurt anybody. Zero. Nobody.
And people wouldn't have to build a whole app just to add one line.

**Comment by xeffyr** [comment]
Bloated code is not accepted here. Termux is standalone application shouldn't rely on adb.

**Comment by jidanni** [comment]
It in no way "rely/depends" on adb. Normal users would never know the difference.

But yes, to make it optionally 10 times more powerful, it does indeed
take that one time boost from adb. And a little one line cooperation
from you.

One cannot just edit your manifest, even with adb.

**Comment by jidanni** [comment]
Take matlog for instance.
- It has that permission listed in its manifest.

It can only read its own logcat entries.
- Not very exciting.
- The permission sitting there in its manifest doesn't do anything...

...Until the user uses **pm grant** once.
- From that day on, it now can read the complete logcat.

**Comment by crisalis2** [comment]
So this was added recently. I'm using Termux 0.103 and Termux:API 0.46 from F-Droid, granted the appropriate permissions through ADB and tried `settings put secure icon_blacklist volume,alarm_clock,rotate,headset`, but I get `cmd: Failure calling service settings: Failed transaction`. What am I missing?

**Comment by xeffyr** [comment]
> What am I missing?

You are missing the fact that `settings` command is restricted since Android 8. Permission is not enough here.

**Comment by crisalis2** [comment]
Makes sense, I'm on Android 10. But I just used an app (https://github.com/zacharee/Tweaker) that could change those same settings just by granting the WRITE_SECURE_SETTINGS permission through ADB.

**Comment by xeffyr** [comment]
@crisalis2 Because it uses Android API for changing settings. Not the utility `/system/bin/settings` which is a restricted system component.

**Comment by crisalis2** [comment]
I see, thanks for explaining.

**Comment by Rudxain** [comment]
@crisalis2 https://github.com/termux/termux-packages/discussions/8292#discussioncomment-5102555

**Comment by mrexperimentalrandom** [comment]
Can you do a device owner Dhizuku type thing with Termux? I've looked all over and nobody has written on this.
