### ISSUE TITLE
Listen to incoming SMS?

### ISSUE THREAD

**Issue by mihojudi** [termux/termux-api#22]
Hello! I would like to implement the following:
When SMS arrives, my computer shows me a notification with it's text and sender.
That's how I see the implementation: using termux, somehow listen to incoming sms, and if sms comes, parse termux-sms-inbox output and pipe it to netcat, on desktop listen to netcat and handle incoming info. Could you please give me a piece of advice on how to listen to incoming sms? Of course, I can run termux-sms-inbox regularly and compare output, but it doesn't seem to be an effective way of doing it. Thanks in advance.

**Comment by Neo-Oli** [comment]
You could use Tasker for this.
1. Make a Script that reads the most recent SMS and does your netcat thing. 
2. Save it in ~/.shortcuts/FILENAME
3. Install [Termux:Widget](https://play.google.com/store/apps/details?id=com.termux.widget), [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) and [AutoShortcut](https://play.google.com/store/apps/details?id=com.joaomgcd.autoshortcut)
4. Setup a new Profile in Tasker. Set it to "Text received.".
5. As Task set AutoShortcut. Then choose "Single Shortcut" (with the Termux Icon) and choose your script.

Now everytime you receive a SMS your Script gets called.

**Comment by mihojudi** [comment]
Thank you very much!

**Comment by Benjamin-Loison** [comment]
Tasker is closed-source as far as I know, I am personally looking for an open-source solution.

**Comment by Neo-Oli** [comment]
> Tasker is closed-source as far as I know, I am personally looking for an open-source solution.

Do you need it in real-time? This is how I do it:
I just have a cronjob that runs every minute that runs a script like this. Basically it runs `termux-sms-list -t inbox` every minute and compares it's output against the last execution to figure out what new SMS arrived. You can run this every minute, or every 5 minutes, or every hour. 

```python
#!/bin/python
import os
import json
from sh import termux_sms_list

folder = os.path.expanduser("~/.local/share/sms")

try:
    os.mkdir(folder)
except FileExistsError:
    pass

raw = termux_sms_list("-t", "inbox")
sms = json.loads(raw)

oldpath = "{}/old".format(folder)
try:
    with open(oldpath, "r") as oldfile:
        oldraw = oldfile.read()
except FileNotFoundError:
    oldraw = "[]"
try:
    oldsms = json.loads(oldraw)
except json.decoder.JSONDecodeError:
    oldsms = []

for cur in oldsms:
    del cur["read"]
for cur in sms:
    del cur["read"]
i = -1

while sms[i] not in oldsms:
    if sms[i]["type"] == "inbox":
        body = sms[i]["body"]
        threadid = str(sms[i]["threadid"])
        number = sms[i]["number"]
        try:
            sender = sms[i]["sender"]
        except KeyError:
            sender = sms[i]["number"]
        print(f"Received SMS from {sender}: {body}")
        # do with it whatever you want here
    i -= 1
    try:
        sms[i]
    except IndexError:
        break

newpath = "{}/old".format(folder)
with open(newpath, "w") as newfile:
    newfile.write(raw)
```

**Comment by Benjamin-Loison** [comment]
> > Tasker is closed-source as far as I know, I am personally looking for an open-source solution.
> 
> Do you need it in real-time? This is how I do it: I just have a cronjob that runs every minute that runs a script like this. Basically it runs `termux-sms-list -t inbox` every minute and compares it's output against the last execution to figure out what new SMS arrived. You can run this every minute, or every 5 minutes, or every hour.
> 
> #!/bin/python
> import os
> import json
> from sh import termux_sms_list
> 
> folder = os.path.expanduser("~/.local/share/sms")
> 
> try:
>     os.mkdir(folder)
> except FileExistsError:
>     pass
> 
> raw = termux_sms_list("-t", "inbox")
> sms = json.loads(raw)
> 
> oldpath = "{}/old".format(folder)
> try:
>     with open(oldpath, "r") as oldfile:
>         oldraw = oldfile.read()
> except FileNotFoundError:
>     oldraw = "[]"
> try:
>     oldsms = json.loads(oldraw)
> except json.decoder.JSONDecodeError:
>     oldsms = []
> 
> for cur in oldsms:
>     del cur["read"]
> for cur in sms:
>     del cur["read"]
> i = -1
> 
> while sms[i] not in oldsms:
>     if sms[i]["type"] == "inbox":
>         body = sms[i]["body"]
>         threadid = str(sms[i]["threadid"])
>         number = sms[i]["number"]
>         try:
>             sender = sms[i]["sender"]
>         except KeyError:
>             sender = sms[i]["number"]
>         print(f"Received SMS from {sender}: {body}")
>         # do with it whatever you want here
>     i -= 1
>     try:
>         sms[i]
>     except IndexError:
>         break
> 
> newpath = "{}/old".format(folder)
> with open(newpath, "w") as newfile:
>     newfile.write(raw)

Yes I am looking for a real-time solution, polling can be heavy especially for a permanent usage even if receive only rarely SMS. Furthermore the one minute frequency can be considered as too long for real-time interaction (both from humans and expiring received codes points of views), while with a `while True; do sleep 30; termux-sms-list; done` can increase the frequency, this would be heavier and heavier.
