### ISSUE TITLE
Mobile Data On/Off

### ISSUE THREAD

**Issue by hexvalid** [termux/termux-api#222]
Hi,
Anyone can append this feature.
Like this: [WifiAPI.java](https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/WifiAPI.java)
I cant use `svc data enable` & `svc data disable` without root. 
Thanks

**Comment by Grimler91** [comment]
There isn't an available api to control mobile data so this feature can't be implemented, see https://stackoverflow.com/questions/31120082/latest-update-on-enabling-and-disabling-mobile-data-programmatically
