### ISSUE TITLE
termux-api not working on OnePlus 6/Android 9

### ISSUE THREAD

**Issue by Wasja7** [termux/termux-api#225]
Since updating my OnePlus 6 to Android 9 none of the termux-api-commands are working anymore. After typing "termux-wifi-connectioninfo" for example nothing happens, I can just cancel it with ctrl-c.

**Comment by Quasic** [comment]
Did you check to see if it still has permissions?

**Comment by Wasja7** [comment]
Unfortunately it doesn't work even with all permissions granted. Some commands like "termux-wifi-connectioninfo" don't even need special permissions, do they?

**Comment by Quasic** [comment]
The clipboard ones and probably others don't need permission, afair, but I have had some commands hang if they use WiFi, location, etc., but it's off or having some trouble.

I think I would next try reinstalling termux-api, the app.

**Comment by Wasja7** [comment]
Reinstalled termux-api, didn't help, then uninstalled the complete termux-app and installed again, now it works. Hopefully it stays this way, don't know why this has happened. Thank you very much for the help!
