### ISSUE TITLE
termux-notification bug

### ISSUE THREAD

**Issue by bokuno** [termux/termux-api#236]
I found that if I run 'termux-notification --title "$(ls)" --content "$(ls)", the "$(ls)" string really be evaled.
So what if it was "$(rm *)"?
I think it would cause secure problem if someone accidently run this.

**Comment by Grimler91** [comment]
There is nothing special about termux-notification. The behaviour you're pointing at is functionality in the shell. 

If the user accidentally runs `rm *` (or `termux-notification --title "$(rm *)"`) then there isn't really much we can do about it, we can't protect the users from themselves..
