### ISSUE TITLE
termux-tts-speak has long delay, can we use a tts server instead?

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-api#24]
If we can start tts server beforehand, the delay could be minimized.

**Comment by fornwall** [comment]
Note that you can do this yourself, by keeping a process alive that reads what to speak and continually feeds it to the tts engine:

```sh
mkfifo ~/.tts
while [ true ]; do cat ~/.tts; done | termux-tts-speak
```

Now you can output speech without delay:

```sh
echo Today is > ~/.tts
date > ~/.tts
```

**Comment by suyashjawale** [comment]
Do i have to write this code in the terminal

**Comment by suyashjawale** [comment]
> Note that you can do this yourself, by keeping a process alive that reads what to speak and continually feeds it to the tts engine:
> 
> ```shell
> mkfifo ~/.tts
> while [ true ]; do cat ~/.tts; done | termux-tts-speak
> ```
> 
> Now you can output speech without delay:
> 
> ```shell
> echo Today is > ~/.tts
> date > ~/.tts
> ```

But where to write this code.....In the terminal or somewhere else

**Comment by aniket16122004** [comment]
How to Do it please tell 
I am new
