### ISSUE TITLE
Sending sms is no longer permitted by google

### ISSUE THREAD

**Issue by geqo** [termux/termux-api#259]
`termux-sms-send` - returned JSON:
`{
  "error": "Sending SMS is no longer permitted by Google"
}`
  
Device: Redmi 5 plus, stock firmware, rooted, all privileges granted to termux and termux-api app.

termux-info: https://pastebin.com/VfsVqc0L

logcat: https://pastebin.com/w7LLwWkJ

**Comment by xeffyr** [comment]
Intended behaviour. Commit: https://github.com/termux/termux-api/commit/de44896a01111506590a258f0267400af067b778

**Comment by geqo** [comment]
Termux is dead now for me :(
Thank you, it was a good time.

**Comment by ethanhs** [comment]
@xeffyr what are your thoughts on the automation exception to the sms restrictions? I believe it may be possible to reinstate the capabilities if it is requested.

**Comment by xeffyr** [comment]
> what are your thoughts on the automation exception to the sms restrictions?

What is "automatic exception to the sms restrictions" ?

Functionality **has to be removed** from application published on google play. We cannot hide it.

I guess google enforces policies in order to prepare developers for Android Q. It will have many restrictions which are enforced at OS level.

**Comment by xeffyr** [comment]
All further discussions about this should be continued in https://github.com/termux/termux-api/issues/257.
