### ISSUE TITLE
/system/bin/am: Permission denied

### ISSUE THREAD

**Issue by sedatsevgili** [termux/termux-api#26]
Hi,

I am using an lg g3 and not any custom rom and i did not rooted my device.
I installed termux-api app and updated and upgraded my apt too. 
However when i want to call any termux api command in the termux terminal, i see this error message:
/data/data/com.termux/files/usr/bin/am: 3: exec: /system/bin/am: Permission denied

**Comment by fornwall** [comment]
Can you paste the output of running:

    ls -la /system/bin/am

Also, could you paste the output of

    echo $PATH

**Comment by sevgilisedat** [comment]
First one is : -rwxr-xr-x 1 root shell 210 Feb 26  2015 /system/bin/am

And the second one is: /data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

**Comment by fornwall** [comment]
What is the output of running

    LD_LIBRARY_PATH= PATH=/system/bin /system/bin/am

**Comment by sevgilisedat** [comment]
-bash: /system/bin/am: /system/bin/sh: bad interpreter: Permission denied

**Comment by fornwall** [comment]
@sevgilisedat  Aha, perhaps the problem is in `/system/bin/sh`! Can you check the output of

    ls -la /system/bin/sh

and try running

    LD_LIBRARY_PATH= /system/bin/sh -c "echo hi"

?

**Comment by sevgilisedat** [comment]
First one is : -rwxr-xr-x 1 root shell 157412 Feb 26  2015 /system/bin/sh

Second one is : hi

**Comment by fornwall** [comment]
Hm, not sure what the problem is here... Could you paste the output from running

    cat /system/bin/am

**Comment by sevgilisedat** [comment]
Sure.

#!/system/bin/sh
#
# Script to start "am" on the device, which has a very rudimentary
# shell.
#
base=/system
export CLASSPATH=$base/framework/am.jar
exec app_process $base/bin com.android.commands.am.Am "$@"

**Comment by saramasood111** [comment]
I have same issue .any luck?
: /system/bin/sh: Permission denied

**Comment by William8915** [comment]
Temporary solution: make a copy of /system/bin/am manually (through adb or other methods), and adjust /data/data/com.termux/usr/bin/am accordingly.

Tested on LG G3 Stylus (D690)

**Comment by sedatsevgili** [comment]
@William8915 how should i relate /system/bin/am and /data/data/com.termux/files/usr/bin/am ? I just could not get it. Can you be more specific please? I really want to use this api.

**Comment by PosaLusa24** [comment]
Try changing selinux mode to permissive. It worked for me.

**Comment by sedatsevgili** [comment]
@PosaLusa24 Thanks, i will try asap

**Comment by sedatsevgili-optimum** [comment]
Issue still lives. I think i have to change my phone to use this api :( 
Btw, i don't want to root.

**Comment by sedatsevgili** [comment]
Issue is still alive. I think i have to change my device to use the api :(
Btw, i don't want to root.

**Comment by sedatsevgili** [comment]
Well, i changed my device. And it works right now :)

**Comment by rootkittt** [comment]
Hi, ive got any problems to run “su“.
Ive tried it with “tsu“ and i cannot use “su“

My phone is rooted by chainfire super su.

But i always get this error. How can i fix it?


su
bash: /data/data/com.termux/files/usr/bin/su: /data/data/com.termux/files/usr/bin/sh: bad interpreter: Permission denied
# ls -la /system/bin/am
bash: /data/data/com.termux/files/usr/bin/applets/ls: Permission denied
# echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
# exit
exit
$ ls -la /system/bin/am
-rwxr-xr-x    1 root     shell          207 Mar 11 17:13 /system/bin/am
$ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
$ LD_LIBRARY_PATH= PATH=/system/bin /system/bin/am
cmd: Failure calling service activity: Failed transaction (2147483646)
$ ls -la /system/bin/sh
-rwxr-xr-x    1 root     shell       298856 Mar 11 17:14 /system/bin/sh
$ cat /system/bin/am
#!/system/bin/sh

if [ "$1" != "instrument" ] ; then
    cmd activity "$@"
else
    base=/system
    export CLASSPATH=$base/framework/am.jar
    exec app_process $base/bin com.android.commands.am.Am "$@"
fi
$

Thanks

**Comment by fearfai** [comment]
I am having problem with this 

bash: /data/data/com.termux/files/usr/bin/python2: Permission denied
