### ISSUE TITLE
`termux-fingerprint` not working on Android 9

### ISSUE THREAD

**Issue by filisko** [termux/termux-api#261]
**Problem description**
termux-fingerprint does not trigger when I touch the fingerprint sensor. I allowed termux-api fingerprint permissions and all that, my device increases it's 'fingerprint allowed permission counter' every time I execute termux-fingerprint. I think the issue is very similar to #228 

**Steps to reproduce**
Execute termux-fingerprint

**Expected behavior**
Return a JSON.

**Additional information**
Termux apk version: 0.67
Termux-api apk version: 0.32

**termux-info:**
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 4.9.151-perf-gdcea99f43677 #1 SMP PREEMPT Wed Mar 6 16:07:51 AWST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
Mi 8

**logcat termux-api**:
04-18 14:16:50.134 14295 14295 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10144 <<<<<<
04-18 14:16:50.135 14295 14295 W app_process: type=1400 audit(0.0:17577): avc: denied { read } for name="event-log-tags" dev="tmpfs" ino=16179 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:runtime_event_log_tags_file:s0 tclass=file permissive=0
04-18 14:16:50.215 14295 14295 D AndroidRuntime: Calling main entry com.example.termuxam.Am
04-18 14:16:50.234 14060 14060 E termux-api: Error in TermuxApiReceiver
04-18 14:16:50.234 14060 14060 E termux-api: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
04-18 14:16:50.234 14060 14060 E termux-api: 	at com.termux.api.FingerprintAPI.onReceive(FingerprintAPI.java:80)
04-18 14:16:50.234 14060 14060 E termux-api: 	at com.termux.api.TermuxApiReceiver.doWork(TermuxApiReceiver.java:82)
04-18 14:16:50.234 14060 14060 E termux-api: 	at com.termux.api.TermuxApiReceiver.onReceive(TermuxApiReceiver.java:20)
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:3417)
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.app.ActivityThread.access$1200(ActivityThread.java:200)
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.os.Looper.loop(Looper.java:193)
04-18 14:16:50.234 14060 14060 E termux-api: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
04-18 14:16:50.234 14060 14060 E termux-api: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 14:16:50.234 14060 14060 E termux-api: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-18 14:16:50.234 14060 14060 E termux-api: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-18 14:16:50.238 14295 14295 D AndroidRuntime: Shutting down VM

**Comment by seffparker** [comment]
Mine has the same issue. Android 9, Xiaomi POCO F1.

Permission Manager showing "Fingerprint was allowed few seconds ago", but the command is not returning any output. I have to hit Ctrl+C to leave the command.

**Comment by filisko** [comment]
Great!
