### ISSUE TITLE
ssh-agent via OpenKeychain

### ISSUE THREAD

**Issue by 532910** [termux/termux-api#262]
Please make ssh agent to use OpenKeychain.

Like [termbot](https://github.com/open-keychain/termbot) does.

gnupg-agent issue: #230

**Comment by DDoSolitary** [comment]
I just created a new project which provides support for using OpenKeychain as an SSH agent. Please [test it](DDoSolitary/OkcAgent#1) and feel free to report bugs or feature requests. Also, I'd suggest close this issue as the project is not part of `termux-api`.

**Comment by 532910** [comment]
The link is invalid, update it please.

**Comment by DDoSolitary** [comment]
@532910 Updated.

**Comment by 532910** [comment]
https://github.com/DDoSolitary/OkcAgent

**Comment by 532910** [comment]
OkcAgent looks abandoned and works bad.

**Comment by 532910** [comment]
OkcAgent is fully usable
