### ISSUE TITLE
termux-notification: Show timestamp

### ISSUE THREAD

**Issue by seffparker** [termux/termux-api#265]
**Problem description**
By default, all standard notifications on Android has a timestamp so we get to know when was the notification popped up. But, termux-notification is not showing a timestamp. 

Its annoying when we push notifications via cron, without a timestamp.

**Steps to reproduce**
Try termux-notification command with required options.

**Expected behavior**
Show timestamp for notifications.

**Additional information**
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 4.9.112-perf-gf165f5d #1 SMP PREEMPT Wed Apr 3 16:46:50 WIB 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
POCO F1

**Comment by xeffyr** [comment]
> Its annoying when we push notifications via cron, without a timestamp.

* Why it has to show timestamp by default ?

* It it difficult to add timestamp to notification's message ?

Finally, Termux:API is just an interface to Android API and should be generic as possible.

**Comment by seffparker** [comment]
Yes, currently I'm pushing timestamp using `date` command in contents. But, Android notification has a predefined space for timestamp, like Title and Content. So, why we are not relying on that feature?

You are saying like, "why you should use title, you can add title in content as TITLE IS THIS"

I'm not asking Termux:API should show timestamp by default. But, if there is an option to show timestamp (not is contents) it would be great.

**Comment by MatthewScholefield** [comment]
Here's an example:

![example](https://images2.imgbox.com/6b/79/9bozSfDf_o.jpg)

**Comment by seffparker** [comment]
Thanks for the commit.

**Comment by xalexalex** [comment]
Hey, my pleasure. It'll be in the next release :smile:
