### ISSUE TITLE
termux-battery-status hangs on Android 9

### ISSUE THREAD

**Issue by gurumark** [termux/termux-api#267]
**Problem description**
termux-camera-info
termux-battery-status
hangs without any errors. I haven't check the others.
********************
$ termux-info
Updatable packages:
ncurses/stable 6.1.20181117-5 aarch64 [upgradable from: 6.1.20181117-4]
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.9.97 #1 SMP PREEMPT Thu Apr 11 17:38:07 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
HUAWEI
Device model:
BLA-A09
************************
**Steps to reproduce**
$ termux-battery-status
^Z
[4]+  Stopped                 termux-battery-status

**Expected behavior**
It should return the value.

**Additional information**
$ logcat -s termux:* termux-api:*
--------- beginning of system
--------- beginning of main

**Comment by Grimler91** [comment]
Do you have the termux-api **app** installed?

**Comment by gurumark** [comment]
Sorry. Yes. that did work. Thanks.

**Comment by Vigneshrajanking** [comment]
In my device same problem what can I do but my device is mi a3
