### ISSUE TITLE
termux-notification: stdin contents empty

### ISSUE THREAD

**Issue by seffparker** [termux/termux-api#271]
**Problem description**
![Screenshot_2019-06-06-11-44-29-546_com termux](https://user-images.githubusercontent.com/21334939/59011005-e14a1280-8850-11e9-866b-ff3686f4c0db.png)

The notification contents are empty when given as stdin. Works well if specified as --content

**Steps to reproduce**
echo test | termux-notification

**Additional information**
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux batmobile 4.9.112-perf-gf165f5d #1 SMP PREEMPT Wed Apr 3 16:46:50 WIB 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
Xiaomi
Device model:
POCO F1

**Comment by Oj18** [comment]
Getting this problem as well.

**Comment by Oj18** [comment]
This issue is with the API package and not the API itself I'm pretty sure. I feel it may be an unwanted problem when I fixed some things a while ago in the script for termux-notification.

**Comment by Oj18** [comment]
See: https://github.com/termux/termux-api-package/commit/816b358e064f382ae4d71399f67785af1021b226

I think I might of accidentally disabled stdin when fixing a different problem.

I'll try to get a fix and get a maintainer to accept it.

**Comment by fornwall** [comment]
Thanks for reporting! Fixed in version 0.44 of the termux-api package.
