### ISSUE TITLE
termux-clipboard-get termux-clipboard-set not working on Android Q

### ISSUE THREAD

**Issue by KevCui** [termux/termux-api#273]
**Problem description**
**termux-clipboard-get** and **termux-clipboard-set** are not working on Android Q beta 5. Terminal is hanging when executing these 2 commands.

**Comment by Grimler91** [comment]
Does other termux-api commands work?
What does `logcat` say when you execute them?
And, just to make sure, you have installed the [termux-api app](https://play.google.com/store/apps/details?id=com.termux.api), right?

**Comment by xeffyr** [comment]
Isn't related to missing environment variable ANDROID_TZDATA_ROOT ?
In such case it should be fixed by https://github.com/termux/termux-app/commit/7d42b07a321f9409dd25445c974c6c12309ebbd6 which will be available in next app release.

**Comment by Grimler91** [comment]
> should be fixed by termux/termux-app@7d42b07 which will be available in next app release.

Ah, I thought that was released already

**Comment by KevCui** [comment]
clipboard APIs work in the latest release 0.73 :+1:
