### ISSUE TITLE
Failed  to update due to package writing more data than expected

### ISSUE THREAD

**Issue by berto12** [termux/termux-api#28]
The issue being that I'm trying to update and will not go all the way through due to an error "http://termux.net stable/main i686 Packages Writing more data than expected (186946 > 186906)". I have tried to uninstall and reinstall, but no luck. Any help would helpful :).
![screenshot_2016-07-21-08-57-59 1](https://cloud.githubusercontent.com/assets/20580172/17025442/8309467a-4f21-11e6-9353-8facb4086723.jpg)

**Comment by Neo-Oli** [comment]
Can you try again please? It could be a http caching issue. 
If it still doesn't work, can you try running `apt clean` and trying again?
Similar issues can usually be fixed with this. https://plus.google.com/u/0/105320182048381120888/posts/g65gS69p27j

**Comment by berto12** [comment]
YES!!! It worked, sorry about that lol. :)
