### ISSUE TITLE
termux commands not responding

### ISSUE THREAD

**Issue by DerekCL** [termux/termux-api#29]
Hello

I installed the termux application, installed the API from the app store, updated the app on the phone, installed the termux api inside the termux app. I cannot get any of the functions to run except for the -help function. When I try running the application I have the application that just sits there and does nothing.

Android version: 5.0
Phone: asus zenfone 2

What should I try doing to get the functions to work.

**Comment by kenzietandun** [comment]
Had the same issue for me. Marshmallow upgrade fixed it.

**Comment by Neo-Oli** [comment]
https://github.com/termux/termux-api/issues/21 seems to be the same Problem. Please subscribe to that issue.
