### ISSUE TITLE
/system/bin/sh: Permission denied

### ISSUE THREAD

**Issue by saramasood111** [termux/termux-api#30]
I am using s5 version 5.0 , i am using rooted cell .when i try to execute make . Its saying permission denied.
make: execvp: /system/bin/sh: Permission denied

**Comment by fornwall** [comment]
Are you running as root inside Termux or running as the normal Termux user?

What is the output of running `ls -la /system/bin/sh`?

Can you past the output from `echo $PATH`?

**Comment by saramasood111** [comment]
-rwxrwxrwt    1 root     shell       157408 Aug  1  2008 /system/bin/sh

**Comment by saramasood111** [comment]
Following result of echo path
echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

**Comment by fornwall** [comment]
Can you try running

    /system/bin/sh -c "echo hi"

and see what the output is?

**Comment by saramasood111** [comment]
system/bin/sh -c "echo hi"                                   <
hi

**Comment by rgh36167** [comment]
Does your Makefile have DOS line endings? Try dos2unix on a copy of the file..

**Comment by saramasood111** [comment]
Can u explain dos2unix . I am newbe

**Comment by rgh36167** [comment]
I assume you have a Makefile that you are trying to "run"?
 `cp Makefile Makefile.orig`
 `dos2unix Makefile`

**Comment by keith-dev** [comment]
Please remember that GNU Make has a SHELL variabke that you can use to set the shell used within make.

**Comment by WeirdlyLazy** [comment]
Hi sorry I know this has been closed but I am facing the same issue and I am not sure what I need to do, please someone help?

**Comment by Malayaliann** [comment]
> Hi sorry I know this has been closed but I am facing the same issue and I am not sure what I need to do, please someone help?
> 
Yeah me too
