### ISSUE TITLE
termux-notification - call arbitrary termux commands?

### ISSUE THREAD

**Issue by rgh36167** [termux/termux-api#31]
is there any way to execute commands when tapping a selection?

**Comment by fornwall** [comment]
This is now possible using the `--action` option, as in

    termux-notification --title 'Start sshd' --action 'sshd'

Run `logcat -s 'termux-task:*'` to see the log of background jobs if you are trying to execute something more advanced in the `--action` and need to debug.

**Comment by rgh36167** [comment]
I am now on termux-api 0.13, termux 0.46 from f-droid but it says `illegal option --` when I use `--action`.

Apparently even `--title` triggers this error, is there some special build option that needs to be enabled so this would work?

**Comment by Neo-Oli** [comment]
@rgh36167 Did you update your packages recently? Try running `apt update && apt upgrade`

**Comment by rgh36167** [comment]
thanks, apparently that did the trick.

Next in the wishlist - would it possible to make this work even when the phone is locked? Should I open a separate issue?

 http://stackoverflow.com/questions/33724567/how-to-perform-notification-action-click-on-lock-screen
