### ISSUE TITLE
Add USSD calling support to termux-telephony-call

### ISSUE THREAD

**Issue by Xosrov** [termux/termux-api#312]
**Feature description**
Due to restrictions to Android itself, dialing USSD numbers is not possible as the '#' is not encoded properly. Adding this feature would open a whole world of possibilities, and a lot of automation that comes with gathering info with it.

**Background information**
You could start by manually encoding the '#' in the number, but there would also have to be a way to read the output from the dial, as well as sending follow-up numbers based on the result. (If you don't know what i mean dial something like *1# on your phone)
Check [this link](https://stackoverflow.com/questions/10214915/dial-ussd-code) as a place to start.
Thanks for your time

**Comment by agnostic-apollo** [comment]
Fixed by 2d7672c
