### ISSUE TITLE
JobScheduler: Support persistent jobs

### ISSUE THREAD

**Issue by pimsierhuis** [termux/termux-api#316]
**Feature description**
As far as I can see, jobs scheduled with termux-job-scheduler aren't persistent, which means they cease to exist after device reboot. This makes them very much less useful. My use case for this feature is that I want to run a backup-script on my phone to secure my photo's using rsync. 

**Background information**
Implementation of this feature seems quite simple, as there is a "persisted" property in the JobInfo.Builder-class. The only caveat I can see is that the app would need the RECEIVE_BOOT_COMPLETED permission.

**Comment by xeffyr** [comment]
Why not to use Termux:Boot to setup job scheduler ?

**Comment by pimsierhuis** [comment]
That's an alternative I thought about, but I think it's unnecessary complex compared to the simple "persistent" flag and I don't need Termux:Boot now. Furthermore I want to  minimize the things I need to do on the phones as I need to do multiple phones.

**Comment by xeffyr** [comment]
Termux:API is the only bridge between Termux command line and some Android API functionality. It is not a standalone app unlike Termux:Boot.

**Comment by pimsierhuis** [comment]
I don't understand what you mean. I'm proposing to (besides the wrapper script) extend Termux:API with said persisted-flag (JobSchedulerAPI.java).

**Comment by xeffyr** [comment]
You are proposing to add duplicate functionality, i.e. to include on-boot trigger into one of the Termux:API commands while we already have Termux:Boot for that purpose.

**Comment by pimsierhuis** [comment]
I'm definitely not proposing for the termux-side to maintain an internal database and act on the boot-trigger from android to set up scheduled tasks. As far as I understand, the Android-API has a persisted-flag to provide cross-boot-persistency functionality. See: https://developer.android.com/reference/android/app/job/JobInfo.Builder.html#setPersisted(boolean).

I agree with you that for on-boot functionality we have Termux:Boot, but I think what I propose is just providing a more complete view of the Android API to the user.

**Comment by kcubeterm** [comment]
@pimsierhuis agree with you.

**Comment by pimsierhuis** [comment]
Cool. Shall I try to put a PR together?

**Comment by xeffyr** [comment]
>Shall I try to put a PR together?

Yes, you can.

Change to https://github.com/termux/termux-api-package/blob/master/scripts/termux-job-scheduler will be needed too in order to add cli option.

**Comment by xalexalex** [comment]
The idea looks good to me!
I can take care of the termux-api-package part, it's going to be just a few lines of code.

**Comment by pimsierhuis** [comment]
@xalexalex: Thanks, but I already had a modified termux-job-scheduler for testing :)

**Comment by xalexalex** [comment]
Tested and can confirm that it works perfectly (job is still present after
rebooting).

**Comment by skygate2012** [comment]
Hi, sometimes the persisted jobs would be gone after 3-5 reboots. What could be causing this?
