### ISSUE TITLE
termux-notification - multiline text content

### ISSUE THREAD

**Issue by rgh36167** [termux/termux-api#32]
Tried the obvious, "\n"  but doesn't work?

**Comment by fornwall** [comment]
This is now possible by piping into `termux-notification` - try e.g.

    ls $PREFIX | termux-notification --title 'Some folders'

Be sure to have the latest version of the `termux-api` package (run `apt update && apt upgrade`) and the Termux:API app.

**Comment by rgh36167** [comment]
thanks, it works.

Line wrapping is a bit of a problem, is there a way to know how many chars fit on a line?

**Comment by fornwall** [comment]
@rgh36167 I don't think so, unfortunately (except trial and error on a specific device).
