### ISSUE TITLE
Request: comma escape sequence for termux-dialog widgets

### ISSUE THREAD

**Issue by sudomain** [termux/termux-api#331]
**Feature description**

Certain widgets (checkbox, radio, sheet, and spinner) of the `termux-dialog` command support the -v option, which is 'comma delim values to use' for the given widget. It would be great if there was a way to include a literal comma in the values. Something like a `\,` or  `\U002C` could be used.

I'm using the sheet widget to create a basic file manager and commas are technically allowed in file names (not that I recommend it). Another idea of mine involves using termux-dialog with large integers, which I would prefer to express with commas. For these reasons, having an escape sequence to use commas with the -v option would be great
**Reference implementation**

Have you checked if the feature is accessible through the Android API? 
N/A
Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)
N/A

**Comment by xalexalex** [comment]
Not able to test right now, but answering for the sake of speed.
If I recall correctly, you *can* include a literal comma by escaping it, with `'\,'` or `"\\,"` (i.e. single backslash in single quotes, double backslash in double quotes).
Please let me know if this works :smiley:

**Comment by sudomain** [comment]
Thank you for the quick response :). I tried what you said, but no luck:

$ termux-dialog sheet -v "item1 (no comma), item2 (comma '\,' here)"
{
  "code": -2,
  "text": ""
}
$ termux-dialog sheet -v "item1 (no comma), item2 (comma '\\,' here)"
{
  "code": -2,
  "text": ""
}
$ termux-dialog sheet -v 'item1 (no comma), item2 (comma "\\," here)'
{
  "code": -2,
  "text": ""
}
$ termux-dialog sheet -v 'item1 (no comma), item2 (comma "\," here)'
{
  "code": -2,
  "text": ""
}



Example 1 and 3 are what you suggested. I also tried double backslash inside of single quotes(2), as well as single backslash inside of double quotes (4)

**Comment by xalexalex** [comment]
Sorry, I should've been more clear. You need not put more quotes inside quotes.

Try these:

`$ termux-dialog sheet -v "item1 (no comma), item2 (comma \\, here)"`

or, equivalently

`$ termux-dialog sheet -v 'item1 (no comma), item2 (comma \\, here)'`

**Comment by sudomain** [comment]
Sorry for the trouble. This was fixed in https://github.com/termux/termux-api/commit/00eeb0948a9c722a45930817144716f64c735601
about amonth ago. I had to update the app. Thanks
