### ISSUE TITLE
an id that is specified with `termux-notification --id` shows up as the "tag" field of termux-notification-show

### ISSUE THREAD

**Issue by sudomain** [termux/termux-api#339]
**Problem description**

A notification created with `termux-notification` can have an id specified using the `--id` option. When notifications are listed using `termux-notification-list`, this id shows up in the "tag" field, not the "id" field.

**Steps to reproduce**

1. `termux-notification -c mycontent --id myid`
2. `termux-notification-list`

"myid" shows up in the tag field:

    "id": 0,
    "tag": "myid",
    "key": "0|com.termux.api|0|myid|10161",
    "group": "",
    "packageName": "com.termux.api",
    "title": "",
    "content": "mycontent"
  }

It appears that all of the notifications created with termux-api have an id of 0?

**Expected behavior**

The id specified in `termux-notification --id` should show up as the id for a notification in `termux-notification-list`

I guess it's not a huge problem since I'll just end up `grep`-ing the output of `termux-notification-list` for the tag field rather than the id field, but this was the cause of a bug in something I'm making using termux:api

**Additional information**

* Termux application version: 0.92
* Android OS version: 7.0
* Device model: LGL84VL

**Comment by xalexalex** [comment]
Hey, thanks for spotting and reporting this!

I guess this is a semantic problem.

What termux-notification calls `id` is technically the notification `tag`.
See [1](https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/NotificationAPI.java#L88) and [2](https://developer.android.com/reference/android/app/NotificationManager#notify(java.lang.String,%20int,%20android.app.Notification)).

I agree that this seems counterintuitive, but fixing this would break backwards compatibility without a good reason to do so (in my opinion). I'll close as wontfix unless someone else disagrees with me.

**Comment by savagemegan** [comment]
we gat issues with posting resolve..
