### ISSUE TITLE
termux-notification-list return empty string as content with multiline notification

### ISSUE THREAD

**Issue by sangowen** [termux/termux-api#341]
**Problem description**

(Probably related to #274 but this issue is about ```termux-notification-list```.)
The multiline notification can be successfully created by ```termux-notification```. However, listing the notification with ```termux-notification-list``` returns "" as its content.

![Screenshot_20200324-173305872](https://user-images.githubusercontent.com/6276605/77413730-c609bd00-6dfa-11ea-980a-86c3bb6c9c3b.jpg)
![Screenshot_20200324-173403709](https://user-images.githubusercontent.com/6276605/77413901-1a14a180-6dfb-11ea-9624-aab6c4a2f631.jpg)

**Steps to reproduce**

```
ls $PREFIX | termux-notification --title 'Some folders'
termux-notification-list
```
**Expected behavior**

content with the original message (the result of ```ls $PREFIX```)

**Additional information**

* Termux application version: 0.92
* Termux:API application version: 0.41
* termux-api package version: 0.50
* Android OS version: 10
* Device model: Zenfone 6

**Comment by xalexalex** [comment]
Nice catch! I can reproduce it on v0.41, however it is fixed on master (by 43dec9b13ac99b9f0bebd7e29be5b2a2ad2bc53d) so it should be fixed in termux:api v0.42 (which will be available in a few days on google play and f-droid).
Closing; please reopen if I'm wrong!
