### ISSUE TITLE
Add drawable library and command-line option for smallIcon to `termux-notification`

### ISSUE THREAD

**Issue by yurimataev** [termux/termux-api#343]
**Feature description**

It would be nice to have the option to change the smallIcon (icon that shows up in the status bar) of notifications using a command-line argument passed to `termux-notification`. 

**Reference implementation**

Have you checked if the feature is accessible through the Android API?

Yes, `setSmallIcon` is a standard method for the Notification builder.

Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)

Automate and Tasker, as well as I'm sure other automation apps, provide this kind of functionality. 

This would not be a difficult feature to implement. `setSmallIcon` is a standard method for the Notification builder. The library of drawables embedded in the app would have to be expanded, for example with the [Google material design icons](https://github.com/google/material-design-icons). If the devs here are OK with this feature, I would be happy to give implementing this a shot.

**Comment by xalexalex** [comment]
Hey,
that sounds like a good idea. Feel free to go ahead and draft it.

**Comment by yurimataev** [comment]
Hi Alex,
I have added the feature discussed here to `termux-notification`. `termux-notification --icon <icon-name>` will set the status bar icon to the name icon. `termux-notification --icon-list` shows the list of icons.

For this I made changes to two repos, termux-api and termux-api-package:
https://github.com/yurimataev/termux-api/tree/343-notification-set-icon
https://github.com/yurimataev/termux-api-package/tree/343-notification-set-icon

It builds without errors and I've tested in Android Emulator and it is working as expected. Are there any other kind of tests you would like me to do before I submit a pull request?

**Comment by yurimataev** [comment]
Hi Alex,
I have added the feature discussed here to `termux-notification`. `termux-notification --icon <icon-name>` will set the status bar icon to the name icon. `termux-notification --icon-list` shows the list of available icons.

It builds without errors and I've tested in Android Emulator and it is working as expected, so I have gone ahead and created pull requests.

Looking forward to your review!

**Comment by xalexalex** [comment]
Hey,
first, thanks for the great job! I'll go ahead and review it as soon as possible (no later than Sunday).
At first I thought that there could be an increase in apk size, but looking at the xml files now I doubt so.
P.S. are there any licensing issues that we should be aware of, regarding this particular icon pack?

Thanks again! :smile:

**Comment by yurimataev** [comment]
I used the [Google Material Design icons](https://github.com/google/material-design-icons). They are open-source under the Apache license, so there shouldn't be any issues
