### ISSUE TITLE
termux-notification button action invoked as different user

### ISSUE THREAD

**Issue by seffparker** [termux/termux-api#347]
**Problem description**
The button actions in termux-notification are run as different user than the command termux-notification is invoked.

**Steps to reproduce**
1. Run termux-notification as root user
2. Set button1-action to "id > /sdcard/debug.log"
3. Push the notification
4. Tap button1 on the notification shade
5. The file debug.log contain a different user ID, than the root user which invoked the termux-notification command.

**Expected behavior**
The button actions should be run as the command invoked user.

**Additional information**

* Termux application version: 0.94
* Termux API version: 0.43
* Android OS version: 9 Pie
* Device model: Xiaomi POCO F1

**Comment by xeffyr** [comment]
You should do privilege escalation inside action command.

Termux:API is executed by Android framework VM (its Android application) and it won't allow and is not able anyway to be executed as root.

This is not a bug but Android OS behaviour.

**Comment by xeffyr** [comment]
`tsudo id > /sdcard/debug.log`

**Comment by seffparker** [comment]
Thanks. Fixed the issue using privilege escalation as per your recommendation.
Ref: https://github.com/seffparker/android-scripts/blob/master/sdcard/lab/android/bin/audio-sleep
