### ISSUE TITLE
termux-speech-to-text crashes the API

### ISSUE THREAD

**Issue by sudomain** [termux/termux-api#351]
**Problem description**

![Screenshot_2020-05-27-13-26-24](https://user-images.githubusercontent.com/30786326/83052945-ff8abe80-a01d-11ea-8167-87198ae7a3c2.png)
Termux:API crashes on the second run of termux-speech-to-text (after it's granted the microphone permission)
**Steps to reproduce**

1. `termux-speech-to-text`
2. Granted the microphone permission
3. `termux-speech-to-text` again
4. Crash
**Expected behavior**

No crash

**Additional information**

$ termux-info
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g606096e-dirty #1 SMP PREEMPT Tue Jan 17 18:10:20 KST 2017 armv7l Android
Device manufacturer:
LGE
Device model:
LGL84VL

* Termux application version: 0.94 (FDroid)
* Android OS version:7.0
* Device model:LGL84VL

**Comment by xeffyr** [comment]
Output of `logcat` is needed.

Also: do you have *Google Play* and *Google Voice Search* installed ?

**Comment by sudomain** [comment]
I no longer have this issue
