### ISSUE TITLE
pm/cmd is broken in Android 10

### ISSUE THREAD

**Issue by joshcangit** [termux/termux-api#354]
**Problem description**

The `pm` command doesn't work.

**Steps to reproduce**

```
$ pm
cmd: Failure calling service package: Failed transaction (2147483646)
```

**Additional information**

- Packages CPU architecture:
aarch64
- Android version:
10
- Kernel build information:
Linux localhost 4.14.113-18242812 #&#8203;1 SMP PREEMPT Fri Mar 20 18:30:04 KST 2020 aarch64 Android
- Device manufacturer:
samsung
- Device model:
SM-G973F

**Comment by 5c0tt1** [comment]
@joshcangit 
The `pm` command has been deprecated in newer versions of Android in favour of `cmd`.
Example: `pm install` is now `cmd package install`.

**Comment by joshcangit** [comment]
> @joshcangit
> The `pm` command has been deprecated in newer versions of Android in favour of `cmd`.
> Example: `pm install` is now `cmd package install`.
> Please close this issue.

I'm not sure if this is fixed because the `pm` command is still there and the `cmd` command is not there yet.

**Comment by Grimler91** [comment]
@joshcangit run `/system/bin/cmd` instead of just `cmd` until we've added a wrapper

**Comment by joshcangit** [comment]
> @joshcangit run `/system/bin/cmd` instead of just `cmd` until we've added a wrapper, or just use `pm package install`, seems pm is already a symlink to cmd on your device

Still getting the same error after testing it.

```
$ /system/bin/cmd package path com.android.chrome
cmd: Failure calling service package: Failed transaction (2147483646)
```

**Comment by xeffyr** [comment]
https://github.com/termux/termux-app/issues/1616#issuecomment-652382813

**Comment by joshcangit** [comment]
> As I wrote, you should create a _request for similar functionality_ not filing a bug report for /system/bin/pm or /system/bin/cmd.
> 
> These utilities are not managed by Termux, instead they are part of Android OS and we simply can't fix them. These utilities are intended to be used only with ADB for debugging purposes and their usage may get disabled for non-privileged shells.
> 
> What we can do is only to create an API for getting info about installed applications, nothing more.

I see, in that case, I'll wait until you fix that API for getting information about installed applications. Either by using the same name, `pm`, or replacing it with `cmd` or some other name.

**Comment by 5c0tt1** [comment]
@joshcangit  If its app info you want... Use `aapt`.

**Comment by xeffyr** [comment]
> Also still seeing the same error message again.

You seeing it because it was not fixed. Everything what was done is just a new script was added to termux-tools.
```
~ $ cat $PREFIX/bin/cmd
#!/data/data/com.termux/files/usr/bin/sh
unset LD_LIBRARY_PATH LD_PRELOAD
PATH=$PATH:/system/bin exec /system/bin/cmd "$@"
```

**Comment by xeffyr** [comment]
Upcoming Android 11 introduced a [package visibility](https://developer.android.com/preview/privacy/package-visibility) which restricts the access to the list of installed applications.

That means no workarounds will be possible for non-root users if Android OS version >=11. For Android <=9.0 this is not needed  and `pm list` should work. Implementing API for Android 10 only is kinda pointless.

**Comment by amsitlab** [comment]
![Screenshot_20200908-161337](https://user-images.githubusercontent.com/10000281/92457403-6196ba80-f1ee-11ea-85ee-9d00b8f0dbdb.png)
@xeffyr still error

**Comment by twaik** [comment]
What if we just add `QUERY_ALL_PACKAGES` to AndroidManifest.xml of `termux-app`? Anyway Termux is not being updated in Google Play.

**Comment by agnostic-apollo** [comment]
>What if we just add QUERY_ALL_PACKAGES to AndroidManifest.xml of termux-app?

That is planned to be added but issue is not related to it. The error is from some binder selinux denial since like Android 8 or something. I haven't been able to figure out which exactly since its not logged, may need to compile android to figure it out since android source is not being helpful to me.

**Comment by Rudxain** [comment]
Is it possible to define a wrapper function that runs `pm` in a subshell?

I've tried this
```bash
function pm() {
    printf '%s' "$(pm "$@" 2>&1 < /dev/null)"
}
```
But it doesn't work

**Comment by Acnfv12** [comment]
cmd: Failure calling service package: Failed transaction (2147483646)

**Comment by agnostic-apollo** [comment]
`termux-tools` now provides its own implementation of `cmd` that does have the error.

**Comment by u0a316** [comment]
@agnostic-apollo how did you solve this problem? did the same trick with me?
