### ISSUE TITLE
File

### ISSUE THREAD

**Issue by guozhenduo** [termux/termux-api#357]
How do I save the returned data to a file?

**Comment by kcubeterm** [comment]
redirect your output , something like this 
YOUR_COOMAND >> file.txt

Example:
`echo 'Lol that's  not a big deal' >> file.txt`

Now when you open file.txt. you will got results
```shell
$ cat file.txt
Lol that's not a big deal




```

**Comment by guozhenduo** [comment]
Thank you.

在 2020-07-24 14:17:20，"Krishna Kanhaiya" <notifications@github.com> 写道：


redirect your output , something like this
YOUR_COOMAND >> file.txt

Example:
echo 'Lol that's not a big deal' >> file.txt

Now when you open file.txt. you will got results

$ cat file.txt
Lol that's not a big deal
