### ISSUE TITLE
How to get the data of the termux-dialog

### ISSUE THREAD

**Issue by phamt8611** [termux/termux-api#370]
I am wanting to use the python programming language to get the data in the termux-dialog.
More specifically, it is code and text
![Screenshot_20200924-025350_Termux](https://user-images.githubusercontent.com/29194008/94062765-4d1f0880-fe11-11ea-9c33-0f3a035211cf.jpg)

**Comment by xeffyr** [comment]
From standard output. Moreover, you shouldn't use `os.system`. Use `subprocess` module instead. https://docs.python.org/3/library/subprocess.html
