### ISSUE TITLE
How To Get Json Data Of Termux-API Using Python?

### ISSUE THREAD

**Issue by phamt8611** [termux/termux-api#371]
Hi everyone, I am having a problem on how to get the json data of the API.

For example termux-dialog, how do I want to get the text of the text in python?

**Comment by AbdullahM0hamed** [comment]
```
>>> import json
>>> import subprocess
>>> data=json.loads(subprocess.getoutput("termux-dialog"))
>>> data
{'code': -1, 'text': 'test'}
```

**Comment by xeffyr** [comment]
Duplicate. See answer in https://github.com/termux/termux-api/issues/370#issuecomment-697955868 and example [in comment above](https://github.com/termux/termux-api/issues/371#issuecomment-699557809).

Read the Python documentation next time, e.g. https://docs.python.org/3/library/subprocess.html.
