### ISSUE TITLE
Close issues related to removed commands/features

### ISSUE THREAD

**Issue by AbdullahM0hamed** [termux/termux-api#374]
Since all sms commands in termux api have now been gone for a good while:

https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/SmsInboxAPI.java#L16-L18

https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/SmsSendAPI.java#L14-L16 

The following issues pertaining to them should be closed as they likely won't ever be resolved unless something like what's suggested in #257 is done:

#71
#148
#102
#108
#72
#96
#141
#118

**Comment by xeffyr** [comment]
Closed now.
