### ISSUE TITLE
How do i sign the app properly?

### ISSUE THREAD

**Issue by Fexiven** [termux/termux-api#379]
**Problem description**
I just built the app but i cant install it because i have to sign it, so i tried to sign it with my own keystore but if i try to install it via adb i get the following error:
Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Reconciliation failed...: Reconcile failed: Package com.termux.api has no signatures that match those in shared user com.termux; ignoring!]

* Termux application version: newest version
* Android OS version: 10
* Device model: Google Pixel

**Comment by xeffyr** [comment]
> so i tried to sign it with my own keystore

Sign all add-ons you wish to install with this keystore as well. And don't forget to uninstall the original app and add-ons before installing custom builds.
