### ISSUE TITLE
Can't send SMS (no android.permission.READ_PHONE_STATE)

### ISSUE THREAD

**Issue by gatosyperros** [termux/termux-api#387]
**Problem description**
I can't seem to send sms, the API does show the inbox, list calls, and call, but the sms never seem to work.
It's clear that it's a permission issue according to the logcat:
"Neither user 10224 nor current process has android.permission.READ_PHONE_STATE"
But I'm also getting:
`com.termux.api.util.-$$Lambda$ResultReturner$oCU8JqHW5HLMrNZa40ThjAWcwzo.run(Unknown Source:8)`
I've recently downloaded fdroid, installed termux from fdroid, and got the api from fdroid...
Am I doing something wrong? do I need root?

I've included a screenshot of log cat output right after I do termux-sms-send -n number "testing":
![Screenshot_20201129_211429](https://user-images.githubusercontent.com/5193147/100552528-083ba600-3288-11eb-85d5-96c5aaa544bc.png)

**Additional info**
here are the permissions
![Screenshot_20201129-211715](https://user-images.githubusercontent.com/5193147/100552617-aa5b8e00-3288-11eb-903f-3dc6f78358ed.png)

**Steps to reproduce**
termux-sms-send -n [a number that I have access to] "testing"

**Expected behavior**
send the sms and receive "testing"

**Additional information**
Termux api:0.45
Termux application version:0.103
Android OS version:8.0.0
Device model:CAT S41

I found out just recently that you added back sms support after having used an outdated version that only gave me "sms read" support, but alas I can not send sms :(

**Comment by xeffyr** [comment]
Problem is that permission is already declared. See https://github.com/termux/termux-api/blob/master/app/src/main/AndroidManifest.xml#L22
```
    <uses-permission android:name="android.permission.READ_PHONE_STATE" />
```

**Comment by xeffyr** [comment]
Can't reproduce the issue.

Try to reboot device.

**Comment by gatosyperros** [comment]
I rebooted and cleared the app cache partition and I was getting the same problem,
so I figured I'd check what other apps might have the sms function ability and I guess toggling it on and off fixed it because now it works! so yeah idk what it was, because I did a "fresh" install, and even rebooted... who cares at least it's working, thanks for the update now I'm going to have some fun! :+1:
