### ISSUE TITLE
Clipboard commands hang

### ISSUE THREAD

**Issue by Marcel-Robitaille** [termux/termux-api#39]
When I pipe text into `termux-clipboard-set` or run `termux-clipboard-get`,  the command just hangs. To get my prompt back, I have to use ctrl-c.

**Comment by fornwall** [comment]
Have you installed the Termux:API app?

**Comment by Marcel-Robitaille** [comment]
I thought I just had to install it in the app with `apt install termux-api`. Now that I have the api app, it works as expected. There should be an error message instead of just hanging the command though.

Thanks for the answer.

**Comment by thiagowfx** [comment]
I had the same issue. I would recommend to add a post-installation message to the termux-api package, advising the user to install the Termux:API app.

**Comment by buckett** [comment]
I've also just had the same issue of the clipboard co mmand just hanging.

**Comment by s243a** [comment]
> Have you installed the Termux:API app?

The Termux:API ap is no longer available on the google play store :(

It looks like it's available on F-droid but doesn't show up when I search for it on using the F-droid ap on myu phone .
