### ISSUE TITLE
bash: /data/data/com.termux/files/usr/bin/applets/ls: Permission denied

### ISSUE THREAD

**Issue by sahad1234black** [termux/termux-api#396]
$ tsu
# ls
bash: /data/data/com.termux/files/usr/bin/applets/ls: Permission denied
#

**Comment by sahad1234black** [comment]
my device is is rooted 
but showing this why

**Comment by xeffyr** [comment]
Something wrong with your root or kernel. That's not a Termux issue.

**Comment by sahad1234black** [comment]
any way to solve that

**Comment by sahad1234black** [comment]
![Screenshot_2021-01-15-17-08-24](https://user-images.githubusercontent.com/71170303/104722750-3a18a700-5726-11eb-973c-9f3ebde30268.png)

**Comment by Grimler91** [comment]
Try `tsu -a`, but most likely something is wrong with the rooting method you used, and then you would have to re-do that

**Comment by sahad1234black** [comment]
i tryed magsik
and super su

always showing this

**Comment by Grimler91** [comment]
Something wrong with your kernel/rom then, not a termux issue anyways

**Comment by xeffyr** [comment]
@sahad1234black Check out your device thread on [XDA](https://forum.xda-developers.com/) for custom kernels and try a one.

**Comment by sahad1234black** [comment]
i dont undrestand what i do

**Comment by Kilo-411** [comment]
remove tsu -y
you shouldn't need it. But it appears your files maybe alter or not mounted right. Make sure where pwd is located 
Should have the termux file as root when using root.
