### ISSUE TITLE
Can't get notifications

### ISSUE THREAD

**Issue by sergeyfilippov1** [termux/termux-api#398]
I can't get notifications using termux-api

**Additional information**

* Termux application version: 0.103
* Android OS version: Android 10 aarch64
* Device model: xiaomi Redmi Note 8
![IMG_20210123_235507](https://user-images.githubusercontent.com/48158038/105613883-73ac7a80-5dd6-11eb-965a-3bee24ef6543.jpg)
![IMG_20210123_235456](https://user-images.githubusercontent.com/48158038/105613884-75763e00-5dd6-11eb-9159-34fde3d8a04f.jpg)

**Comment by xeffyr** [comment]
Is Termux:API application installed?

**Comment by sergeyfilippov1** [comment]
yes

**Comment by sergeyfilippov1** [comment]
> Is Termux:API application installed?
> 
> Package `termux-api` is useless without it.

Yes

**Comment by sergeyfilippov1** [comment]
> Is Termux:API application installed?
yes

**Comment by sergeyfilippov1** [comment]
> Is Termux:API application installed?
yes

**Comment by sergeyfilippov1** [comment]
> Is Termux:API application installed?

yes

**Comment by krystean** [comment]
You have to re-enable Notification access for Termux:API in Settings whenever it does not get your notifications. We have the same device and I find that Termux:API loses access to notifications after a few days even though Notification access is not turned off.

**Comment by sergeyfilippov1** [comment]
ok i will try it

**Comment by sergeyfilippov1** [comment]
> You have to re-enable Notification access for Termux:API in Settings whenever it does not get your notifications. We have the same device and I find that Termux:API loses access to notifications after a day or two even though Notification access is not turned off.

I changed the resolution and any command stopped working 
![IMG_20210130_070607](https://user-images.githubusercontent.com/48158038/106346658-af10e280-62c9-11eb-9fa8-3628a79c6b7e.jpg)

**Comment by sergeyfilippov1** [comment]
> You have to re-enable Notification access for Termux:API in Settings whenever it does not get your notifications. We have the same device and I find that Termux:API loses access to notifications after a day or two even though Notification access is not turned off.

Nothing changed

**Comment by sergeyfilippov1** [comment]
thanks, it worked
