### ISSUE TITLE
Feature request: remove item from clipboard

### ISSUE THREAD

**Issue by Marcel-Robitaille** [termux/termux-api#40]
I would like to see an option on `termux-clipboard-set` or a new command that allows you to remove items from the clipboard. For example, when copying a password from pass, I want the password to be deleted from the clipboard after a certain amount of time.

**Comment by Neo-Oli** [comment]
Can't you just call `termux-clipboard-set ""`, which empties the clipboard?

And by the way, pass has been patched to work with the termux-clipboard commands
`pass -c Github` will copy the password to the clipboard instead of displaying it. The clipboard contents get reset after 45 seconds to whatever it was before running `pass`

**Comment by Marcel-Robitaille** [comment]
The problem with the first option (and from the sounds of it this applies to the second too) is that I have a clipboard manager that keeps clipboard history.

**Comment by Neo-Oli** [comment]
Then there's nothing that can be done. The android clipboard only ever contains one item. These clipboard managers just periodically check for new entries and record it. There can be no such command unless your specific clipboard manager has an API for this. Which one do you have? Did it come pre-installed om your device?

**Comment by Marcel-Robitaille** [comment]
I figured this might be the case. So if I uninstall the app, to clear the clipboard I just need to run `termux-clipboard-set ""`?

**Comment by Neo-Oli** [comment]
Yes

**Comment by sixtyfive** [comment]
Google brought me here while trying to find out why `pass -c` won't work under Termux on my device. It just hangs/waits (?) forever until interrupted via Ctrl-c. Is there anything that needs to be done to make it work besides `apt update && apt upgrade && apt install termux-api pass`?

**Comment by Iambecomeroot** [comment]
I think pass uses xsel to handle clipboard. I don't know if there's a workaround.

**Comment by Neo-Oli** [comment]
@sixtyfive You probably forgot to install [Termux:Api](https://play.google.com/store/apps/details?id=com.termux.api). You need both the App from the Play Store(or F-Droid if you have Termux from F-Droid) and the termux-api package from apt (that you already have now). `pass` has definitely been patched to work with the API

**Comment by sixtyfive** [comment]
That did it, thank you Oliver! :)
