### ISSUE TITLE
termux-media-player not working

### ISSUE THREAD

**Issue by dit7ya** [termux/termux-api#405]
**Problem description**

`termux-media-player` cannot detect any currently playing tracks. Tried with Spotify, VLC, AntennaPod, and NewPipe.

**Steps to reproduce**

1. Play a song in a media player app.
2. `termux-media-player info`

**Expected behavior**

Should return the currently playing track. Instead returns 'No tracks playing'.

**Additional information**

* Termux application version: latest F-droid
* Android OS version:11

**Comment by xeffyr** [comment]
`termux-media-player` works only with player embedded into Termux:API.
