### ISSUE TITLE
APIs not updated for a year in Google Play Store

### ISSUE THREAD

**Issue by xzj8b3** [termux/termux-api#408]
In Google Play Store API are not updated since 2020 and also the developer email should be updated.

I tried to connect Shodan but is not possible because API does not work.... I just needed it for a quick test of one of our blogs to see vulnerability!

I hope this can be solved soon because various tools even from mobile devices can be very convenient for quick tests without necessarily access to the notebook as I had to do.

Translated with www.DeepL.com/Translator (free version)

**Comment by Grimler91** [comment]
Since beginning of this year it is no longer possible to upload newer app version to google play. Termux needs to be updated to be compatible with android api level 29 for that to be possible. See https://wiki.termux.com/wiki/Termux_Google_Play

It is recommended to install all apps from F-droid instead. You need to uninstall termux-app and all addons to be able to install from F-droid. This is described in https://wiki.termux.com/wiki/Termux:API.

**Comment by xzj8b3** [comment]
> Dalla fine dello scorso anno non è più possibile caricare la versione più recente dell'app su Google Play. Termux deve essere aggiornato per essere compatibile con Android api livello 29 affinché ciò sia possibile. Vedi https://wiki.termux.com/wiki/Termux_Google_Play
> 
> Si consiglia invece di installare tutte le app da F-droid. È necessario disinstallare l'app termux e tutti i componenti aggiuntivi per poter installare da F-droid. Questo è descritto in https://wiki.termux.com/wiki/Termux:API .

I reinstalled everything from Fdroid but just a waste of time ... API doesn't work, Shodan can't connect

**Comment by xzj8b3** [comment]
> Dalla fine dello scorso anno non è più possibile caricare la versione più recente dell'app su Google Play. Termux deve essere aggiornato per essere compatibile con Android api livello 29 affinché ciò sia possibile. Vedi https://wiki.termux.com/wiki/Termux_Google_Play
> 
> Si consiglia invece di installare tutte le app da F-droid. È necessario disinstallare l'app termux e tutti i componenti aggiuntivi per poter installare da F-droid. Questo è descritto in https://wiki.termux.com/wiki/Termux:API .

![Screenshot_2021-04-13-00-08-52-462_com termux](https://user-images.githubusercontent.com/26720956/114468948-8ae85080-9bec-11eb-984a-94afe65ca707.jpg)
just reinstalled from Fdroid

**Comment by xeffyr** [comment]
Nothing to do with Termux:API add-on. Termux is not affiliated with Shodan, neither vice-versa.

Your problem is invalid API key. You should log in to your account, copy the provided API key and paste it on command line.
