### ISSUE TITLE
How to edit notifications quitely

### ISSUE THREAD

**Issue by sudo-do** [termux/termux-api#424]
how to edit a notification quietly .-. 

https://youtu.be/Ok8ro9sLWWw

i use os.system() in python to send notification,
```
os.system('termux-notification --content "'+str(x)+'" -i 5')
```

i dont want to go dnd to suppress sound

**Comment by dannywritescode** [comment]
From the [wiki](https://wiki.termux.com/wiki/Termux-notification), it seems like the `--alert-once` option solves exactly this!
