### ISSUE TITLE
removing USB Permission pop-up when asking for device authorization

### ISSUE THREAD

**Issue by artynet** [termux/termux-api#432]
Hello folks,

I need to suppress the pop-up window when asking the system authorization for an Usb device with:

`termux-usb -r <device>`

is this short patch enough to fulfill my need ? take a look at it:

```patch
--- a/app/src/main/java/com/termux/api/UsbAPI.java
+++ b/app/src/main/java/com/termux/api/UsbAPI.java
@@ -44,8 +44,8 @@ public class UsbAPI {
                     device = getDevice(apiReceiver, context, intent);
                     if (device == null) return;
                     ResultReturner.returnData(apiReceiver, intent, out -> {
-                        boolean result = getPermission(device, context, intent);
-                        out.append(result ? "yes\n" : "no\n");
+                        // boolean result = getPermission(device, context, intent);
+                        out.append("yes\n");
                     });
                     break;
                 case "open":
```

in the end I should be able to  drop the pop-up and getting always an yes as answer. Of course I need to rebuild the APK after the applied patch...

          Kind Regards

**Comment by xeffyr** [comment]
Carefully read what this code does and you will understand that your patch just disables permission dialog, while faking the permission status.

You just won't be able to use the USB device without, if not asking permission.
