### ISSUE TITLE
App not installed

### ISSUE THREAD

**Issue by CriviCiro** [termux/termux-api#433]
Hello folks,

I need to build custom Termux:API app, but when i try to install the application i have this error message: "App not installed".

Could the issue be this ```android:sharedUserId="com.termux"```?

Because the ```android:sharedUserId``` in termux-app is equal to ```android:sharedUserId``` in termux-api

**Additional information**

* Termux application version: 0.117
* Termux:API application version: 0.48
* Android OS version: ^9.0
* Device model: Lenovo

**Comment by agnostic-apollo** [comment]
You also need to build termux-app and all plugins yourself or use debug builds if you haven't changed the APK signing key.

https://github.com/termux/termux-app#installation
