### ISSUE TITLE
Functions of Termux API in C++

### ISSUE THREAD

**Issue by Dolfost** [termux/termux-api#436]
About a week ago I had the idea to transfer the functions of Termux API in the function of the C++ library and call them through the system(). But here I thought, don't you have Termux API functions in the form of C ++ library?

**Comment by SDRausty** [comment]
> the functions of Termux API in the function of the C++ library and call them through the system(). 

You might be able to do this in C with loksh:
[    pkg install unstable-repo
    pkg install loksh](https://github.com/termux/termux-packages/issues/1341)

**Comment by Dolfost** [comment]
> > the functions of Termux API in the function of the C++ library and call them through the system().
> 
> You might be able to do this in C with loksh:
> [ pkg install unstable-repo pkg install loksh](https://github.com/termux/termux-packages/issues/1341)

Thanks!

**Comment by SDRausty** [comment]
You are welcome; This repository https://github.com/ksh-community/ksh builds in [TermuxArch](https://github.com/TermuxArch/TermuxArch):
```
ksh --version                                                         
version         sh (AT&T Research) 93u+ 2012-08-01
```
It builds as intended, and seems to function as expected in Termux PRoot:
![Screenshot_20210808-084246](https://user-images.githubusercontent.com/27742457/128632358-228fc759-96b7-41ea-9dff-acfe0db4b89f.png)

I just checked this last night.  Hopefully a Termux package will soon be made for `ksh`.

**Comment by Dolfost** [comment]
> You are welcome; This repository https://github.com/ksh-community/ksh builds in [TermuxArch](https://github.com/TermuxArch/TermuxArch):
> 
> ```
> ksh --version                                                         
> version         sh (AT&T Research) 93u+ 2012-08-01
> ```
> 
> It builds as intended, and seems to function as expected in Termux PRoot:
> ![Screenshot_20210808-084246](https://user-images.githubusercontent.com/27742457/128632358-228fc759-96b7-41ea-9dff-acfe0db4b89f.png)
> 
> I just checked this last night. Hopefully a Termux package will soon be made for [`ksh`](https://github.com/ksh-community/ksh).

Hi. I just asked about the library for C ++, not about .... Oh ... I don't know, I don't understand what it is. Sorry, can you explain me how this works, what it is, and if possible, how it can be used as a Termux API in the Clang (C++) Code? Sorry again... I don't understand what's going on...

**Comment by xeffyr** [comment]
@SDRausty `ksh` and `loksh` shells have nothing to do with what OP has asked about. Please read the issue carefully.

**Comment by agnostic-apollo** [comment]
Check [`termux-api.c`](https://github.com/termux/termux-api-package/blob/master/termux-api.c)

**Comment by Dolfost** [comment]
> Check [`termux-api.c`](https://github.com/termux/termux-api-package/blob/master/termux-api.c)

Yaay! Exactly what i need! Thanks!

**Comment by SDRausty** [comment]
Thank you for inspiring [`makeksh`](https://github.com/TermuxArch/TermuxArch/commit/b6fe2f65a29bc846bdaf47dab97e5e3df7b3421e) with this issue;  Which is a fairly easy way to install `ksh` in Termux PRoot.

> Sorry, can you explain me how this works, what it is, and if possible, how it can be used as a Termux API in the Clang (C++) Code? 

`what is korn shell`

`what is cshell`

> `ksh` and `loksh` shells have nothing to do with what OP has asked about. Please read the issue carefully.

I just now realised my mistake in interpreting this issue; In my original reply, "You might be able to do this in C with `loksh`," I had mistakenly thought korn shell is cshell.  Sorry about the mixup, and thank you for your suggestion.

I would have recommended `tcsh` instead of `ksh` in my original reply.  Hopefully `tsch` will come in handy for this topic as well.

> Check [`termux-api.c`](https://github.com/termux/termux-api-package/blob/master/termux-api.c)

Thank you for sharing the link.
