### ISSUE TITLE
Detecting Device Orientation

### ISSUE THREAD

**Issue by AbdullahBinJahed** [termux/termux-api#444]
Is there any way to run scripts accordingly to orientation ?
Let's say I'm using the fish shell and I want to run greeting1.sh if the device in vertical when opening Termux or greeting2.sh if the device is in horizontal ... any way to do it ?

**Comment by Grimler91** [comment]
`stty size` tells you the number of columns and rows. If number of columns is larger than rows then you are probably in landscape mode

**Comment by AbdullahBinJahed** [comment]
> `stty size` tells you the number of columns and rows. If number of columns is larger than rows then you are probably in landscape mode

Thank you very much for your reply 💖

**Comment by AbdullahBinJahed** [comment]
> > `stty size` tells you the number of columns and rows. If number of columns is larger than rows then you are probably in landscape mode
> 
> Thank you very much for your reply

also is there any way to change the column and row number (basically font size i guess) from script/command line ?

**Comment by Grimler91** [comment]
> also is there any way to change the column and row number (basically font size i guess) from script/command line ?

No, not at the moment
