### ISSUE TITLE
Notifications from termux-notification don't play any sound, even with --sound

### ISSUE THREAD

**Issue by shrihanDev** [termux/termux-api#445]
**Problem description**

I have a problem which is exactly opposite to #319. All notifications spawned by `termux-notification` are grouped under "Silent Notifications" on API 30, so they don't play any sound. The `--sound` option doesn't do anything, either. The workaround that I've found is to open the notification settings and change the notification type from Silent to Alerting / Default.

**Steps to reproduce**

Run `termux-notification --sound -c "Some content"`. The notification doesn't show in the heads up nor does it make any sound. Pull down the notification shade and the notification is present in the Silent Notifications section.

**Expected behavior**

The notification should play a sound and show up in the heads up, and should be grouped under "Alerting notifications" instead of "Silent Notifications".

**Additional information**

* Termux application version: v0.117
* Android OS version: 11 (API 30) (Using HavocOS as custom ROM)
* Device model: j7elte (Samsung Galaxy J7 2015, SM-J700F) (shouldn't be applicable tho)

**Comment by shrihanDev** [comment]
Bump.

Are the issues here even considered?

**Comment by shrihanDev** [comment]
Bump

**Comment by tareksander** [comment]
I tried it on my Android 10 Fairphone 2 and it also didn't make a sound.  
For me it was that the standard system notification sound is just no sound, I had to go into the notification settings and pick another sound and it worked.

**Comment by shrihanDev** [comment]
I know right? Unfortunately it seems `termux-api` devs are on a holiday or something.

**Comment by shrihanDev** [comment]
Bump?

**Comment by tareksander** [comment]
Support for custom notification channels is merged and will be available in the next release. Then you can create a new notification channel, set it to make a sound in the Android options and use it in the `termux-notification` commands.
