### ISSUE TITLE
easier way to get device model name through shell in termux

### ISSUE THREAD

**Issue by cnst** [termux/termux-api#448]
It appears that the only way to get the device model name in termux shell may be through `termux-info`, however, the output is not very scriptable, plus it includes a lot of info about installed and upgradeable packages, so, presumably it's very expensive to generate (and it does take several seconds to return, longer than most other termux-api utilities), plus it also seems to copy stuff into the clipboard, which is unexpected when you run the shell scripts, and kind of annoying as well.

There should be an easier way to do this.  Surprisingly, this information is not part of `uname -a` on Android -- not even the codename for the device, even though these kernels are supposedly mostly device-specific.

There should be something similar to `sysctl -n hw.{vendor,product,version}` on OpenBSD, although I realise the sysctl entries might be coming from upstream and aren't available for addition to sysctl on termux' side.  Should there be a new command line utility, or maybe just an extra option to `termux-info` to suppress the package info and/or to only output manufacturer and model names?

```
% time termux-info | tail -4
Device manufacturer:
Google
Device model:
Pixel 2 XL
termux-info  1.30s user 0.65s system 50% cpu 3.837 total
tail -4  0.01s user 0.01s system 0% cpu 3.836 total
```

**Comment by agnostic-apollo** [comment]
`/system/bin/getprop ro.product.model`

**Comment by cnst** [comment]
> `/system/bin/getprop ro.product.model`

So awesome, thank you!

`getprop` by itself returns a whole bunch of other properties as well (although it doesn't accept multiple parameters to get more than one property in a single invocation).

```
% getprop | fgrep ro.product | tail -3
[ro.product.manufacturer]: [Google]
[ro.product.model]: [Pixel 2 XL]
[ro.product.name]: [taimen]
```

**Comment by SDRausty** [comment]
> Other properties exist too defined by Build.java.

Thank you very much about https://cs.android.com/android/platform/superproject/+/master:frameworks/base/core/java/android/os/Build.java and `getprop` information @agnostic-apollo 🎵 🎶 

`java api`; https://docs.oracle.com/javase/7/docs/api/

`android api` results are not as eloquent as https://docs.oracle.com/javase/7/docs/api/; 
 Would you have a similar link that documents what we are attempting to create?

**Comment by agnostic-apollo** [comment]
You are both welcome.

>getprop by itself returns a whole bunch of other properties as well

I know, it was left as an exercise for the reader ;)

>although it doesn't accept multiple parameters to get more than one property in a single invocation

Java `properties` files (like `termux.properties`) support multiline values as well, so some universal splitter would be required.

The android docs exist at https://developer.android.com/reference/android/os/Build and https://developer.android.com/reference/java/lang/System#getProperty(java.lang.String,%20java.lang.String). The `termux-app` internally gets the properties with multiple ways in java here https://github.com/termux/termux-app/blob/v0.117/termux-shared/src/main/java/com/termux/shared/termux/AndroidUtils.java
