### ISSUE TITLE
Drop down menu multiple termux notification  and list id of existing notification

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-api#459]
Feature description

What i am trying to implement is:
A persistent grouped notification that has drop down menu and when clicked on down arrow it will list multiple notifications which when clicked executes pass manager and copies password.

eg. group notification --> drop down ---> notification 1) github notification 2) google notification 3) yahoo
when i click drop down it will list three more notification and when i click github it will execute pass -c github.com to copy password.

How can i implement below:  Help needed:
```
Also when i click notification and it execute  
pass -c command   
it should pop up some dialog box where we  
 can write gpg passphrase and it wil 
supply that to pass   
command to decrypt and copy password
```

DISCLAIMER: 
```
Currently i am implenting it with buttons but i cannot add more than 3 buttons.
when i use --button4; it says unrecognized option button4
```

Also how can i list the id of existing notification

I created a persistant notification with --ongoing option providing some id. I cleared my history. Now i dont remember id of that notification. And termux-notification-remove is asking for id

Reference implementation

Have you checked if the feature is accessible through the Android API?
Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)

**Comment by agnostic-apollo** [comment]
>I created a persistant notification with --ongoing option providing some id. I cleared my history. Now i dont remember id of that notification. And termux-notification-remove is asking for id

Force stop Termux:API from app info in android settings.

**Comment by tathastu871** [comment]
> > I created a persistant notification with --ongoing option providing some id. I cleared my history. Now i dont remember id of that notification. And termux-notification-remove is asking for id
> 
> Force stop Termux:API from app info in android settings.

Yes that an option but if termux notification has some option to list ids of currently active termux notification we can remove it without force stop

**Comment by agnostic-apollo** [comment]
Max 3 buttons are allowed by android and `termux-notification`.

https://developer.android.com/reference/android/app/Notification.Builder.html#addAction(android.app.Notification.Action)

https://wiki.termux.com/wiki/Termux-notification

Pass `--help` to commands to get info, like `termux-notification --help`.

**Comment by agnostic-apollo** [comment]
>Yes that an option but if termux notification has some option to list ids of currently active termux notification we can remove it without force stop

Use tag field of `termux-notification-list`.

https://github.com/termux/termux-api/issues/339

**Comment by tathastu871** [comment]
What actually --group does? Tried --group option to solve above mentioned problem of multiple notification if buttons are limited to 3. But not working. no proper documentation

**Comment by agnostic-apollo** [comment]
https://developer.android.com/training/notify-user/group

**Comment by tathastu871** [comment]
How can i implement below: Help needed:

Also when i click notification and it execute  
pass -c command   
it should pop up some dialog box where we  
 can write gpg passphrase and it wil 
supply that to pass   
command to decrypt and copy password

**Comment by tathastu871** [comment]
Please if possible answer above before closing it

**Comment by tathastu871** [comment]
Please if possible answer above before closing it

**Comment by agnostic-apollo** [comment]
The wiki lists all the commands. Try to search first before asking questions.

https://wiki.termux.com/wiki/Termux:API

The `termux-dialog` command should work.

**Comment by tathastu871** [comment]
> The wiki lists all the commands. Try to search first before asking questions.
> 
> https://wiki.termux.com/wiki/Termux:API
> 
> The `termux-dialog` command should work.

I know that but pass manager ask for gpg passphrase interactively how can i supply passphrase to pass managar from inputted text on termux-dialog

**Comment by agnostic-apollo** [comment]
Something like following should work.

`--passphrase-file "/path/to/file" --batch --yes --pinentry-mode loopback`

`--passphrase "I don't know how to google search" --batch --yes --pinentry-mode loopback`
