### ISSUE TITLE
Create and make $TERMUX_API_VERSION accessible through termux console

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-api#463]
**Feature description**

**Reference implementation**

Have you checked if the feature is accessible through the Android API?

Unknown

Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)

**Comment by agnostic-apollo** [comment]
Already implemented in termux/termux-app@0cf3cef7 and will be available in `termux-app` `v0.118`.
