### ISSUE TITLE
termux-share can't share images from stdin

### ISSUE THREAD

**Issue by TheRawMeatball** [termux/termux-api#468]
**Problem description**
`termux-share` should be able to share images fed in from stdin, but currently running it simply exits with no message or share dialog.

**Steps to reproduce**
```
cat image.png | termux-share -c image/png
```

**Expected behavior**
The share dialog pops up

**Additional information**

* Termux application version:0.117
* Android OS version:Android 10 (LineageOS 17)
* Device model:Xiaomi Mi 8

**Comment by tareksander** [comment]
I ran that command and looked at the log output:  
There is an Android error saying the transaction is too large.  
Have you tried a smaller file? The limit is ~2MB.  
On Android you are not supposed to pass large amounts of data directly to other apps, apps should create a file and share that instead. You should do the same.

**Comment by TheRawMeatball** [comment]
Ah, that makes sense, thanks :) I'll close this issue for now but this limit should probably be documented on termux-share.
