### ISSUE TITLE
Termux USB - Didnt response error

### ISSUE THREAD

**Issue by EndorfinTR** [termux/termux-api#478]
I put my usb to OTG cable and i write consol this, "termux-usb -l" and i waiting for 30 minutes. 
**Additional information**

* Termux application version: 0.101
* Android OS version: 10
* Device model: ETab 20

**Comment by Grimler91** [comment]
Do you have the termux-api app installed?

**Comment by Grimler91** [comment]
Note also that termux-app v0.101 is very old. Install the latest from f-droid instead, see https://github.com/termux/termux-app#Installation

**Comment by EndorfinTR** [comment]
> Note also that termux-app v0.101 is very old. Install the latest from f-droid instead, see https://github.com/termux/termux-app#Installation

I try to download newer version but my android said "The application could not be installed"

**Comment by EndorfinTR** [comment]
> > Note also that termux-app v0.101 is very old. Install the latest from f-droid instead, see https://github.com/termux/termux-app#Installation
> 
> I try to download newer version but my android said "The application could not be installed"

I try those versions, 0.117, 0.116, 0.115.

**Comment by EndorfinTR** [comment]
> Do you have the termux-api app installed?

Yes, i install.

**Comment by EndorfinTR** [comment]
> > > Note also that termux-app v0.101 is very old. Install the latest from f-droid instead, see https://github.com/termux/termux-app#Installation
> > 
> > 
> > I try to download newer version but my android said "The application could not be installed"
> 
> I try those versions, 0.117, 0.116, 0.115.

Ok, i download but still dont responsing

**Comment by Grimler91** [comment]
> I try to download newer version but my android said "The application could not be installed"

You need to uninstall termux-app, and all other add-on apps, from google play before you can install from f-droid



> > Do you have the termux-api app installed?
> 
> Yes, i installed.

What version of the termux-api app do you have installed?

**Comment by EndorfinTR** [comment]
> > I try to download newer version but my android said "The application could not be installed"
> 
> You need to uninstall termux-app, and all other add-on apps, from google play before you can install from f-droid
> 
> > > Do you have the termux-api app installed?
> > 
> > 
> > Yes, i installed.
> 
> What version of the termux-api app do you have installed?

0.49

**Comment by Grimler91** [comment]
> 0.49

The newest [termux-api app version on google play is 0.44](https://play.google.com/store/apps/details?id=com.termux.api), so you cannot have 0.49 if you have installed termux from google play. You need to install both the termux-api package, and the termux-api app

**Comment by EndorfinTR** [comment]
> > 0.49
> 
> The newest [termux-api app version on google play is 0.44](https://play.google.com/store/apps/details?id=com.termux.api), so you cannot have 0.49 if you have installed termux from google play. You need to install both the termux-api package, and the termux-api app
https://f-droid.org/tr/packages/com.termux.api/ i saw in here

**Comment by Grimler91** [comment]
So you have installed the termux-app and termux-api apps from f-droid now and am still having issues with termux-usb? Share your output of `termux-info` in that case, and capture a logcat over adb of when termux-usb hangs

**Comment by EndorfinTR** [comment]
> So you have installed the termux-app and termux-api apps from f-droid now and am still having issues with termux-usb? Share your output of `termux-info` in that case, and capture a logcat over adb of when termux-usb hangs

Termux Info Output,
```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
apt/stable 2.3.13-3 aarch64 [upgradable from: 2.3.6]
bash/stable 5.1.12-2 aarch64 [upgradable from: 5.1.8]
ca-certificates/stable 1:2021-10-26-0 all [upgradable from: 20210525]
command-not-found/stable 1.70 aarch64 [upgradable from: 1.62]
coreutils/stable 9.0 aarch64 [upgradable from: 8.32-7]
curl/stable 7.80.0 aarch64 [upgradable from: 7.77.0-3]
dash/stable 0.5.11.5 aarch64 [upgradable from: 0.5.11.3]
debianutils/stable 5.5 aarch64 [upgradable from: 4.11.2]
dialog/stable 1.3-20211214-0 aarch64 [upgradable from: 1.3-20210530-0]
diffutils/stable 3.8 aarch64 [upgradable from: 3.7-3]
dpkg/stable 1.21.1 aarch64 [upgradable from: 1.20.9-5]
ed/stable 1.17-4 aarch64 [upgradable from: 1.17]
gawk/stable 5.1.1 aarch64 [upgradable from: 5.1.0-1]
gpgv/stable 2.3.3-2 aarch64 [upgradable from: 2.3.1-1]
grep/stable 3.7-2 aarch64 [upgradable from: 3.6]
gzip/stable 1.11-3 aarch64 [upgradable from: 1.10-4]
inetutils/stable 1.9.4-12 aarch64 [upgradable from: 1.9.4-11]
less/stable 590 aarch64 [upgradable from: 563]
libandroid-support/stable 28-2 aarch64 [upgradable from: 28]
libc++/stable 23b-3 aarch64 [upgradable from: 21d-1]
libcurl/stable 7.80.0 aarch64 [upgradable from: 7.77.0-3]
libgcrypt/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
libgnutls/stable 3.6.16-1 aarch64 [upgradable from: 3.6.15-3]
libgpg-error/stable 1.43 aarch64 [upgradable from: 1.42]
libidn2/stable 2.3.2 aarch64 [upgradable from: 2.3.0-2]
libnettle/stable 3.7.3 aarch64 [upgradable from: 3.7.2]
libnghttp2/stable 1.46.0 aarch64 [upgradable from: 1.43.0]
libssh2/stable 1.10.0 aarch64 [upgradable from: 1.9.0-2]
libtirpc/stable 1.3.2 aarch64 [upgradable from: 1.3.1]
lsof/stable 4.94.0-1 aarch64 [upgradable from: 4.94.0]
nano/stable 6.0 aarch64 [upgradable from: 5.7]
openssl/stable 1.1.1l aarch64 [upgradable from: 1.1.1k-2]
pcre/stable 8.45 aarch64 [upgradable from: 8.44-1]
sed/stable 4.8-2 aarch64 [upgradable from: 4.8-1]
termux-keyring/stable 2.4 all [upgradable from: 1.9]
termux-tools/stable 0.154 all [upgradable from: 0.130]
util-linux/stable 2.37.2-1 aarch64 [upgradable from: 2.37]
xxhash/stable 0.8.1 aarch64 [upgradable from: 0.8.0-1]
Android version:
10
Kernel build information:
Linux localhost 4.14.133 #1 SMP PREEMPT Wed Aug 18 15:47:15 CST 2021 aarch64 Android
Device manufacturer:
General Mobile
Device model:
e-tab 20
```
 
With logcat,
Logcat output is very long to send, sorry.
