### ISSUE TITLE
termux-camera-info raises error message on kindle fireos

### ISSUE THREAD

**Issue by italomaia** [termux/termux-api#48]
Calling termux-camera-info in my kindle 8" fireos raises the following error message:

`CANNOT LINK EXECUTABLE DEPENDENCIES: "libandroid_runtime.so" is 64-bit instead of 32-bit.` 

Suggestions?

**Comment by Grimler91** [comment]
Is this still a problem? 
Might have been solved by https://github.com/termux/termux-app/issues/192 I presume. 
(Closing for now)
