### ISSUE TITLE
Commands don't work with sudo

### ISSUE THREAD

**Issue by TBM13** [termux/termux-api#481]
**Problem description**
termux-api commands don't work with sudo.
Example:
`termux-vibrate` works fine.
`sudo termux-vibrate` does nothing, it's stuck forever.

**Steps to reproduce**
Open Termux and execute `sudo <termux-api command>`.

**Expected behavior**
`sudo <termux-api command>` should execute the command normally.

**Additional information**

* Termux application version: 0.117 - Termux API 0.50
* Android OS version: AOSP 12.0 v400.d GSI by phhusson
* Device model: Galaxy A20 (SM-A205G)

**Comment by agnostic-apollo** [comment]
https://github.com/termux/termux-api/issues/402#issuecomment-904799297
