### ISSUE TITLE
How can I choose second SIM slot when sending SMS

### ISSUE THREAD

**Issue by byteshiva** [termux/termux-api#482]
How can I choose second SIM slot when sending SMS?

I see by default it picks up the first SIM slot when sending SMS

`termux-sms-send`

**Comment by Grimler91** [comment]
Use the -s option: 

```
$ termux-sms-send -help
Usage: termux-sms-send -n number[,number2,number3,...] [-s slot] [text]
Send a SMS message to the specified recipient number(s). The text to send is either supplied as arguments or read from stdin if no arguments are given.
  -n number(s)  recipient number(s) - separate multiple numbers by commas
  -s slot       sim slot to use - silently fails if slot number is invalid or if missing READ_PHONE_STATE permission
```

**Comment by byteshiva** [comment]
Thanks, it worked!

```
termux-sms-send -n <senderPhoneNumber> -s 0 "Hello World!"
```

Ex.
```
termux-sms-send -n +11771111111 -s 0 "Hello World!
```

-s 0 - "0" indicates first SIM Slot
-s 1 - "1" indicates second SIM Slot

**Comment by byteshiva** [comment]
> Use the -s option:
> 
> ```
> $ termux-sms-send -help
> Usage: termux-sms-send -n number[,number2,number3,...] [-s slot] [text]
> Send a SMS message to the specified recipient number(s). The text to send is either supplied as arguments or read from stdin if no arguments are given.
>   -n number(s)  recipient number(s) - separate multiple numbers by commas
>   -s slot       sim slot to use - silently fails if slot number is invalid or if missing READ_PHONE_STATE permission
> ```

Side Note:
`termux-sms-send` wiki not updated. 

https://wiki.termux.com/wiki/Termux-sms-send

**Comment by machitgarha** [comment]
> -s 0 - "0" indicates first SIM Slot
> -s 1 - "1" indicates second SIM Slot

Doesn't work for me.

How can I find SIM slot IDs?

**Comment by machitgarha** [comment]
> Use the -s option:
> 
> ```
> $ termux-sms-send -help
> Usage: termux-sms-send -n number[,number2,number3,...] [-s slot] [text]
> Send a SMS message to the specified recipient number(s). The text to send is either supplied as arguments or read from stdin if no arguments are given.
>   -n number(s)  recipient number(s) - separate multiple numbers by commas
>   -s slot       sim slot to use - silently fails if slot number is invalid or if missing READ_PHONE_STATE permission
> ```

Notice the "missing READ_PHONE_STATE permission" part!

To get the permission, for example, you can run:

```
termux-telephony-deviceinfo
```

and then accept the permission dialog in your Android box.
