### ISSUE TITLE
termux-notification not working

### ISSUE THREAD

**Issue by PowaBanga** [termux/termux-api#484]
Hi,
is it normal that when i wrotte this on android 11 : 
```
termux-notification -c "content" --action "echo action"
```
termux stay running, and nothing happen.
I have to use CTRL+C to stop the process, and my phone do not recieve any notifications... :(

**Comment by Grimler91** [comment]
Have you installed the termux-api app? 
If yes, what version do you have of the termux-api app, and what version of the termux-api package?

**Comment by PowaBanga** [comment]
yes, 
`termux-api/stable,now 0.57 aarch64 [installed]`
the installed version is the same

**Comment by Grimler91** [comment]
That's the package, [not the app](https://f-droid.org/en/packages/com.termux.api/)

**Comment by PowaBanga** [comment]
rha yes, i forgot that !
i recieve this message when i try to install it :+1: 
`there are contradictory packages `
I do not know how to find which are contradictory package...

**Comment by PowaBanga** [comment]
I finaly removed termux-widget, installed termux-api reinstalled termux-widget...

and all work correctly, thank you very much @Grimler91 !!!
