### ISSUE TITLE
[question] Does termux-job-scheduler execute jobs without a Termux session?

### ISSUE THREAD

**Issue by kentcb** [termux/termux-api#489]
Sorry to ask here, but I can't find any answer in the docs. In fact, [the docs for `termux-job-scheduler`](https://wiki.termux.com/wiki/Termux-job-scheduler) seem to be missing altogether...?

Anyway, according to [this Reddit post](https://www.reddit.com/r/ObsidianMD/comments/omjyzi/setting_up_git_syncing_for_obsidian_on_android/h5mueuk/?utm_source=share&utm_medium=web2x&context=3) it sounds like jobs scheduled with `termux-job-scheduler` should run regardless of whether Termux has an active session running. But my experience (on a Pixel 3a) is that they do not. Once I start a Termux session, my jobs run as expected, but not before.

Is Termux misbehaving, or are my expectations off?

**Comment by tareksander** [comment]
`termux-job-scheduler` uses the Android job scheduling system directly, and Android has control of when these jobs run when the app itself isn't running. Do you have battery saving mode enabled? Have you configured Termux and Termux:API to ignore power savings mode in the Android app settings? That are the reasons I can think of right now why it won't work, worked fine for me.

**Comment by kentcb** [comment]
Yeah, my bad sorry. It turns out it was working - I forgot to come back and close this. Thanks for the response.
