### ISSUE TITLE
Get internet or airplane mode status

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-api#493]
**Feature description**

i am writing script that keeps looping and pauses if there is no internet connection.

So if using termux api we can get status whether internet is on or off or whether airplane mode is on or off so that i can control loop when connection is gone

**Reference implementation**

Have you checked if the feature is accessible through the Android API?
Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)

**Comment by krystean** [comment]
You can probably use `termux-wifi-connectioninfo` for the internet connection status.

**Comment by SDRausty** [comment]
>writing script that keeps looping and pauses if there is no internet connection.

I wrote and published [`ic.sh`](https://github.com/shlibs/shlibs.sh/blob/master/ic.sh) not long ago.  It checks the Internet connection.  Hopefully `ic.sh` will help you out with the Internet status check you are seeking;  Good luck!
