### ISSUE TITLE
Wish: Command to play alert/notification sound

### ISSUE THREAD

**Issue by dezifit** [termux/termux-api#5]
I tried to find a existing global Android intend for this purpose but didn't discovered one. `termux-play` is already listed in the idea section and would be very appreciated.

**Comment by fornwall** [comment]
There is already a `play-audio` command (in the package named `play-audio`) available that play files using the system media server (though a bit limited). Does that work for you?

**Comment by dezifit** [comment]
Yes! It plays mp3 files without further interaction, thats exactly what I was looking for. Many thanks again (and sorry to miss it).

**Comment by fornwall** [comment]
Great! It's easily missed, I'm planning to add a wiki or something similar with tips like these soon!
