### ISSUE TITLE
Open termux dialog with termux widget without opening termux just the sheet or radio button whatever as a pop up 

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-api#506]
**Feature description**

What i am trying is to use termux-dialog with termux-widget.

I wanted termux dialog to open as a pop up without opening termux itself and run rest script in background.

Trying to use pass manager in conjuction with termux-dialog.

What i am trying to implement is use termux widget with script ~/.shortcuts/Pass

Above when rum through widget open termux-dialog sheet with list of users stored in pass manager when clicked. it will copy the password.

But currently it open termux and then executes script. 

Please implement background functionality so that termux-dialog should open as a pop up rather than opening termux itself

**Reference implementation**

Have you checked if the feature is accessible through the Android API?
Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)

**Comment by agnostic-apollo** [comment]
Create script under `~/.shortcuts/tasks` to run it in a background task.

https://github.com/termux/termux-widget#script-directories-mandatory
