### ISSUE TITLE
termux-open-url works only if the terminal is the foreground

### ISSUE THREAD

**Issue by mayureshw** [termux/termux-api#509]
**Problem description**

I updated to latest version available on f-droid today. Previously I did not face this issue. termux-open-url pops up the application chooser dialog if termux terminal is in the focus. If termux is in the background and if you run termux-open-url by ssh'ing, then it doesn't work.

termux is in "wake lock held" state in case that matters.

**Steps to reproduce**

ssh to the device with sshd on termux running
in the ssh terminal type termux-open-url <some url>
keep termux application in the background on the phone UI

**Expected behavior**

An application chooser dialog should open
It is seen open only if termux application is in the foreground, else no dialog opens

**Additional information**

* termux-api application version: 0.50.1
* termux-api package version (installed through apt): 0.57
* Android OS version: 10
* Device model: Samsung Galaxy M01S

**Comment by agnostic-apollo** [comment]
Grant `Draw Over Apps` permission to termux.

https://github.com/termux/termux-widget/#draw-over-apps-permission-optional

**Comment by electr1fy0** [comment]
I still face this with many commands even when permission is granted.

**Comment by romanovj** [comment]
> This is still a major problem.

did you disable notifications for termux?

**Comment by mayureshw** [comment]
> > This is still a major problem.
> 
> did you disable notifications for termux?

No.

**Comment by agnostic-apollo** [comment]
Check `adb logcat -d > logcat.txt` output for exceptions/errors or post here after removing any private info or email me. You can also bring termux into foreground before running commands by running `am start -n com.termux/.app.TermuxActivity`

**Comment by twaik** [comment]
Maybe that is related to https://github.com/termux/TermuxAm/issues/7

**Comment by agnostic-apollo** [comment]
@electr1fy0 says he has already granted the permissions, hopefully the correct one.

- Android UI: `Android Settings` -> `Apps` -> `Termux` -> `Advanced` -> `Draw over other apps`. The permission name may be different on different devices, like on Xiaomi, its called `Display pop-up windows while running in the background`, check https://dontkillmyapp.com for device specific issues.

- `adb`: `adb shell "appops set --user 0 com.termux SYSTEM_ALERT_WINDOW allow"`

- `root`: `su -c "appops set --user 0 com.termux SYSTEM_ALERT_WINDOW allow"`

**Comment by mayureshw** [comment]
> Check `adb logcat -d > logcat.txt` output for exceptions/errors or post here after removing any private info or email me. You can also bring termux into foreground before running commands by running `am start -n com.termux/.app.TermuxActivity`

There is too much text in logcat, difficult to look for private info and filter. I'd have expected the cpu to be idle and logs to be sparse - like most other systems. Is a constantly scrolling log normal in android?

But the workaround you suggested works and is usable. I'll stick to that for now.

**Comment by agnostic-apollo** [comment]
You can always clear the logcat buffer with `adb logcat -c` before running required termux commands and dumping logs to only get recent entries.

>Is a constantly scrolling log normal in android?

Yes, there is always stuff happening underneath. Logs may slow down in deep sleep mode.

https://developer.android.com/tools/logcat
