### ISSUE TITLE
termux-clipboard-get not work with root user

### ISSUE THREAD

**Issue by RussiaVk** [termux/termux-api#510]
termux-clipboard-get seem can't work with root user.
It just stuck and no any output.

**Comment by wmcbtech30** [comment]
Termux:API runs on regular user context while you're in a root user context which it can't properly communicate if having to run the command as root. try running as regular user

**Comment by RussiaVk** [comment]
> Termux:API runs on regular user context while you're in a root user context which it can't properly communicate if having to run the command as root. try running as regular user


okey,thanks
