### ISSUE TITLE
Feature: A way to clear notifications generated by Termux:API

### ISSUE THREAD

**Issue by FluffyFoxUwU** [termux/termux-api#512]
**Feature description**

A way to clear all notification generated by Termux:API.

Use Case:
When you writing a script that create an ongoing notification and forget to remove the notification and didnt store the ID (basicly it stuck there forever)

**Reference implementation**

It functions like you have an array of notifications generated by Termux:API and there is API for clearing all notification generated by it. The name would be like `termux-api-clear-notification`

**Comment by HusniMuhammad** [comment]
```
termux-notification-remove
``` 

`Usage: termux-notification-remove notification-id
Remove a notification previously shown with termux-notification --id.`

**Comment by FluffyFoxUwU** [comment]
@HusniMuhammad thats close but my case is when during developing a script, the script crash and the ID is gone and `termux-notification-remove` needs ID

**Comment by HusniMuhammad** [comment]
**Use customised id (add id by your self)**
```
termux-notification --id=123
```

**And then mention the id for removing**

```
termux-notification-remove 123
```

**Comment by HusniMuhammad** [comment]
> **Feature description**
> 
> A way to clear all notification generated by Termux:API.
> 
> Use Case: When you writing a script that create an ongoing notification and forget to remove the notification and didnt store the ID (basicly it stuck there forever)
> 
> **Reference implementation**
> 
> It functions like you have an array of notifications generated by Termux:API and there is API for clearing all notification generated by it. The name would be like `termux-api-clear-notification`

Reply me

**Comment by FluffyFoxUwU** [comment]
> > **Feature description**
> > A way to clear all notification generated by Termux:API.
> > Use Case: When you writing a script that create an ongoing notification and forget to remove the notification and didnt store the ID (basicly it stuck there forever)
> > **Reference implementation**
> > It functions like you have an array of notifications generated by Termux:API and there is API for clearing all notification generated by it. The name would be like `termux-api-clear-notification`
> 
> Reply me

Sorry for late respond i was busy yesterday. Thanks, never thought of exiting termux would clear those notification.

**Comment by HusniMuhammad** [comment]
Thanks for you reply .
if it's worked please close this  issue :)

**Comment by FluffyFoxUwU** [comment]
Ok :3

**Comment by FluffyFoxUwU** [comment]
Ok :3
