### ISSUE TITLE
when there are wordwarps, only the first line will be sent with termux-sms-send

### ISSUE THREAD

**Issue by MurkyWang** [termux/termux-api#518]
when there are wordwarps, only the first line will be sent with termux-sms-send.
 i've tried everything."\n" char(10) etc

* termux-api application version:latest
* termux-api package version (installed through apt):latest
* Android OS version:Android 11,Android 12
* Device model:samsung s10, redmagic 6

**Comment by xalexalex** [comment]
Did you try simply embedding the newline in the string, e.g.

```
termux-sms-send -n 123123 "hello
world"
```
? This works for me.

**Comment by MurkyWang** [comment]
> Did you try simply embedding the newline in the string, e.g.
> 
> ```
> termux-sms-send -n 123123 "hello
> world"
> ```
> 
> ? This works for me.

it works, but sadly i won't be able to use that coz im using python to run the command.

**Comment by xalexalex** [comment]
You could also feed the string to the stdin of `termux-sms-send`, whatever best fits your bill. You'll have to fix your invocation, though; it's not a termux issue per se.
