### ISSUE TITLE
termux-camera-photo: black picture output (oneplus 3T, android 6.0.1)

### ISSUE THREAD

**Issue by exyode** [termux/termux-api#52]
termux-camera-photo pruduces black picture output (jpeg file size ~250-300 kb).
The issue only happens with termux-api v0.11 and v0.10.
Version 0.9 works fine and produces good photo.

**Comment by exyode** [comment]
Version 0.9 stopped working.
It looks like the default parameters for the camera doesn't work.

It would be nice to be able to specify camera parameters through command line.

**Comment by fornwall** [comment]
Thanks for finding out when it stopped working!

I guess the preview frames are needed.

**Comment by mannok** [comment]
So, will it be fixed?
Thank in advance.

**Comment by taltoris** [comment]
I am also having this issue. Any fixes in the works?

**Comment by marcbelmont** [comment]
I'm also having the issue with latest update 7.1.1 (Oneplus 3t)

**Comment by marcbelmont** [comment]
Here's the camera info

```
[
{
"id": "0",
"facing": "back",
"jpeg_output_sizes": [
{
"width": 4640,
"height": 3480
},
{
"width": 4640,
"height": 2610
},
{
"width": 4608,
"height": 3456
},
{
"width": 4608,
"height": 2592
},
{
"width": 3488,
"height": 3488
},
{
"width": 3840,
"height": 2160
},
{
"width": 3456,
"height": 3456
},
{
"width": 3264,
"height": 2448
},
{
"width": 3264,
"height": 1836
},
{
"width": 2464,
"height": 2464
},
{
"width": 2304,
"height": 1728
},
{
"width": 2304,
"height": 1296
},
{
"width": 1920,
"height": 1080
},
{
"width": 1728,
"height": 1728
},
{
"width": 1440,
"height": 1080
},
{
"width": 1280,
"height": 720
},
{
"width": 1080,
"height": 1080
},
{
"width": 720,
"height": 480
},
{
"width": 640,
"height": 480
},
{
"width": 480,
"height": 360
},
{
"width": 480,
"height": 320
},
{
"width": 352,
"height": 288
},
{
"width": 320,
"height": 240
},
{
"width": 176,
"height": 144
}
],
"focal_lengths": [
4.260000228881836
],
"auto_exposure_modes": [
"CONTROL_AE_MODE_OFF",
"CONTROL_AE_MODE_ON",
"CONTROL_AE_MODE_ON_AUTO_FLASH",
"CONTROL_AE_MODE_ON_ALWAYS_FLASH",
"CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE"
],
"physical_size": {
"width": 5.232640266418457,
"height": 3.9334399700164795
},
"capabilities": [
"backward_compatible",
"manual_sensor",
"manual_post_processing",
5,
6,
4,
7,
9,
"raw"
]
},
{
"id": "1",
"facing": "front",
"jpeg_output_sizes": [
{
"width": 4608,
"height": 3456
},
{
"width": 4608,
"height": 2592
},
{
"width": 3840,
"height": 2160
},
{
"width": 3456,
"height": 3456
},
{
"width": 2304,
"height": 1728
},
{
"width": 2304,
"height": 1296
},
{
"width": 1920,
"height": 1080
},
{
"width": 1728,
"height": 1728
},
{
"width": 1440,
"height": 1080
},
{
"width": 1280,
"height": 720
},
{
"width": 1080,
"height": 1080
},
{
"width": 720,
"height": 480
},
{
"width": 640,
"height": 480
},
{
"width": 480,
"height": 360
},
{
"width": 480,
"height": 320
},
{
"width": 352,
"height": 288
},
{
"width": 320,
"height": 240
},
{
"width": 176,
"height": 144
}
],
"focal_lengths": [
3.569999933242798
],
"auto_exposure_modes": [
"CONTROL_AE_MODE_OFF",
"CONTROL_AE_MODE_ON"
],
"physical_size": {
"width": 5.178879737854004,
"height": 3.8886401653289795
},
"capabilities": [
"backward_compatible",
"manual_sensor",
"manual_post_processing",
5,
6,
4,
7
]
}
]
```

**Comment by qwerty250** [comment]
Will it be fixed?

**Comment by Linreg-gmx-net** [comment]
Black picture output also happen on Galaxy S6 and Huawei P10 (Pro). Front and Back camera.
How can i help? With Testing or so

**Comment by willem640** [comment]
Also happens on honor 6x europe variant bln-l21

Camera info:

```
[
  {
    "id": "0",
    "facing": "back",
    "jpeg_output_sizes": [
      {
        "width": 320,
        "height": 240
      },
      {
        "width": 640,
        "height": 480
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 1920,
        "height": 1080
      },
      {
        "width": 3264,
        "height": 1840
      },
      {
        "width": 3264,
        "height": 2448
      },
      {
        "width": 3968,
        "height": 2976
      },
      {
        "width": 2048,
        "height": 1536
      },
      {
        "width": 2976,
        "height": 2976
      },
      {
        "width": 3968,
        "height": 2240
      }
    ],
    "focal_lengths": [
      3.8299999237060547
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_OFF",
      "CONTROL_AE_MODE_ON",
      "CONTROL_AE_MODE_ON_AUTO_FLASH",
      "CONTROL_AE_MODE_ON_ALWAYS_FLASH"
    ],
    "physical_size": {
      "width": 5.039999961853027,
      "height": 3.7699999809265137
    },
    "capabilities": [
      "backward_compatible",
      "manual_post_processing",
      "raw",
      9
    ]
  },
  {
    "id": "1",
    "facing": "front",
    "jpeg_output_sizes": [
      {
        "width": 640,
        "height": 480
      },
      {
        "width": 320,
        "height": 240
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 1920,
        "height": 1080
      },
      {
        "width": 3264,
        "height": 2448
      },
      {
        "width": 2448,
        "height": 2448
      },
      {
        "width": 2592,
        "height": 1952
      },
      {
        "width": 3264,
        "height": 1840
      }
    ],
    "focal_lengths": [
      2.819999933242798
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_OFF",
      "CONTROL_AE_MODE_ON"
    ],
    "physical_size": {
      "width": 3.6700000762939453,
      "height": 2.759999990463257
    },
    "capabilities": [
      "backward_compatible",
      "manual_post_processing"
    ]
  }
]
```

**Comment by willem640** [comment]
Looking at camera info, might this be an issue with auto exposure?

**Comment by al-paul** [comment]
Experiencing the same issue on a SONIM phone.  I hear a faint "click" and am left with an image of 189341 in size, but always black.  Same results with the front camera.  Here is my termux-info, followed by the termux-camera-info:

Updatable packages:
All packages up to date
System information:
Linux localhost 4.4.21-perf+ #1 SMP PREEMPT Fri May 18 18:32:02 IST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.1.1
Device manufacturer:
Sonimtech
Device model:
XP8800

[
  {
    "id": "0",
    "facing": "back",
    "jpeg_output_sizes": [
      {
        "width": 4000,
        "height": 3000
      },
      {
        "width": 3840,
        "height": 2160
      },
      {
        "width": 3264,
        "height": 2448
      },
      {
        "width": 3200,
        "height": 2400
      },
      {
        "width": 2976,
        "height": 2976
      },
      {
        "width": 2592,
        "height": 1944
      },
      {
        "width": 2688,
        "height": 1512
      },
      {
        "width": 2048,
        "height": 1536
      },
      {
        "width": 1920,
        "height": 1080
      },
      {
        "width": 1600,
        "height": 1200
      },
      {
        "width": 1440,
        "height": 1080
      },
      {
        "width": 1280,
        "height": 960
      },
      {
        "width": 1280,
        "height": 768
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 1200,
        "height": 1200
      },
      {
        "width": 1280,
        "height": 480
      },
      {
        "width": 1024,
        "height": 768
      },
      {
        "width": 800,
        "height": 600
      },
      {
        "width": 864,
        "height": 480
      },
      {
        "width": 800,
        "height": 480
      },
      {
        "width": 720,
        "height": 480
      },
      {
        "width": 640,
        "height": 480
      },
      {
        "width": 640,
        "height": 360
      },
      {
        "width": 480,
        "height": 640
      },
      {
        "width": 480,
        "height": 360
      },
      {
        "width": 480,
        "height": 320
      },
      {
        "width": 352,
        "height": 288
      },
      {
        "width": 320,
        "height": 240
      },
      {
        "width": 240,
        "height": 320
      },
      {
        "width": 176,
        "height": 144
      },
      {
        "width": 160,
        "height": 120
      },
      {
        "width": 144,
        "height": 176
      }
    ],
    "focal_lengths": [
      3.950000047683716
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_OFF",
      "CONTROL_AE_MODE_ON",
      "CONTROL_AE_MODE_ON_AUTO_FLASH",
      "CONTROL_AE_MODE_ON_ALWAYS_FLASH",
      "CONTROL_AE_MODE_ON_AUTO_FLASH_REDEYE"
    ],
    "physical_size": {
      "width": 5.139999866485596,
      "height": 3.859999895095825
    },
    "capabilities": [
      "backward_compatible",
      "manual_sensor",
      "manual_post_processing",
      5,
      6,
      7,
      9,
      "raw"
    ]
  },
  {
    "id": "1",
    "facing": "front",
    "jpeg_output_sizes": [
      {
        "width": 3264,
        "height": 2448
      },
      {
        "width": 3200,
        "height": 2400
      },
      {
        "width": 2592,
        "height": 1944
      },
      {
        "width": 2688,
        "height": 1512
      },
      {
        "width": 2048,
        "height": 1536
      },
      {
        "width": 1920,
        "height": 1080
      },
      {
        "width": 1600,
        "height": 1200
      },
      {
        "width": 1440,
        "height": 1080
      },
      {
        "width": 1280,
        "height": 960
      },
      {
        "width": 1280,
        "height": 768
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 1200,
        "height": 1200
      },
      {
        "width": 1280,
        "height": 480
      },
      {
        "width": 1024,
        "height": 768
      },
      {
        "width": 800,
        "height": 600
      },
      {
        "width": 864,
        "height": 480
      },
      {
        "width": 800,
        "height": 480
      },
      {
        "width": 720,
        "height": 480
      },
      {
        "width": 640,
        "height": 480
      },
      {
        "width": 640,
        "height": 360
      },
      {
        "width": 480,
        "height": 640
      },
      {
        "width": 480,
        "height": 360
      },
      {
        "width": 480,
        "height": 320
      },
      {
        "width": 352,
        "height": 288
      },
      {
        "width": 320,
        "height": 240
      },
      {
        "width": 240,
        "height": 320
      },
      {
        "width": 176,
        "height": 144
      },
      {
        "width": 160,
        "height": 120
      },
      {
        "width": 144,
        "height": 176
      }
    ],
    "focal_lengths": [
      2.559999942779541
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_OFF",
      "CONTROL_AE_MODE_ON"
    ],
    "physical_size": {
      "width": 3.655679941177368,
      "height": 2.741760015487671
    },
    "capabilities": [
      "backward_compatible",
      "manual_sensor",
      "manual_post_processing",
      5,
      6,
      7,
      9,
      "raw"
    ]
  }
]

**Comment by meberli** [comment]
same issue: black image with both front and back camera
model: google pixel
android 9

**Comment by seisdr** [comment]
yea

**Comment by seisdr** [comment]
Camera info useless

**Comment by ruipalma** [comment]
Same behavior on oneplus 3t

**Comment by shagarah** [comment]
Same here Xiomi A1 

If we can increase exposure please, the photo is just too dark in room light, and trying to fix that using imagemagick produces very low quality image. Also, using termux-torch is useless.

**Comment by lsisoft** [comment]
I also have a Samsung Galaxy S8+ and I get very dark images.

I think the fix means playing with following file:
https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/PhotoAPI.java

and submitting a pull request after one of us manages to fix it.

Googled: "CaptureRequest.Builder take photo exposure compensation" and got a lot of answers, but I am not a Android java developer to get it done.

**Comment by asdman384** [comment]
the same issue, phone: huawei p8 lite 2017
termux-camera-info
` [
  {
    "id": "0",
    "facing": "back",
    "jpeg_output_sizes": [
      {
        "width": 3968,
        "height": 2976
      },
      {
        "width": 640,
        "height": 480
      },
      {
        "width": 320,
        "height": 240
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 1920,
        "height": 1080
      },
      {
        "width": 3264,
        "height": 1840
      },
      {
        "width": 3264,
        "height": 2448
      },
      {
        "width": 2048,
        "height": 1536
      },
      {
        "width": 2976,
        "height": 2976
      },
      {
        "width": 3968,
        "height": 2240
      }
    ],
    "focal_lengths": [
      3.8299999237060547
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_OFF",
      "CONTROL_AE_MODE_ON",
      "CONTROL_AE_MODE_ON_AUTO_FLASH",
      "CONTROL_AE_MODE_ON_ALWAYS_FLASH"
    ],
    "physical_size": {
      "width": 5.039999961853027,
      "height": 3.7699999809265137
    },
    "capabilities": [
      "backward_compatible",
      "manual_post_processing",
      "raw",
      9
    ]
  },
  {
    "id": "1",
    "facing": "front",
    "jpeg_output_sizes": [
      {
        "width": 3264,
        "height": 2448
      },
      {
        "width": 640,
        "height": 480
      },
      {
        "width": 320,
        "height": 240
      },
      {
        "width": 1280,
        "height": 720
      },
      {
        "width": 1920,
        "height": 1080
      },
      {
        "width": 2448,
        "height": 2448
      },
      {
        "width": 2592,
        "height": 1952
      },
      {
        "width": 3264,
        "height": 1840
      }
    ],
    "focal_lengths": [
      2.819999933242798
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_OFF",
      "CONTROL_AE_MODE_ON"
    ],
    "physical_size": {
      "width": 3.6700000762939453,
      "height": 2.759999990463257
    },
    "capabilities": [
      "backward_compatible",
      "manual_post_processing"
    ]
  }
]`

**Comment by anarchist912** [comment]
Very dark, almost black pictures with Fairphone 2, Android 7. All packages / termux apps on latest version. It would be awesome if we could control camera parameters via flags. When I open one of the cameras in the OpenCamera app, it comes from black to clear, bright image within 200ms or so. What happens, I guess, is that the camera open its shutter and the sensors start receiving light. There should be a delay between opening the shutter and actually taking the picture, so that the picture is taken, when the camera is fully "initialized".
I'll donate € 10, if you fix this.

**Comment by anarchist912** [comment]
```

  {
    "id": "0",
    "facing": "back",
    "jpeg_output_sizes": [..]
    "focal_lengths": [
      3.700000047683716
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_ON",
      "CONTROL_AE_MODE_ON_AUTO_FLASH",
      "CONTROL_AE_MODE_ON_ALWAYS_FLASH"
    ],
    "physical_size": {
      "width": 5.709062099456787,
      "height": 5.709062099456787
    },
    "capabilities": [
      "backward_compatible"
    ]
  },
  {
    "id": "1",
    "facing": "front",
    "jpeg_output_sizes": [..],
    "focal_lengths": [
      2.930000066757202
    ],
    "auto_exposure_modes": [
      "CONTROL_AE_MODE_ON"
    ],
    "physical_size": {
      "width": 3.0375354290008545,
      "height": 2.278829336166382
    },
    "capabilities": [
      "backward_compatible"
    ]
  }
]
```

**Comment by erikkut** [comment]
has anyone found a solution for this?

**Comment by popsc30** [comment]
come on, almost 3 years.. still no solution?

**Comment by UmutAlihan** [comment]
still having the issue

**Comment by xalexalex** [comment]
Guys, I'm sorry but until today, nobody on the team has had the time to work on this, and pinging won't get the issue fixed. Best you can do is draft a PR.

**Comment by Bartvelp** [comment]
Unable to verify but this pull requests referenced the issue, https://github.com/termux/termux-api/pull/254 by @erqan
can anybody rebuild and verify this works?

**Comment by OmarMohamedKhallaf** [comment]
Anything new ??

**Comment by UmutAlihan** [comment]
To my knowledge there is not.

**Comment by softy2k** [comment]
Very dark with Samsung Galaxy S7, Android 8.0.0

{"id":"0","facing":"back","jpeg_output_sizes":[{"width":4032,"height":3024},{"width":4032,"height":2268},{"width":3024,"height":3024},{"width":3984,"height":2988},{"width":3264,"height":2448},{"width":3264,"height":1836},{"width":2976,"height":2976},{"width":2880,"height":2160},{"width":2560,"height":1440},{"width":2160,"height":2160},{"width":2048,"height":1152},{"width":1920,"height":1080},{"width":1440,"height":1080},{"width":1088,"height":1088},{"width":1280,"height":720},{"width":1056,"height":704},{"width":1024,"height":768},{"width":960,"height":720},{"width":800,"height":450},{"width":720,"height":720},{"width":720,"height":480},{"width":640,"height":480},{"width":352,"height":288},{"width":320,"height":240}],"focal_lengths":[4.199999809265137],"auto_exposure_modes":["CONTROL_AE_MODE_OFF","CONTROL_AE_MODE_ON","CONTROL_AE_MODE_ON_AUTO_FLASH","CONTROL_AE_MODE_ON_ALWAYS_FLASH"],"physical_size":{"width":5.644999980926514,"height":4.434999942779541},"capabilities":["backward_compatible","manual_sensor","manual_post_processing","raw",5,6,9]}
