### ISSUE TITLE
Termux api GitHub version detected as malware 

### ISSUE THREAD

**Issue by Anonymous1231-dev** [termux/termux-api#520]
**Problem description**
As title said 

**Steps to reproduce**
Download it from GitHub 

**Expected behavior**

**Additional information**

* termux-api application version: GitHub version 
* termux-api package version (installed through apt): latest
* Android OS version:12
* Device model: vivo v2027

**Comment by wmcbtech30** [comment]
The information isn't enough and this is likely marked as false-positive. what antivirus triggers when installing termux api?
