### ISSUE TITLE
Can't install Termux:Api from google play on Nougat. 

### ISSUE THREAD

**Issue by jottr** [termux/termux-api#53]
I've tried to install **Termux:Api** on a rooted Nexus 6P running Nougat (`7.1.1 Build NMF26F`). 
I've tried rebooting and clearing google play cache. To no avail. 
Google Play issues the following errorcode `-505`, which to my understanding is a catch-all for various errors. 
The device has sufficient storage memory.
The same happens when trying to install **Termux:Task** on that device.

**Comment by fornwall** [comment]
@jottr Did you install the main Termux app also from Google Play?

You need to install Termux and it's add-ons from the same source (either F-Droid or Google Play) - you cannot mix sources, as they use different keys for signing the apps, and they need to be signed with the same key.

**Comment by jottr** [comment]
That fixed it, thanks you.

**Comment by Javimoya03** [comment]
> That fixed it, thanks you. 

how did you fix it?

**Comment by NAJIBnaderi2014** [comment]
Schw action
