### ISSUE TITLE
Help trying to create a constant location data stream

### ISSUE THREAD

**Issue by snuffysasa** [termux/termux-api#536]
I am able to use `termux-location`  to get the console to print the gps coordinates.

and I understand that is just a wrapper around running `./termux-api-broadcast Location`

... and digging into that more, I found that is just a wrapper around running `am broadcast com.termux.api/.TermuxApiReceiver`
 with specifying some sockets (unix sockets?)

I am trying to get to the source of this... at the end of the day.. my goal is to make a C/C++ application that I can compile for the device and launch with either termux/adb shell/ or bind to startup script.  and I want that C/C++ application to get a constant stream of GPS data, preferable once per second or even faster frequency.

One method to do this, is I was figuring I can use the termux-api for that.  (although, if there is a way I can get around that and go directly, to whatever method the termux api is using to get that data, that might be more ideal)

So Anyways, I have been reading the termux-api code and I have been able to compile it myself and run it with slight tweaks.  I want to modify the code/api.. so that instead of printing once and exiting..I want it to stay open and publish a constant location data stream.  I also notice that it's quite slow, which I read is because it launches a VM?  It's okay if launch time is slow, if I can get it to launch and run forever and stay open, constantly publishing location. 

There should be away I can modify the termux-api to do this right? Can you recommend the best method of doing this?

I am also wondering what is `am broadcast`?  and I am wondering where / how does TermuxApi receive the gps data to begin with?

Any support would be hugely appreciated! Thanks!

**Comment by tareksander** [comment]
> I am also wondering what is am broadcast? and I am wondering where / how does TermuxApi receive the gps data to begin with?

Termux:API gets the location data from Android itself, and Android APIs are usually only accessible from an app (require an app context) and only from Java/Kotlin, not native code.  
am is a command line tool to send intents: https://developer.android.com/guide/components/intents-filters  
  

The command parameters and the output socket address are send to the Termux:API app via a broadcast. Termux:API then runs the command, opens a connection to the server socket address and outputs the result. Receiving a broadcast only makes Android not kill the app for a short period of time, after that Android is free to kill the app. If you want to modify it so you get a constant stream of data, you would probably have to use a foreground service to keep the app alive.

**Comment by snuffysasa** [comment]
First, thank you so much for a response and the information. This really helps me out.

>Termux:API gets the location data from Android itself, and Android APIs are usually only accessible from an app (require an app context) and only from Java/Kotlin, not native code.

So because Termux is an app it is able to access the android APIs?  There is really not a way to access the GPS from native code?  Even on a rooted phone?   How does the Android OS get the GPS data in the first place?  I want to do the same retrieval that it does, going right to the hardware/driver. I assume I'd need root access... but I am wondering should I give this up? is this just a pipe dream and not really realistic to do on android?

>Receiving a broadcast only makes Android not kill the app for a short period of time, after that Android is free to kill the app. If you want to modify it so you get a constant stream of data, you would probably have to use a foreground service to keep the app alive.

Okay So if I understand correctly Termux and Termux API are two separate android apps?   And from Termux it triggers a command that launches termuxApi just for a moment to get the GPS data then sent back to Termux via socket. Then TermuxAPI closes... Is this all correct?

So I am wondering why can't the Termux app simply just get the GPS data itself?

**Comment by agnostic-apollo** [comment]
You can use `/system/bin/dumpsys location` with either `adb` from ([`android-tools` package](https://www.reddit.com/r/termux/comments/mmu2iu/announce_adb_is_now_packaged_for_termux/)) or `root` to get last known location, but if no app is requesting updates, then you will only get old values, not live.

https://android.stackexchange.com/questions/85279/a-way-to-get-location-coordinates-from-command-line

The location interfaces require a callback object, so only apps can request it, otherwise `service call` command could have been used.

https://cs.android.com/android/platform/superproject/+/android-12.0.0_r34:frameworks/base/location/java/android/location/ILocationManager.aidl;l=54

https://cs.android.com/android/platform/superproject/+/android-12.0.0_r34:frameworks/base/services/core/java/com/android/server/location/provider/LocationProviderManager.java;l=1103

> sent back to Termux via socket.

Send back to native program.

https://github.com/termux/termux-api-package/blob/master/scripts/termux-location.in

https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/apis/LocationAPI.java

Also in its current state, location api is broken and not reliable due to not following android guidelines and background restrictions and requires work to fix.

>So I am wondering why can't the Termux app simply just get the GPS data itself?

termux api is separate for segregation. It does not handle location stuff at all. Only script and termux-api app communicate themselves. Commands will be relayed through termux app in next version to decrease startup time.

**Comment by snuffysasa** [comment]
Thanks again!  This is super helpfu

> You can use /system/bin/dumpsys location with either adb from ([android-tools package](https://www.reddit.com/r/termux/comments/mmu2iu/announce_adb_is_now_packaged_for_termux/)) or root to get last known location, but if no app is requesting updates, then you will only get old values, not live.

That's working I am able to get the location values this way.  So then in this case, I feel like I should be able to create an app, or use en existing app, and set it to launch on startup, and have it just constantly request the location (even if do nothing with it), and I mean constantly like 10 times per second.

Then I can repeatedly do `dumpsys` from another program and process the output for GPS stream.

Do you know of an existing app that I could use to do this, Or mod Termux app to do it, or just make my own app from scratch that just uses the location api and makes a request on a loop.

**Comment by agnostic-apollo** [comment]
You can use Tasker app. Create a profile for `Tick` event and in entry task, use `Get Location v2` action. You will get data back in local variables, which you can pass to native program by writing to a file and tailing/inotifying it in native program, like with `Run Shell` action. You can even run native program in `Run Shell` itself. You can also use a task with goto infinite loop and wait action, but it may stop if tasker gets killed, so will need monitor start and other events to automatically restart it.

https://tasker.joaoapps.com/

https://tasker.joaoapps.com/userguide/en/help/ah_get_current_location.html

There is an open source alternative Easer that has some location support, but I haven't used it.

https://f-droid.org/packages/ryey.easer/

https://me.ryey.icu/Easer/en/FEATURES

**Comment by snuffysasa** [comment]
@agnostic-apollo 

Thank you so much, I think that should work for this problem I was trying to solve.  

I actually have some more somewhat similar questions. However, I am closing this issue, because didn't think it was fair to hijack this GitHub repo because my questions were getting off topic.

Would you be willing to answer some other questions related to this?  You seemed to have a lot of helpful answers and information, and I don't know a ton about android yet.  Of course you don't have to help me, but if you are willing, could I just post more answers on this closed thread? or contact you another way.   I am willing to do something in exchange for your help/answers/information.

**Comment by snuffysasa** [comment]
Okay great! look for a post on r/termux from mattsasa
