### ISSUE TITLE
Feature Request: Implement termux-wakelock using unix socket

### ISSUE THREAD

**Issue by ccaapton** [termux/termux-api#543]
**Feature description**

Current the wakelock mechanism is implemented as `am startservice` which is too heavy weighted and cause a lot of latency. As we now have unix socket, wakelock/unlock could be much more responsive.

**Reference implementation**

Have you checked if the feature is accessible through the Android API?
Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)

**Comment by tareksander** [comment]
If you use the Github action build of Termux, you can try replacing the `am` in the scripts with `termux-am`. It uses a unix socket to connect to the main app and should be about 10 times faster (or was it 100? I can't remember, I ran the tests a long time ago). Emulating `am` is easier than changing all APIs to unix sockets.

**Comment by ccaapton** [comment]
@tareksander I'm using f-droid build of termux with every thing up to date, but when I replace am with termux-am, it give the error `Could not connect to socket: No such file or directory` .

```
Termux Variables:                    
TERMUX_APP_PACKAGE_MANAGER=apt                                                                                             
TERMUX_MAIN_PACKAGE_FORMAT=debian                                                                                          
TERMUX_VERSION=0.118.0                                                                                                     
Packages CPU architecture:                                                                                                 
aarch64                                                                                                                    
Subscribed repositories:                                                                                                   
# sources.list        
deb https://mirror.iscas.ac.cn/termux/apt/termux-main stable main
# root-repo (sources.list.d/root.list)                                                                                     
deb https://grimler.se/termux/termux-root root stable
# x11-repo (sources.list.d/x11.list)
deb https://grimler.se/termux/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.27.0
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf-gf5e9e9c #2 SMP PREEMPT Tue Jul 27 21:52:42 CST 2021 aarch64 Android
```
What should I do to make it work?

**Comment by tareksander** [comment]
> If you use the Github action build of Termux

I said that for a reason, that feature isn't in the fdroid releases yet. Also iirc Termux:API doesn't provide the wakelock, but the main app, so the only thing to do is to wait for the next fdroid release or switch to Github action builds for Termux and all plugins.
