### ISSUE TITLE
Android 12 major performance degradation 

### ISSUE THREAD

**Issue by hanyman7** [termux/termux-api#547]
**Problem description**

**Steps to reproduce**

**Expected behavior**

**Additional information**

* termux-api application version:
* termux-api package version (installed through apt):
* Android OS version:
* Device model:

Termux Variables:
unsupported
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
Listing...
termux-tools version:
1.29.2
Android version:
12
Kernel build information:
Linux localhost 5.10.66-android12-9-24537318-abA536USQU2AVG2 #2 SMP PREEMPT Wed Jul 20 23:14:17 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A536U

**Comment by Grimler91** [comment]
There's no info here, so impossible to know what type of degradation that supposedly has been observed

**Comment by hanyman7** [comment]
On my old Android


> 
[J8.j7:26031:/data/data/com.termux/files/home] 0
_> time termux-battery-status
{
  "health": "GOOD",
  "percentage": 100,
  "plugged": "PLUGGED_AC",
  "status": "FULL",
  "temperature": 27.5,
  "current": 0
}

real    0m0.614s
user    0m0.008s
sys     0m0.040s
[J8.j7:26031:/data/data/com.termux/files/home] 0
_> oslevel                                             Android version: 10
Kernel build information: Linux localhost 4.4.177-19844912 #1 SMP PREEMPT Wed Mar 30 18:53:10 KST 2022 aarch64 Android
[J8.j7:26031:/data/data/com.termux/files/home] 0
_>


On my new Android

[/data/data/com.termux/files/home] 0
-> time termux-battery-status
osl{
  "health": "GOOD",
  "percentage": 88,
  "plugged": "UNPLUGGED",
  "status": "DISCHARGING",
  "temperature": 38.0,
  "current": -396
}

real    0m3.671s
user    0m0.005s
sys     0m0.013s
[/data/data/com.termux/files/home] 0
-> oslevel                                             Android version: 12
Kernel build information: Linux localhost 5.10.66-android12-9-24537318-abA536USQU2AVG2 #2 SMP PREEMPT Wed Jul 20 23:14:17 KST 2022 aarch64 Android
[/data/data/com.termux/files/home] 0
->

**Comment by hanyman7** [comment]
I put these directions basically type

time termux-battery-status or any other termux-* call and it takes in excess of 3.8 seconds.

Note this "may" be related to the new dalvikvm -Ximage-dex2oat default that I have observed since the Android 12 my phone company pushed out.

Lemme know if I need to re-open this issue with all the data. I am new here, however, would gladly do so

**Comment by agnostic-apollo** [comment]
That should already be solved with https://github.com/termux/termux-api-package/pull/147 and https://github.com/termux/termux-app/pull/2458 but there hasn't been a release of `termux-api-package` since then. Requires termux app release as well for F-Droid.

**Comment by mentalisttraceur** [comment]
@agnostic-apollo so is that release ever going to happen?
