### ISSUE TITLE
Slow speed for termux-clipboard-set (avg 5seconds)

### ISSUE THREAD

**Issue by Haiz14** [termux/termux-api#585]
**Problem description**

When doing `termux-clipboard-set "hi"` the avg time it takes is around 5 seconds

**Steps to reproduce**

• download termux api app
• install termux api pkg on termux
• do `termux-clipboard-set "hi"`

**Expected behavior**

The command should be executed in 1-2 seconds instead of 5 seconds

**Additional information**

* termux-api application version: 0.50.1 (GitHub release)
* termux-api package version (installed through apt): 0.57
* Android OS version: 12
* Device model: Realme 7

**Comment by Haiz14** [comment]
![Screenshot_2023-02-08-10-50-30-38_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/68465021/217512586-c062a38b-de52-4417-a9d6-8b7d038514be.jpg)

**Comment by RVC2020** [comment]
I have the same issue, also android 12, termux:API 0.50.1, package version 0.57.
![Screenshot_20230506-131253](https://user-images.githubusercontent.com/75840436/236618508-1a3b421b-cbc8-4737-ba7a-97e4940c14a6.png)

**Comment by agnostic-apollo** [comment]
First non-Samsung device.

Check https://github.com/termux/termux-api/issues/552#issuecomment-1382722639

**Comment by RVC2020** [comment]
Sorry for forgetting about this issue. The solution definitely improved the time. 
The phone is Motorola g42 (android 12).
Thank you for your help.
![time_termux_clip](https://github.com/termux/termux-api/assets/75840436/4494d9ea-b0b5-493f-a19d-9fe3acfd0b6b)

**Comment by agnostic-apollo** [comment]
You are welcome. Fix has been added to latest `termux-am` package as well.
