### ISSUE TITLE
[question] Must be signed by same key as termux itself?

### ISSUE THREAD

**Issue by krt16s** [termux/termux-api#6]
I get an installation error about shared resources when installing. I suspect the app needs to be signed by the same key as termux itself?

**Comment by fornwall** [comment]
Yes, at the moment termux-api needs to be signed with the same key as the termux-app itself. This is for security, to avoid other random apps calling Termux API functions (custom permissions could perhaps be used for this in the future instead).

To get it working for now you should probably install both termux-app and termux-api from source with your own debug keys - does that work for you?

**Comment by krt16s** [comment]
I raised an issue with f-droid at https://gitlab.com/fdroid/fdroidserver/issues/127, thanks for the explanation.
