### ISSUE TITLE
Termux-notification: Add image.

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#60]
Certain apps, mostly audio players, have pictures in the notifications. These pictures are then set as lock screen wallpapers.
Example: Pocket casts
![screenshot_20170130-185604](https://cloud.githubusercontent.com/assets/7983745/22434883/35326b3a-e71e-11e6-9268-e4e6d6b59753.png)

I'd like for this to be added to the termux-notification api.
Specifically I would use this in [Termux-Mpv](https://github.com/Neo-Oli/Termux-Mpv) to display album-art

**Comment by xalexalex** [comment]
The function has been implemented in termux-api and in termux-api-package, however I can't get it to work, so I'm keeping this issue open and also tagging it with `bug report`.

**Comment by HusniMuhammad** [comment]
**Use this command**

```
termux-notification --image-path /storage/emulated/0/img.png
``` 

![Screenshot_20230905-163941](https://github.com/termux/termux-api/assets/104101867/6ca0a772-b425-4309-a3c1-1a371c4fea97)

**For more information**

```
termux-notification -h
```


**If it's works please close this issue**

**Comment by Neo-Oli** [comment]
Yeah, I guess this works now. This is an old issue. It's important to note that it only seems to work with globally readable files. So files in `/sdcard`. Not with files in the Termux Home directory.

**Comment by HusniMuhammad** [comment]
> Yeah, I guess this works now. This is an old issue. It's important to note that it only seems to work with globally readable files. So files in `/sdcard`. Not with files in the Termux Home directory.

I think it would be work if  files in `$HOME`
