### ISSUE TITLE
Question: How to set the clipboard under the root user

### ISSUE THREAD

**Issue by stevenxxiu** [termux/termux-api#619]
I'm running a program that has to be run under root. I also want to set the clipboard in this program. How do I do that?

The following works for me under the *Termux* user:

    $ /data/data/com.termux/files/usr/bin/termux-clipboard-set foo

However under root nothing happens. The command just hangs.

    # /data/data/com.termux/files/usr/bin/termux-clipboard-set foo

I tried to switch to my *Termux* user too. It hangs as well.

```
$ whoami
u0_a324
$ su
# su u0_a324 --command '/data/data/com.termux/files/usr/bin/termux-clipboard-set foo'
```

**Comment by cxyzzz** [comment]
> I'm running a program that has to be run under root. I also want to set the clipboard in this program. How do I do that?
> 
> The following works for me under the _Termux_ user:
> 
> ```
> $ /data/data/com.termux/files/usr/bin/termux-clipboard-set foo
> ```
> 
> However under root nothing happens. The command just hangs.
> 
> ```
> # /data/data/com.termux/files/usr/bin/termux-clipboard-set foo
> ```
> 
> I tried to switch to my _Termux_ user too. It hangs as well.
> 
> ```
> $ whoami
> u0_a324
> $ su
> # su u0_a324 --command '/data/data/com.termux/files/usr/bin/termux-clipboard-set foo'
> ```

try this ,touch `termux-tools` file,add this content .
``` bash
#!/system/bin/sh

export LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
export PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets

exec "$@"
```
`chmod +x termux-tools`,then you can run termux command with root user in other application. 

this way is working in my old phone,but when i change a phone it's got a `ResultReturner:
java.io.IOException: Permission denied
	at android.net.LocalSocketImpl.connectLocal(Native Method)
`error, you can try it, maybe it's work for you😂😂😂

**Comment by romanovj** [comment]
You should dig into selinux.

Simple fix - disabling selinux

**setenforce 0**

more advanced 

sudo ps -AZ | grep termux.api
magiskpolicy --live "allow **untrusted_app_27** * * *"

**Comment by cxyzzz** [comment]
> 

It's work ,thank!

**Comment by stevenxxiu** [comment]
@romanovj Thanks for the suggestion, however I still can't get it working. Running the following under root doesn't even start the *Termux:API* app:

    # termux-clipboard-set foo

I'm on *Android 13*.

Any ideas, short of debugging this?

**Comment by cxyzzz** [comment]
> @romanovj Thanks for the suggestion. I tried disabling _SELinux_ globally, or through `magiskpolicy` (my `ps` label is also `untrusted_app_27`). However I still can't get it working. Running the following under root doesn't even start the _Termux:API_ app:
> 
> ```
> # termux-clipboard-set foo
> ```
> 
> I'm on _Android 13_.
> 
> Any ideas, short of debugging this?

try this，it's working fine.
``` bash
#!/system/bin/sh

export SHELL="/data/data/com.termux/files/usr/bin/bash"
export PREFIX="/data/data/com.termux/files/usr"
export PWD="/data/data/com.termux/files/home"
export EXTERNAL_STORAGE="/sdcard"
export LD_PRELOAD="/data/data/com.termux/files/usr/lib/libtermux-exec.so"
export HOME="/data/data/com.termux/files/home"
export LANG="en_US.UTF-8"
export TMPDIR="/data/data/com.termux/files/usr/tmp"
export ANDROID_DATA="/data"
export TERM="xterm-256color"
export SHLVL="1"
export ANDROID_ROOT="/system"
export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
export PATH="/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets"
export _="/data/data/com.termux/files/usr/bin/env"

"$@"
```

**Comment by romanovj** [comment]
> > try this，it's working fine.
> 
> Nope setting your environment variables don't work for me.

check if you have selinux context

id
uid=0(root) gid=0(root) context=u:r:magisk:s0

**Comment by stevenxxiu** [comment]
@romanovj Thanks for the comment, that was really helpful for debugging. It got me going through the various `su` commands to see what they were doing.

Turns out *SELinux* permissive wasn't needed for me.

What I needed was to forward these environment variables to `root`:

- `ANDROID_ART_ROOT`
- `ANDROID_I18N_ROOT`
- `ANDROID_TZDATA_ROOT`
- `BOOTCLASSPATH`

I haven't investigated as of why, but this is the minimal set that works.
