### ISSUE TITLE
Termux-notification: Make notification permanent

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#62]
It woule be great if there could be a switch for `termux-notification` to have the notification pinned. Only to be removed with `termux-notification-remove`. It could be used to indicate running processes. Like backup scripts or media playback (https://github.com/Neo-Oli/Termux-Mpv)

**Comment by xalexalex** [comment]
Closing as this has been implemented: `termux-notification [...] --ongoing`
