### ISSUE TITLE
MIUI 14 (Android 13) notice: Termux-api needs to be set to [self-start]

### ISSUE THREAD

**Issue by zz5678** [termux/termux-api#625]
MIUI 14 小米/红米手机需要安装，并将 Termux-api 设置为【自启动】，否则运行相关剪贴板程序 termux-clipboard-get 和 termux-clipboard-set 都将表达为：挂起，没有反应。另外 termux-api 需要与 termux 同源安装，google play 或者 f-droid 只能二选一。如上是中文部分，留给后来者与搜索引擎参考。

其他 Android 13 应该都有这个问题

MIUI 14 notice: Termux-api needs to be set to [self-start], otherwise, running the related clipboard programs termux-clipboard-get and termux-clipboard-set will be expressed as: hanging and no response. In addition, termux-api needs to be co-installed with termux, you are limited to installing them on one platform, either Google Play or F-Droid, not both. The above is the English part, leave it to the latter ones and search engine reference.

All other Android 13 should have this problem too

![Screenshot_20230928094616](https://github.com/termux/termux-api/assets/67672527/1ec040e3-1f01-4903-adfc-845de7e8beb1)

**Comment by HusniMuhammad** [comment]
Where you downloaded form termux:api?


Where you downloaded from termux?

**Comment by zz5678** [comment]
found another bug victim: 
https://github.com/termux/termux-packages/issues/16411
