### ISSUE TITLE
[Bug] Unable to install due to signatures not matching

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [termux/termux-api#628]
**Problem description**

I am unable to install Termux-API. When I install the app through the android package installer (well, any file manager), it says that it conflicts with another package. When I try to install it through adb, I get a much better description as to what the problem is.
```
Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Reconciliation failed...: Reconcile failed: Package com.termux.api has no signatures that match those in shared user com.termux; ignoring!]
```

**Steps to reproduce**

Just try to install the app through f-droid, or the apk from github.

**Expected behavior**

The app should get installed

**Additional information**

* termux-api application version: v0.50.1
* termux-api package version (installed through apt):
* Android OS version: 14
* Device model: Google pixel 6a

**Comment by ego-lay-atman-bay** [comment]
I just looked at https://github.com/termux/termux-app#Installation and it turns out this isn't an issue. The problem is, I tried installing it through f-droid first, which was where I installed termux, so I have no idea why the sigatures are different.

**Comment by ego-lay-atman-bay** [comment]
Actually, disregard all of this. Turns out I just have another repository in my f-droid that also has the termux apps on it, and that one apparently was the default repo instead of the f-droid repo.

**Comment by agnostic-apollo** [comment]
Which custom repo?

**Comment by ego-lay-atman-bay** [comment]
> Which custom repo?

[Kali NetHunter App Store.](https://store.nethunter.com/repo)

The repo description is 
> This is the official Kali NetHunter App Store. Applications in this repository are official binaries built by the original application developers.

**Comment by twaik** [comment]
We are not supporting Kali and all related stuff. https://wiki.termux.com/wiki/Hacking

**Comment by agnostic-apollo** [comment]
Ah, still on 0.95 of termux app.

https://store.nethunter.com/en/packages/2/index.html

@twaik dude, I literally asked him.

**Comment by twaik** [comment]
Sorry, I was triggered by `Kali` word.

**Comment by agnostic-apollo** [comment]
Might wanna book some therapy sessions ;)
