### ISSUE TITLE
termux-sms-send does not work

### ISSUE THREAD

**Issue by adamerso** [termux/termux-api#629]
**Problem description**

termux-sms-send does not work - it hangs silently, I cannot grant
`OnePlus9Pro:/ # pm grant com.termux android.permission.READ_PHONE_STATE`
since it ends with error 
`java.lang.SecurityException: Package com.termux has not requested permission android.permission.READ_PHONE_STATE`

**Steps to reproduce**

`pkg install termux-api`
`termux-sms-send -n 4811111111 -s 1 "test"`

**Expected behavior**

simply to work :)

**Additional information**

* termux-api application version: 0.57
* termux-api package version (installed through apt): 0.57
* Android OS version: 13
* Device model: oneplus 9 pro

**Comment by Grimler91** [comment]
Seems like you haven't install the termux-api app. Latest released version is 0.50.1: https://github.com/termux/termux-api/releases

**Comment by adamerso** [comment]
Yes, that was the problem. Sorry for not noticing that in manual :)
