### ISSUE TITLE
Termux:API commands return `Native registration unable to find class 'com/android/icu/text/TimeZoneNamesNative'; aborting...` inside Proot on Galaxy A10 with Android 13 (LineageOS 20)

### ISSUE THREAD

**Issue by UrNightmaree** [termux/termux-api#639]
**Problem description**

Every Termux:API commands (including non-packaged into `termux-api`, like `termux-open`) returns an output:
```
Native registration unable to find class 'com/android/icu/text/TimeZoneNamesNative'; aborting...
```
Even if the all required environmnet variables to have most Termux:API commands to work. (Sourcing `/etc/profile.d/termux-proot.sh` if rootfs installed using `proot-distro`)

**Steps to reproduce**

1. `exec pd login alpine --user urnaree`
2. Any commands that run the libexec Termux:API or `am`. Example: `termux-toast hello`

**Expected behavior**

Successfully run the command.

**Additional information**

* termux-api application version: `0.50.1+b732327`
* termux-api package version (installed through pacman): `0.57-0`
* Android OS version: Android 13
* Device model: A105G
* SELinux: Enforcing
* Zsh script to patch Termux commands inside Proot:
```zsh
[[ -d "/data/data/com.termux" ]] && {
    export TERM=xterm-256color
    export TMPDIR=/tmp
    export PULSE_SERVER=127.0.0.1
    export MOZ_FAKE_NO_SANDBOX=1
    export ANDROID_ART_ROOT='/apex/com.android.art'
    export ANDROID_DATA='/data'
    export ANDROID_I18N_ROOT='/apex/com.android.i18n'
    export ANDROID_ROOT='/system'
    export ANDROID_TZDATA_ROOT='/apex/com.android.tzdata'
    export BOOTCLASSPATH='/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/smartbondingservice.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/knoxanalyticssdk.jar:/system/framework/fipstimakeystore.jar:/system/framework/timakeystore.jar:/system/framework/knoxsdk.jar:/system/framework/drutils.jar:/system/framework/framework-atb-backward-compatibility.jar:/system/framework/SmpsManager.jar:/system/framework/esecomm.jar:/system/framework/uibc_java.jar:/system/framework/ICDVerification.jar:/apex/com.android.conscrypt/javalib/conscrypt.jar:/apex/com.android.media/javalib/updatable-media.jar:/apex/com.android.mediaprovider/javalib/framework-mediaprovider.jar:/apex/com.android.os.statsd/javalib/framework-statsd.jar:/apex/com.android.permission/javalib/framework-permission.jar:/apex/com.android.sdkext/javalib/framework-sdkextensions.jar:/apex/com.android.wifi/javalib/framework-wifi.jar:/apex/com.android.tethering/javalib/framework-tethering.jar'
    export COLORTERM='truecolor'
    export DEX2OATBOOTCLASSPATH='/apex/com.android.art/javalib/core-oj.jar:/apex/com.android.art/javalib/core-libart.jar:/apex/com.android.art/javalib/core-icu4j.jar:/apex/com.android.art/javalib/okhttp.jar:/apex/com.android.art/javalib/bouncycastle.jar:/apex/com.android.art/javalib/apache-xml.jar:/system/framework/framework.jar:/system/framework/ext.jar:/system/framework/telephony-common.jar:/system/framework/smartbondingservice.jar:/system/framework/voip-common.jar:/system/framework/ims-common.jar:/system/framework/knoxanalyticssdk.jar:/system/framework/fipstimakeystore.jar:/system/framework/timakeystore.jar:/system/framework/knoxsdk.jar:/system/framework/drutils.jar:/system/framework/framework-atb-backward-compatibility.jar:/system/framework/SmpsManager.jar:/system/framework/esecomm.jar:/system/framework/uibc_java.jar:/system/framework/ICDVerification.jar'
    export EXTERNAL_STORAGE='/sdcard'

    termux_path="/data/data/com.termux/files/usr/bin"
    path=("${path[@]/$termux_path}")
}
```

**Comment by Grimler91** [comment]
Looks like you are not binding /system, /data and /apex in alpine, so I guess those paths are unavailable?

**Comment by UrNightmaree** [comment]
> Looks like you are not binding /system, /data and /apex in alpine, so I guess those paths are unavailable?

It does available
```
😼 # urnaree@localhost : ~
0% ls / | grep -E "apex|data|system"
apex
data
system
```

**Comment by TomJo2000** [comment]
Please be aware that parsing `ls` inside a script is inherently flawed and does not work for some weird, but valid, filename edge cases.

Generally it is preferable to use `find` or to loop over a directory directly, e.g.
```bash
for file in ./*; do
    : "$file" # stuff
done
```

For more detailed explanations and examples see:
https://mywiki.wooledge.org/ParsingLs

**Comment by UrNightmaree** [comment]
> Are environment variables not getting configured, so you need to setup them manually?

Technically, I'm not setting it up manually. Instead I copy the content of `<rootfs>/etc/profile.d/termux-proot.sh` due to the file isn't sourced by Zsh.

**Comment by UrNightmaree** [comment]
I replaced `BOOTCLASSPATH` and `DEX2OATBOOTCLASSPATH` variables, and it works fine now.

**Comment by diyar-azhir** [comment]
> I replaced `BOOTCLASSPATH` and `DEX2OATBOOTCLASSPATH` variables, and it works fine now.

which values did you replace with?

**Comment by Sanksrdas** [comment]
Free fire mein photo hai short complifier

**Comment by Visuals244** [comment]
This cypher is aknowledge very powerfull one coin you make energy to infity. Price and gass to listing weekly this, this important cause you want to universe like a you imagine you can buy this coin
