### ISSUE TITLE
Add android.permission.CALL_PHONE

### ISSUE THREAD

**Issue by rgh36167** [termux/termux-api#65]
I am trying to start a phone call like `/system/bin/service call phone 2 s16 1-808-456-XXXX` and get an error saying I need this permission. Could it be added? Would it work at all?

**Comment by fornwall** [comment]
A new `termux-telephony-call <number>` utility has been added. It takes care of prompting for the required CALL_PHONE permission.

This requires:

1. Version 0.15 of the Termux:API app which has been released and should be available as an update shortly.
2. Version 0.23 of the termux-api package (available now, run `packages up` to get it).
