### ISSUE TITLE
termux-notification actions don't work

### ISSUE THREAD

**Issue by ErrrorMaxx** [termux/termux-api#653]
**Problem description**

Instead of executing termux-notification button's action, wakelock is stopped and no action really executed

**Steps to reproduce**

```
termux-wake-lock
termux-notification -i sshd -c '...' --priority max --ongoing --button1 'Stop' --button1-action 'termux-notification-remove sshd'
```
and press 'Stop' button on notification

**Expected behavior**

Wakelock is still here and action actually works

**Additional information**

* termux-api application version: 0.50.1+b732327
* termux-api package version (installed through apt): 0.58.0
* Android OS version: 13
* Device model: Tecno Camon 20 Pro 5G

**Comment by ErrrorMaxx** [comment]
... Notifications itself works (shows). Click actions works. Button actions DO NOT

**Comment by BruceLee027** [comment]
Witam, mam problem ktoś hakuje mój telefon i wi fi czy jest jakiś sposób
żeby się przed tym obronić?

pon., 12 lut 2024, 06:04 użytkownik ErrrorMaxx ***@***.***>
napisał:

**Comment by BruceLee027** [comment]
Co to za problem , co muszę zrobić żeby działało

czw., 15 lut 2024, 10:19 użytkownik Łukasz Machała <
***@***.***> napisał:

**Comment by twaik** [comment]
1. Official language here is English. We do not offer support in other languages.
2. We do not help with hacking. https://wiki.termux.com/wiki/Hacking

**Comment by ErrrorMaxx** [comment]
I think this is actually the same issue as in https://github.com/termux/termux-api/issues/677

Because after this line:
```shell
termux-notification --action "termux-dialog" -t Suspicious -c NotReally
```

This line now works:
```shell
termux-notification -i sshd -c '...' --priority max --ongoing --button1 'Stop' --button1-action 'termux-notification-remove sshd'
```
But incurrectly: Button1 works, but runs `termux-dialog` instead of `termux-notification-remove sshd`

Closing this issue in favor of https://github.com/termux/termux-api/issues/677

**Comment by SpaceEngineer17** [comment]
Have you done any research where the problem is?

**Comment by ErrrorMaxx** [comment]
No, I'm not. But problem gone after downgrading to latest release

**Comment by ErrrorMaxx** [comment]
I don't understand what do you mean by "source code is same". SAF was implemented literraly way later than latest release happened

**Comment by SpaceEngineer17** [comment]
Oh, I thought the latest build ([v0.50.1](https://github.com/termux/termux-api/releases/tag/v0.50.1)) was made with the present source code.

Now I understood they are different.
Thank you.


So the `termux-notification` actions bug might came from one of these [changes](https://github.com/termux/termux-api/compare/v0.50.1...master) , I guess.
