### ISSUE TITLE
لماذا هذا الخطأ عند تثبيت تطبيق API

### ISSUE THREAD

**Issue by trky-homs** [termux/termux-api#660]
![Screenshot_٢٠٢٤٠٢١٥_١٥٣٥٢٢_NetHunter Store](https://github.com/termux/termux-api/assets/126033530/c289f43e-93f3-4b45-9ef9-8d00ab6bcab9)

أرجو المساعدة مع جزيل الشكر

**Comment by twaik** [comment]
Official language in all termux repos is English. We do not offer support in other languages.
