### ISSUE TITLE
termux-vibrate only works with durations bigger than 1000 ms

### ISSUE THREAD

**Issue by nemalex** [termux/termux-api#666]
**Problem description**

`termux-vibrate` only works with durations bigger than 1000 ms

**Steps to reproduce**

Run `termux-vibrate -d 100`

**Expected behavior**

Vibration happens with any positive duration

**Additional information**

* termux-api application version: 0.50.1
* termux-api package version (installed through apt): 0.58.0-1
* Android OS version: 14
* Device model: willow, Xiaomi Redmi Note 8T

**Comment by agnostic-apollo** [comment]
Thanks for the report, should be fixed.

**Comment by nemalex** [comment]
Thanks!

**Comment by nemalex** [comment]
I'm not able to install the debug apk
I get an app conflict error, even after uninstalling the prevous version
