### ISSUE TITLE
Add `capabilities` to the output of termux-wifi-scaninfo

### ISSUE THREAD

**Issue by 37eex9** [termux/termux-api#676]
**Feature description**

For the `termux-wifi-scaninfo` command I'd like to get the `capabilities` string. This should include information about the wifi security. E.g., whether this AP does support WPA2, WPA3, WEP or no encryption.

**Reference implementation**

_Have you checked if the feature is accessible through the Android API?_
The [Android API documentation](https://developer.android.com/reference/android/net/wifi/ScanResult#capabilities) states, that there is a `capabilities` field in the `ScanResult` object.

_Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)_
[WifiAnalyzer](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/) show those capabilities I'm interested in. Unfortunately, I could not find the exact implementation within their repository.

I think it should be done by adding the line
```
                        out.name("capabilities").value(scan.capabilities);
```
to the [WifiAPI](https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/apis/WifiAPI.java) in the brackets between line 76 and 115.

Up to now, I did not have the time to test it by myself. If I did, I'll open a pull request, but maybe someone else is faster ;)

**Comment by agnostic-apollo** [comment]
Should be available in github action builds.

- https://github.com/termux/termux-api/actions/runs/8852822919

**Comment by shallow-beach** [comment]
@agnostic-apollo apologies if I am missing the obvious, but on the latest pre-release [v0.119.0-beta.1](https://github.com/termux/termux-app/releases/tag/v0.119.0-beta.1) of termux and most recent release (v0.50.1) of termux-api, I still don't see the "capabilities" value in the results of either `termux-wifi-scaninfo` or `termux-wifi-connectioninfo`. where were they added?

**Comment by shallow-beach** [comment]
> Should be available in github action builds.
> 
> * https://github.com/termux/termux-api/actions/runs/8852822919

apologies if i am missing something obvious, but the build file is expired so can't be downloaded.

**Comment by agnostic-apollo** [comment]
Check https://github.com/termux/termux-api/actions/runs/10155362023

**Comment by shallow-beach** [comment]
> Check https://github.com/termux/termux-api/actions/runs/10155362023

(Please feel free to ignore this question, as it is more generally about how GitHub works.) Was there just a timed expiration date on the old commit, or did other people committing their own master branches cause the expiration to trigger?

**Comment by agnostic-apollo** [comment]
GitHub action artifacts expire after 90 days. I have fixed it locally by triggering rebuild, will get pushed soon with the next release along with termux-widget.
