### ISSUE TITLE
`termux-wifi-connectioninfo` doesn't halt

### ISSUE THREAD

**Issue by KernelDeimos** [termux/termux-api#696]
**Problem description**

This command displays no output and doesn't halt. I found a [reddit post](https://www.reddit.com/r/termux/comments/yunwop/termuxwifi_commands_return_nothing_infinite_loop/) from someone who observed the same thing. A comment says to enable location access to `termux-api` but I don't see termux-api in Settings->apps (because it's... not an app) and I don't see any option to grant this permission to Termux. I'm nearly certain I'm missing something but I'm posting this as an issue anyway since infinite-looping/idling is probably not the intended outcome.

**Steps to reproduce**

```
pkg update
pkg install termux-api
termux-wifi-connectioninfo
```

**Expected behavior**

Outputs wifi info in JSON

**Additional information**

* termux-api application version: what is this?
* termux-api package version (installed through apt): 0.58.0-1
* Android OS version:  14
* Device model: Pixel 7a

**Comment by Grimler91** [comment]
Termux-api app needs to be installed, here it is at f-droid: https://f-droid.org/packages/com.termux.api/, and github: https://github.com/termux/termux-api/releases/tag/v0.50.1
