### ISSUE TITLE
We need python virtualenv

### ISSUE THREAD

**Issue by user-11150** [termux/termux-api#698]
**Feature description**

**Reference implementation**

Have you checked if the feature is accessible through the Android API?
Do you know of other open-source apps that has a similar feature as the one you want? (Provide links)

**Comment by TomJo2000** [comment]
Python virtual environments are available in the `python` package on Termux.
They are not an Android feature, and their availability can not be checked through Termux-API.

**Comment by user-11150** [comment]
Thansks
