### ISSUE TITLE
Unable to pop up usb authorization

### ISSUE THREAD

**Issue by Superstupid-UX** [termux/termux-api#702]
I can't connect to the device after executing termux-usb -r "..." adb devices cannot obtain the device, cannot execute any adb instructions, and cannot pop up the usb authorization.

**Comment by Grimler91** [comment]
Do you have the termux-api app installed? Share your versions of the apps and your output of `termux-info`

**Comment by Superstupid-UX** [comment]
> 您是否安装了 termux-api 应用程序？共享您的应用程序版本和输出`termux-info`

Yes, I installed version 0.50.1 termux0.118.1 I executed
termux-usb -r usbdev and show Access granted. But I tried to control another device with adb commands, and he still told me that the device could not be found, and the error was as follows
* daemon not running; starting now at tcp:5037
* daemon started successfully
error: no devices/emulators found

**Comment by Grimler91** [comment]
termux-usb can provide a file descriptor that other software can use, but other software have to be patched to make use of it. 

Easiest is to use the `-E` flag of `termux-usb`, and then patch your software to get the file descriptor from the env var `TERMUX_USB_FD`. For software that use libusb you do this by basically replacing `libusb_open` with `libusb_wrap_sys_device`, see for example [this old patch](https://github.com/Grimler91/ttwatch/commit/1ad9f96f596efed5c5e1fc76fdabeaeba0cfab1b#diff-ccaccb0f3e4989f1f6a066a334ef440e2afa2137b2a4a8c36e7b893bb9e1a5c3R339-L373) (where I did not use the env var though, so it is more complicated than it has to be). 

From your output it looks like you are running adb? It will not work out of the box, best bet would be to use adb-over-wifi, if that works for your use case.

There is some room for improvements of termux-usb (and termux-api in general), especially for user-friendliness of it, but it has unfortunately not been high enough on anyone's TODO list..
