### ISSUE TITLE
termux-sms-send - messages sent via Termux don't appear in standard SMS apps

### ISSUE THREAD

**Issue by wardrich** [termux/termux-api#72]
I'm not an Android app developer, so I don't understand exactly how it all works, but it is to my understanding that there is an SMS database that standard SMS applications hook into.  I was wondering if there was any way that Termux could append sent SMS messages to this database so that the messages will appear in standard SMS applications.

**Comment by xeffyr** [comment]
Closing as SMS feature was removed in https://github.com/termux/termux-api/commit/de44896a01111506590a258f0267400af067b778.
