### ISSUE TITLE
termux-usb -e ./usbtest /dev/bus/usb/001/004 No permission

### ISSUE THREAD

**Issue by pastij** [termux/termux-api#733]
**Problem description**
termux-usb -e ./usbtest /dev/bus/usb/001/004
No permission
saya mencoba menggunakan adb di termux tetapi device target tidak terdeteksi lalu saya mencoba install termux api 0.50.1 itu berhasil terdeteksi tapi adb saya tetap tidak mau terdeteksi mohon bantuannya 

**Steps to reproduce**

**Expected behavior**

**Additional information**

* termux-api application version:Versi 0.50.1 (51)
* termux-api package version (installed through apt):
* Android OS version:14
* Device model:Redmi note 12 pro 5g

**Comment by twaik** [comment]
Official language here is English.
