### ISSUE TITLE
termux-notification: Action for dismissal of notification

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#81]
I would like to be able to define an action for the dismissal of a notification. https://github.com/Neo-Oli/Termux-Mpv/issues/6 needs this. 
I'm not sure this is even possible, I can't recall any app that does something when a notification is dismissed.

**Comment by fornwall** [comment]
Hm, it actually seems to be possible by using [setDeleteIntent](https://developer.android.com/reference/android/app/Notification.Builder.html#setDeleteIntent(android.app.PendingIntent)).

http://stackoverflow.com/questions/14671453/catch-on-swipe-to-dismiss-event for more has more information and examples.

**Comment by fornwall** [comment]
This is now possible by passing the new `--on-delete 'things to execute'` parameter to `termux-notification`. Requires:

1. Version 0.15 of the Termux:API app which has been released and should be available as an update shortly.
2. Version 0.23 of the termux-api package (available now, run `packages up` to get it).
