### ISSUE TITLE
termux-notification: Error when --on-delete isn't specified

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#83]
There seems to be a problem with termux-notification after the last update. If the new `--on-delete` (which is great by the way) isn't specified there is an error. 
```
$ termux-notification -c "test"
/data/data/com.termux/files/usr/bin/termux-notification: line 98: OPT_ON_DELETE_ACTION: unbound variable
$ termux-notification -c "test" --on-delete "ls"
```

**Comment by fornwall** [comment]
Thanks - fixed in the 0.24 update of the termux-api package!
