### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by aelmahdaoui** [termux/termux-api#85]
I am trying to connect my android phone to a bluetooth module and find out which serial port is being assigned. However if I try:
`ls /dev/tty*`
I get "No such file or directory. If I do:
`ls /dev/tty`
I get 

> /dev/tty

If I do 
`ls /dev/tt*`
I get "No such file or directory" again.

How I can I find the port assigned?

**Comment by Grimler91** [comment]
Seems very weird that no interfaces at all are listed. Is this still an issue? I'll re-open in that case.
