### ISSUE TITLE
Termux-api doesn't work when running it under `termux-chroot`

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-api#89]
It just hangs forever like it does when the Termux:API package isn't installed

```
$ time termux-vibrate

real    0m0.922s
user    0m0.040s
sys     0m0.000s
$ termux-chroot
$ time termux-vibrate
^C

real    0m10.236s
user    0m0.000s
sys     0m0.020s
$
```

What is the reason for this and is there any way to make it work?

**Comment by ebpa** [comment]
Possibly related to this:
This hang behavior also occurs when invoking termux commands from a shell running within Emacs (M-x shell).

The app is installed, the termux-api package is installed, and the command runs as expected when run from a plain shell.

**Comment by Neo-Oli** [comment]
Apparently this now works.
