### ISSUE TITLE
termux-get-wakelock, or maybe fix shell/sleep?

### ISSUE THREAD

**Issue by rgh36167** [termux/termux-api#93]
I have a script which is supposed to fetch an url every 10 minutes and uses sleep. Unless I acquire a wakelock for termux it won't work as expected but randomly sleep much longer. Getting the wakelock  manually is a hassle and easily forgotten..

BTW I found that having a wakelock isn't a noticeable problem for battery life.

**Comment by fornwall** [comment]
The two commands `termux-wake-lock` and `termux-wake-unlock` are already available - do they do what you want?

**Comment by rgh36167** [comment]
perfect.. will give it some longer testing tomorrow but seems exactly what I need.

**Comment by rgh36167** [comment]
works nicely:)

**Comment by j0y101** [comment]
wakelock aint working!!

**Comment by Quasic** [comment]
I don't think it's supposed to prevent other sleeping, such as the screen turning off, just running Termux processes, in case you had the same confusion I did...
