### ISSUE TITLE
termux-sms-send : add an option for choosing SIM card

### ISSUE THREAD

**Issue by flyinva** [termux/termux-api#96]
On dual SIM phones, termux-sms-send can only send SMS with default SIM. Could be possible to add an option to use another SIM ?

Example:

```
termux-sms-send -n 1234567890 "text on SIM 1"
termux-sms-send -s 2 -n 1234567890 "text on SIM 2"
```

**Comment by LoveMHz** [comment]
Looks like multi sim support was added in [Android 5.1](https://developer.android.com/about/versions/android-5.1.html#multisim). 

I believe we can use getSmsManagerForSubscriptionId(). [#ref ](https://github.com/subhechhu/AutoMsg/blob/ae5039d48964ce41465a0a37fd7a00f1b4a9dca1/app/src/main/java/com/subhechhu/automessage/message/AlarmReceiver.java#L106)

Should we bump minSdkVersion to 22?

**Comment by jim3ma** [comment]
Same request.

**Comment by guerby** [comment]
Would be nice to have! Thanks.

**Comment by monperrus** [comment]
What's the behavior with two SIMs? It chooses one or it does not work?

**Comment by flyinva** [comment]
termux-sms-send can only use first SIM

**Comment by kingrony** [comment]
How to solve Google permit problem sending sms with termux

**Comment by xeffyr** [comment]
> How to solve Google permit problem sending sms with termux

You can't solve it because api was disabled at application level: https://github.com/termux/termux-api/commit/de44896a01111506590a258f0267400af067b778

**Comment by xeffyr** [comment]
Closing as SMS feature was removed in https://github.com/termux/termux-api/commit/de44896a01111506590a258f0267400af067b778.
